### ISSUE TITLE
Error on "gvsbuild build gtk4"

### ISSUE THREAD

**Issue by marisaa-kirisame** [wingtk/gvsbuild#1064]
When running "gvsbuild build gtk4" the following error occurs:

https://pastebin.com/dN70ReSn

I have censored out my computer user name for privacy reasons.

**Comment by danyeaw** [comment]
Hi @marisaa-kirisame! It looks like an issue with your MSYS2 installation. Do you know what the errors are related to the missing signatures near the start of the log?

**Comment by marisaa-kirisame** [comment]
I don't know.

**Comment by danyeaw** [comment]
@marisaa-kirisame There are instructions to fix it here: https://www.msys2.org/news/#2020-06-29-new-packagers

```
$ curl -O https://repo.msys2.org/msys/x86_64/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz
$ curl -O https://repo.msys2.org/msys/x86_64/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz.sig

$ pacman-key --verify msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz.sig
==> Checking msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz.sig... (detached)
gpg: Signature made Mon Jun 29 07:36:14 2020 CEST
gpg:                using DSA key AD351C50AE085775EB59333B5F92EFC1A47D45A1
gpg: Good signature from "Alexey Pavlov (Alexpux) <alexpux@gmail.com>" [full]

# pacman -U msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz
```

You could also uninstall MSYS2 and reinstall it. I think this is causing Gvsbuild to fail because it can't download the packages it needs.

**Comment by danyeaw** [comment]
Since I think this was an issue with your MSYS2 install and not Gvsbuild, I am going to go ahead and close this. If you are still having issues, please feel free to open it back up. Thanks!
