### ISSUE TITLE
libadwaita 1.4 isn't buildable with Gvsbuild

### ISSUE THREAD

**Issue by danyeaw** [wingtk/gvsbuild#1075]
libadwaita now depends on AppStream
AppStream depends on libxmlb
libxmlb makes use of g_autoptr, which isn't supported with MSVC.

So we have no upgrade path with libadwaita unless we can work with the other projects to:
1. Make the AppStream dependency optional
2. Allow use of a different xml library in AppStream (I'm not sure how feasible this is)
3. Remove use of g_autoptr in libxmlb

**Comment by danyeaw** [comment]
The other option may be to use clang-cl.exe for building.

**Comment by danyeaw** [comment]
@fanc999 I know you have been experimenting with clang-cl for glib builds. Do you think this is the direction we should be heading?

**Comment by nacho** [comment]
Dan I think we should start by filing a ticket to libadwaita. Do you have already a ticket upstream?

**Comment by danyeaw** [comment]
https://gitlab.gnome.org/GNOME/libadwaita/-/merge_requests/833

https://gitlab.gnome.org/GNOME/libadwaita/-/issues/659

**Comment by danyeaw** [comment]
Closed by #1076. It would still be nice to be able to build Appstream for Windows so that we don't need to patch libadwaita, but we don't need an open issue for that.
