### ISSUE TITLE
Current gvsbuild release has incompatible GTK and libadwaita version

### ISSUE THREAD

**Issue by mitchhentges** [wingtk/gvsbuild#1121]
Libadwaita 1.3 doesn't seem to be fully compatible with GTK 3.12.x, as the rendering of `AdwEntryRow` has lost its vertical centering:

![image](https://github.com/wingtk/gvsbuild/assets/7784737/bbb2f7ce-b8e8-4d36-b18d-466595746fdc)

This is affecting `gvsbuild>=2023.8.0`, since that's when the major version of GTK was bumped. Fortunately, there's a workaround: use `gvsbuild==2023.7.1` in the meantime.

From some testing on Linux, it looks like Libadwaita 1.4 will resolve this, which is good ([and there's already a PR to update it for `gvsbuild`, nice!](https://github.com/wingtk/gvsbuild/pull/1076)).

-----

Unfortunately, there isn't a nice obvious solution here. The two I can think of are
1. Stay the course, try to keep packages up-to-date, even if other packages become "weakly" incompatible. This is what is currently happening.
    * Downside: when incompatibilities happen, people will have to deliberately use an old `gvsbuild`
2. If a package upgrade causes breakages, then wait and try to bump packages all together
    * Downside: it can be tricky to detect breakages like this `libadwaita` one, where specific UI elements look wrong
    * Downside: people who aren't using the dependent package - and therefore aren't affected by the breakage - will have to wait longer for updates to the "dependee" package

I think that option 1 is better, so this ticket isn't really actionable :)
However, I think that:
* Perhaps someone may come up with a better solution
* In the meantime, if others are running into the weird "vertical alignment" issue that I was, they'll be able to find this ticket and rule out that it's a local build problem.

**Comment by danyeaw** [comment]
Hi @mitchhentges, thanks for submitting the discussion.

Our goal is to keep versions as up to date as possible. If two versions become incompatible, that is an upstream issue to fix the compatibility, but we are glad to release a new gvsbuild to fix this if you provide a patch to fix the incompatibility or if the upstream library releases an update.

In this case, gvsbuild 2023.11.0 has libadwaita 1.4.0, so I think we can close this.
