### ISSUE TITLE
Missing libav plugin after building

### ISSUE THREAD

**Issue by kozliuk** [wingtk/gvsbuild#1126]
Hi everyone, I built the streamer for windows and can't use lib plugins (avdec_h265 elements). What did I do wrong?

**Comment by danyeaw** [comment]
Hi @kozliuk, I don't personally use GStreamer for any of my projects, so I need more guidance on what commands you used, what you were expecting to happen, and what you got instead. That way we can try to reproduce the issue. Thanks!

**Comment by kozliuk** [comment]
have already resolved the issue
