### ISSUE TITLE
Add librsvg to gtk4 dependencies

### ISSUE THREAD

**Issue by nazar-pc** [wingtk/gvsbuild#1185]
BTW`librsvg` is not a dependency of `gtk4` for some reason even though SVG icons are extremely common in apps, maybe consider adding it?

I suspect that the reason is that it takes a while to compile, but at the same time a lot of test cases and other utilities are built for GTK4 itself and other things that take significant amount of time.

**Comment by danyeaw** [comment]
Hi @nazar-pc, thanks for the suggestion. If you look at https://gitlab.gnome.org/GNOME/gtk/-/blob/main/meson.build, GTK does not depend on librsvg. If you build adwaita-icon-theme, it does depend on librsvg though.

**Comment by nazar-pc** [comment]
I know gtk4 itself doesn't, but it seems to make sense to include it so that SVG icons can be used. At least to me it was surprising that I installed gtk4 and librsvg that is supposedly needed for SVG icons support wasn't present. I do understand it is optional.

**Comment by danyeaw** [comment]
Would it help if we add a statement about this in the README? I don't think we should make things dependencies unless the library really depends on another library.

**Comment by nazar-pc** [comment]
Yes, I think mentioning this in readme would be sufficient
