### ISSUE TITLE
Add gtk4

### ISSUE THREAD

**Issue by nacho** [wingtk/gvsbuild#121]
Now that graphene is in we should be able to add gtk 4.

**Comment by nacho** [comment]
For this there is wip/gtk4 but there is still some work to do to make it build properly

**Comment by bigvzhang** [comment]
I'm waiting this. From my side, the  version is 3.24.17. Is it possible to build the latest version 3.24.23?

**Comment by acidtonic** [comment]
Any updates here?

**Comment by danyeaw** [comment]
GTK4 is supported :+1:
