### ISSUE TITLE
Install gvsbuild error

### ISSUE THREAD

**Issue by RustyAngler** [wingtk/gvsbuild#1228]
The instructions at 
_https://github.com/wingtk/gvsbuild?tab=readme-ov-file#install-gvsbuild_
gives an error at:

> python -m pip install --user pipx

"No Python at c:\Python311\python.exe"
due to previous command 

> choco install python

installed python 3.12.1
to fix I had to uninstall python 3.12 
and run command

> choco install python311

then continue the setup instructions

**Comment by danyeaw** [comment]
Hi @RustyAngler, thanks for the report. I actually have the best success using the Python from python.org and then using the Python launcher with `py -m pip install --user pipx`. We could update the README to recommend that instead, what do you think?

**Comment by RustyAngler** [comment]
Hi Dan
The python install part of the instructions installs the latest version, but the 

> python -m pip install --user pipx

called a specific (not latest) version, I think it would be better to fix this to not be version specific.
I am not a python user, and I don't understand why the _python -m pip ..._ call does not use the latest version installed.

**Comment by danyeaw** [comment]
Ya, Python Launcher with `py -m pip` would fix that, or you can even specify a version like `py -3.12 -m pip`
