### ISSUE TITLE
gtk4 build failed

### ISSUE THREAD

**Issue by PrabeshBastola** [wingtk/gvsbuild#1232]
FAILED: testsuite/gdk/gltexture.exe testsuite/gdk/gltexture.pdb
"link"  /MACHINE:x64 /OUT:testsuite/gdk/gltexture.exe testsuite/gdk/gltexture.exe.p/gltexture.c.obj "/release" "/nologo" "/DEBUG" "/PDB:testsuite\gdk\gltexture.pdb" "gtk/libgtk.a" "gtk/css/libgtk_css.a" "gdk/libgdk.a" "gsk/libgsk.a" "gsk/libgsk_f16c.a" "C:/gtk-build/gtk/x64/release/bin/../lib/gmodule-2.0.lib" "C:/gtk-build/gtk/x64/release/bin/../lib/glib-2.0.lib" "C:/gtk-build/gtk/x64/release/bin/../lib/intl.lib" "C:/gtk-build/gtk/x64/release/bin/../lib/gobject-2.0.lib" "C:/gtk-build/gtk/x64/release/bin/../lib/gio-2.0.lib" "C:/gtk-build/gtk/x64/release/bin/../lib/pangocairo-1.0.lib" "C:/gtk-build/gtk/x64/release/bin/../lib/pango-1.0.lib" "C:/gtk-build/gtk/x64/release/bin/../lib/harfbuzz.lib" "C:/gtk-build/gtk/x64/release/bin/../lib/cairo.lib" "C:/gtk-build/gtk/x64/release/bin/../lib/fribidi.lib" "C:/gtk-build/gtk/x64/release/bin/../lib/cairo-gobject.lib" "C:/gtk-build/gtk/x64/release/bin/../lib/gdk_pixbuf-2.0.lib" "C:/gtk-build/gtk/x64/release/bin/../lib/epoxy.lib" "C:/gtk-build/gtk/x64/release/bin/../lib/graphene-1.0.lib" "C:/gtk-build/gtk/x64/release/bin/../lib/pangowin32-1.0.lib" "advapi32.lib" "comctl32.lib" "crypt32.lib" "dwmapi.lib" "imm32.lib" "setupapi.lib" "winmm.lib" "intl.lib" "C:/gtk-build/gtk/x64/release/bin/../lib/libpng16.lib" "C:/gtk-build/gtk/x64/release/bin/../lib/tiff.lib" "C:/gtk-build/gtk/x64/release/bin/../lib/jpeg.lib" "hid.lib" "opengl32.lib" "C:/gtk-build/gtk/x64/release/bin/../lib/cairo-script-interpreter.lib" "advapi32.lib" "comctl32.lib" "crypt32.lib" "dwmapi.lib" "imm32.lib" "setupapi.lib" "winmm.lib" "intl.lib" "hid.lib" "opengl32.lib" "hid.lib" "opengl32.lib" "hid.lib" "opengl32.lib" "hid.lib" "opengl32.lib" "/SUBSYSTEM:CONSOLE" "kernel32.lib" "user32.lib" "gdi32.lib" "winspool.lib" "shell32.lib" "ole32.lib" "oleaut32.lib" "uuid.lib" "comdlg32.lib" "advapi32.lib"
   Creating library testsuite\gdk\gltexture.lib and object testsuite\gdk\gltexture.exp
[166/339] Linking target testsuite/gdk/image.exe
FAILED: testsuite/gdk/image.exe testsuite/gdk/image.pdb
"link"  /MACHINE:x64 /OUT:testsuite/gdk/image.exe testsuite/gdk/image.exe.p/image.c.obj "/release" "/nologo" "/DEBUG" "/PDB:testsuite\gdk\image.pdb" "gtk/libgtk.a" "gtk/css/libgtk_css.a" "gdk/libgdk.a" "gsk/libgsk.a" "gsk/libgsk_f16c.a" "C:/gtk-build/gtk/x64/release/bin/../lib/gmodule-2.0.lib" "C:/gtk-build/gtk/x64/release/bin/../lib/glib-2.0.lib" "C:/gtk-build/gtk/x64/release/bin/../lib/intl.lib" "C:/gtk-build/gtk/x64/release/bin/../lib/gobject-2.0.lib" "C:/gtk-build/gtk/x64/release/bin/../lib/gio-2.0.lib" "C:/gtk-build/gtk/x64/release/bin/../lib/pangocairo-1.0.lib" "C:/gtk-build/gtk/x64/release/bin/../lib/pango-1.0.lib" "C:/gtk-build/gtk/x64/release/bin/../lib/harfbuzz.lib" "C:/gtk-build/gtk/x64/release/bin/../lib/cairo.lib" "C:/gtk-build/gtk/x64/release/bin/../lib/fribidi.lib" "C:/gtk-build/gtk/x64/release/bin/../lib/cairo-gobject.lib" "C:/gtk-build/gtk/x64/release/bin/../lib/gdk_pixbuf-2.0.lib" "C:/gtk-build/gtk/x64/release/bin/../lib/epoxy.lib" "C:/gtk-build/gtk/x64/release/bin/../lib/graphene-1.0.lib" "C:/gtk-build/gtk/x64/release/bin/../lib/pangowin32-1.0.lib" "advapi32.lib" "comctl32.lib" "crypt32.lib" "dwmapi.lib" "imm32.lib" "setupapi.lib" "winmm.lib" "intl.lib" "C:/gtk-build/gtk/x64/release/bin/../lib/libpng16.lib" "C:/gtk-build/gtk/x64/release/bin/../lib/tiff.lib" "C:/gtk-build/gtk/x64/release/bin/../lib/jpeg.lib" "hid.lib" "opengl32.lib" "C:/gtk-build/gtk/x64/release/bin/../lib/cairo-script-interpreter.lib" "advapi32.lib" "comctl32.lib" "crypt32.lib" "dwmapi.lib" "imm32.lib" "setupapi.lib" "winmm.lib" "intl.lib" "hid.lib" "opengl32.lib" "hid.lib" "opengl32.lib" "hid.lib" "opengl32.lib" "hid.lib" "opengl32.lib" "/SUBSYSTEM:CONSOLE" "kernel32.lib" "user32.lib" "gdi32.lib" "winspool.lib" "shell32.lib" "ole32.lib" "oleaut32.lib" "uuid.lib" "comdlg32.lib" "advapi32.lib"
   Creating library testsuite\gdk\image.lib and object testsuite\gdk\image.exp
[167/339] Linking target testsuite/gdk/texture.exe
FAILED: testsuite/gdk/texture.exe testsuite/gdk/texture.pdb
"link"  /MACHINE:x64 /OUT:testsuite/gdk/texture.exe testsuite/gdk/texture.exe.p/texture.c.obj "/release" "/nologo" "/DEBUG" "/PDB:testsuite\gdk\texture.pdb" "gtk/libgtk.a" "gtk/css/libgtk_css.a" "gdk/libgdk.a" "gsk/libgsk.a" "gsk/libgsk_f16c.a" "C:/gtk-build/gtk/x64/release/bin/../lib/gmodule-2.0.lib" "C:/gtk-build/gtk/x64/release/bin/../lib/glib-2.0.lib" "C:/gtk-build/gtk/x64/release/bin/../lib/intl.lib" "C:/gtk-build/gtk/x64/release/bin/../lib/gobject-2.0.lib" "C:/gtk-build/gtk/x64/release/bin/../lib/gio-2.0.lib" "C:/gtk-build/gtk/x64/release/bin/../lib/pangocairo-1.0.lib" "C:/gtk-build/gtk/x64/release/bin/../lib/pango-1.0.lib" "C:/gtk-build/gtk/x64/release/bin/../lib/harfbuzz.lib" "C:/gtk-build/gtk/x64/release/bin/../lib/cairo.lib" "C:/gtk-build/gtk/x64/release/bin/../lib/fribidi.lib" "C:/gtk-build/gtk/x64/release/bin/../lib/cairo-gobject.lib" "C:/gtk-build/gtk/x64/release/bin/../lib/gdk_pixbuf-2.0.lib" "C:/gtk-build/gtk/x64/release/bin/../lib/epoxy.lib" "C:/gtk-build/gtk/x64/release/bin/../lib/graphene-1.0.lib" "C:/gtk-build/gtk/x64/release/bin/../lib/pangowin32-1.0.lib" "advapi32.lib" "comctl32.lib" "crypt32.lib" "dwmapi.lib" "imm32.lib" "setupapi.lib" "winmm.lib" "intl.lib" "C:/gtk-build/gtk/x64/release/bin/../lib/libpng16.lib" "C:/gtk-build/gtk/x64/release/bin/../lib/tiff.lib" "C:/gtk-build/gtk/x64/release/bin/../lib/jpeg.lib" "hid.lib" "opengl32.lib" "C:/gtk-build/gtk/x64/release/bin/../lib/cairo-script-interpreter.lib" "advapi32.lib" "comctl32.lib" "crypt32.lib" "dwmapi.lib" "imm32.lib" "setupapi.lib" "winmm.lib" "intl.lib" "hid.lib" "opengl32.lib" "hid.lib" "opengl32.lib" "hid.lib" "opengl32.lib" "hid.lib" "opengl32.lib" "/SUBSYSTEM:CONSOLE" "kernel32.lib" "user32.lib" "gdi32.lib" "winspool.lib" "shell32.lib" "ole32.lib" "oleaut32.lib" "uuid.lib" "comdlg32.lib" "advapi32.lib"
   Creating library testsuite\gdk\texture.lib and object testsuite\gdk\texture.exp
[168/339] Linking target gtk/gtk-4-1.dll
FAILED: gtk/gtk-4-1.dll gtk/gtk-4-1.pdb
"link"  /MACHINE:x64 /OUT:gtk/gtk-4-1.dll  "/release" "/nologo" "/DEBUG" "/PDB:gtk\gtk-4-1.pdb" "/DLL" "/IMPLIB:gtk\gtk-4.lib" "/WHOLEARCHIVE:gtk/libgtk.a" "/WHOLEARCHIVE:gtk/css/libgtk_css.a" "/WHOLEARCHIVE:gdk/libgdk.a" "/WHOLEARCHIVE:gsk/libgsk.a" "gtk/libgtk.a" "gtk/css/libgtk_css.a" "gdk/libgdk.a" "gsk/libgsk.a" "gsk/libgsk_f16c.a" "C:/gtk-build/gtk/x64/release/bin/../lib/gmodule-2.0.lib" "C:/gtk-build/gtk/x64/release/bin/../lib/glib-2.0.lib" "C:/gtk-build/gtk/x64/release/bin/../lib/intl.lib" "C:/gtk-build/gtk/x64/release/bin/../lib/gobject-2.0.lib" "C:/gtk-build/gtk/x64/release/bin/../lib/gio-2.0.lib" "C:/gtk-build/gtk/x64/release/bin/../lib/pangocairo-1.0.lib" "C:/gtk-build/gtk/x64/release/bin/../lib/pango-1.0.lib" "C:/gtk-build/gtk/x64/release/bin/../lib/harfbuzz.lib" "C:/gtk-build/gtk/x64/release/bin/../lib/cairo.lib" "C:/gtk-build/gtk/x64/release/bin/../lib/fribidi.lib" "C:/gtk-build/gtk/x64/release/bin/../lib/cairo-gobject.lib" "C:/gtk-build/gtk/x64/release/bin/../lib/gdk_pixbuf-2.0.lib" "C:/gtk-build/gtk/x64/release/bin/../lib/epoxy.lib" "C:/gtk-build/gtk/x64/release/bin/../lib/graphene-1.0.lib" "C:/gtk-build/gtk/x64/release/bin/../lib/pangowin32-1.0.lib" "advapi32.lib" "comctl32.lib" "crypt32.lib" "dwmapi.lib" "imm32.lib" "setupapi.lib" "winmm.lib" "intl.lib" "C:/gtk-build/gtk/x64/release/bin/../lib/libpng16.lib" "C:/gtk-build/gtk/x64/release/bin/../lib/tiff.lib" "C:/gtk-build/gtk/x64/release/bin/../lib/jpeg.lib" "hid.lib" "opengl32.lib" "C:/gtk-build/gtk/x64/release/bin/../lib/cairo-script-interpreter.lib" "advapi32.lib" "comctl32.lib" "crypt32.lib" "dwmapi.lib" "imm32.lib" "setupapi.lib" "winmm.lib" "intl.lib" "hid.lib" "opengl32.lib" "hid.lib" "opengl32.lib" "hid.lib" "opengl32.lib" "hid.lib" "opengl32.lib" "kernel32.lib" "user32.lib" "gdi32.lib" "winspool.lib" "shell32.lib" "ole32.lib" "oleaut32.lib" "uuid.lib" "comdlg32.lib" "advapi32.lib"
   Creating library gtk\gtk-4.lib and object gtk\gtk-4.exp
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "C:\gtk-build\github\gvsbuild\.venv\Lib\site-packages\gvsbuild\utils\builder.py", line 527, in build
    if self.__build_one(p):
       ^^^^^^^^^^^^^^^^^^^
  File "C:\gtk-build\github\gvsbuild\.venv\Lib\site-packages\gvsbuild\utils\builder.py", line 663, in __build_one
    skip_deps = proj.build()
                ^^^^^^^^^^^^
  File "C:\gtk-build\github\gvsbuild\.venv\Lib\site-packages\gvsbuild\projects\gtk.py", line 151, in build
    Meson.build(
  File "C:\gtk-build\github\gvsbuild\.venv\Lib\site-packages\gvsbuild\utils\base_builders.py", line 56, in build
    self.builder.exec_ninja(params="install", working_dir=ninja_build)
  File "C:\gtk-build\github\gvsbuild\.venv\Lib\site-packages\gvsbuild\utils\builder.py", line 985, in exec_ninja
    self.__execute(
  File "C:\gtk-build\github\gvsbuild\.venv\Lib\site-packages\gvsbuild\utils\builder.py", line 1041, in __execute
    subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'ninja install' returned non-zero exit status 1.
Error: gtk4 build failed

**Comment by danyeaw** [comment]
Hi @PrabeshBastola, we need a lot more information if we are going to help. How did you install Gvsbuild, what is your setup, and what were you trying to build and how?
