### ISSUE TITLE
GTK App crashes with g_atomic_ref_count_dec: assertion 'old_value > 0' failed

### ISSUE THREAD

**Issue by danyeaw** [wingtk/gvsbuild#1289]
I am getting a g_atomic_ref_count_dec: assertion 'old_value > 0' failed error when trying to launch Gaphor which is a GTK4/PyGObject app.

Gvsbuild 2024.1.0 works
Gvsbuild 2024.2.0 and later does not. On CI/CD, I am also getting a Windows fatal exception: code 0xc0000374. I was also getting access error exceptions as well locally.

I am currently trying to narrow this down to what commit broke things. I would like to fix this before proceeding with trying to update to GTK 4.14 in #1279.

**Comment by pbor** [comment]
Could it be https://gitlab.gnome.org/GNOME/pango/-/merge_requests/726 ?
