### ISSUE TITLE
Error while building gtk3

### ISSUE THREAD

**Issue by doadin** [wingtk/gvsbuild#1298]
"Program gtk4-update-icon-cache gtk-update-icon-cache found: NO
meson.build:49:24: ERROR: Program 'gtk4-update-icon-cache gtk-update-icon-cache' not found or not executable"

**Comment by doadin** [comment]
https://gitlab.gnome.org/GNOME/adwaita-icon-theme/-/commit/ae6966167b93c28abc4435a6904671ebba67b9b0 seems to add gtk3 as a requirment to meson.build

**Comment by danyeaw** [comment]
Hi @doadin, thanks for the issue report. Adwaita-icon-theme supports both gtk-update-icon-cache and gtk4-update-icon-cache, so it should still support GTK3.

What command are you using, what version of Gvsbuild do you have and how did you install it, and can you provide the larger portion of the build log where you got the failure? Thanks!

**Comment by doadin** [comment]
@danyeaw https://github.com/doadin/gvsbuild-release/blob/main/.github/workflows/release.yml is the workflow file so you can see the whole process. 
`      - name: Build
        run: >
          gvsbuild build
          --platform=${{ matrix.arch }}
          --vs-ver=${{ matrix.vstudio }}
          --enable-gi
          --py-wheel
          gtk3 pygobject lz4 enchant`

https://github.com/doadin/gvsbuild-release/actions/runs/8443289392/job/23126574349

that is the step used to run the build. Everything else seems to build fine other than pycairo, with the same messon issue with python I reported here like 6 months ago. I just reported the issue to them have not got a responce yet. ( I mention this because thats what the "# Delete unused python versions to avoid meson issue in cairo." is for in the workflow file. Thoughh this did not help that issue either. That being said one issue at a time.

**Comment by danyeaw** [comment]
Hi @doadin, I updated our official CI build to also build pygobject with GTK3 at https://github.com/wingtk/gvsbuild/pull/1299 and it builds fine. Some differences I noticed from our build:

1, Starting with Gvsbuild 2024.2.0, moving the Git bin folder out of the way is no longer required
2. We are passing the -j2 option, since we have seen GitHub Action runners run out of memory
3. We are using VS version 17, and not passing in the `--vs-ver`
4. We aren't getting the cairo meson errors causing you to have to delete other Python versions

**Comment by doadin** [comment]
ok, I am running a new build now to test I adjusted for 
# 1 
# 2
# 3 im assuming it defaults to vs17 if you dont specify --vs-ver?, for this test I only removed that arg
# 4 still have it deleting python for now as it should not hurt, as they should be unused anyways.

The only other difference I saw was use of poetry, I wouldnt think that should cause errors though?

**Comment by doadin** [comment]
@danyeaw ok that test did not get far, it errored :

"Run gvsbuild build --platform=x86 --ninja-opts -j2 --enable-gi --py-wheel gtk3 pygobject lz4 enchant
Build type is debug-optimized
Cleaning up the build environment
Checking msys tool
Using C:\msys64 for msys installation
Checking Msvc tool

Visual Studio installation(s) found:
    Visual Studio Enterprise 2019 @ C:\Program Files (x86)\Microsoft Visual 
Studio\20[19](https://github.com/doadin/gvsbuild-release/actions/runs/8461275508/job/23180803008#step:13:20)\Enterprise

Error: Unable to find Visual Studio, try using --vs-ver or --vs-install-path to
specify Visual Studio version or install location"

Visual Studio installation(s) found .....proceded by Unable to find Visual Studio, seems it can't mkae up its mind.

**Comment by doadin** [comment]
@danyeaw still same error after changing runner to windows-2022 to get vs 17.

https://github.com/doadin/gvsbuild-release/actions/runs/8461761735/workflow

x64 build works fine because it meson "finds" x86_64" but 32-bit build fails.

**Comment by doadin** [comment]
@danyeaw so, I was able to I guess workaround the issue by using the same method as other projects and specifying the meson python param, https://github.com/doadin/gvsbuild/commit/5e241a42a01aae0f3bfeb399e4def03d48b4a7ee 
after that commit
gvsbuild build --platform=x64 --ninja-opts -j2 --enable-gi --py-wheel gtk3 pygobject lz4 enchant is successful

I have not tested Adwaita-icon-theme yet.

**Comment by danyeaw** [comment]
Ok great, do you want to please submit a PR?

**Comment by doadin** [comment]
@danyeaw sure.

**Comment by doadin** [comment]
@danyeaw looks like gtk3 and 4 both built in the PR so no regression in adding this change even for your builds so thats nice!

**Comment by danyeaw** [comment]
Closed by #1301.
