### ISSUE TITLE
Link to binaries

### ISSUE THREAD

**Issue by pbor** [wingtk/gvsbuild#1319]
A little while ago, we added to the readme: "If you want to only run GTK on Windows and not build it yourself, you can download a zip file from the last release and unzip it to C:\gtk."

but there is no explanation or link to know where to get it from...

**Comment by danyeaw** [comment]
Hi @pbor, ya, good point. The artifacts are being built in CI and show as an artifact on the builds, but I think we are missing the step to upload them for a release. I'll work on this.
