### ISSUE TITLE
Include patch to fix pango font rendering

### ISSUE THREAD

**Issue by theCapypara** [wingtk/gvsbuild#1324]
It seems that Pango 1.51.1 introduced font rendering issues under Windows (took me a while to pin this down :) ):
https://gitlab.gnome.org/GNOME/pango/-/issues/767

For MSYS2 this issue was worked around via patch, disabling "dwrite":
https://github.com/msys2/MINGW-packages/pull/20385

Would you think it's possible to port this patch over? Thanks!

**Comment by pbor** [comment]
But are you sure we are affected and it is not msys specific? The comment from Fan in the upstream bug report says that he cannot reproduce when building with VS2019

**Comment by theCapypara** [comment]
I'm not fully certain. I have some weirdness with font rendering for a few months for one of my GTK3 apps, but its possible it's unrelated to this. I'll do some tests.
![grafik](https://github.com/wingtk/gvsbuild/assets/3512122/3bb20263-9dca-4dd1-8e7f-b04d9e9c2eb6)
![grafik](https://github.com/wingtk/gvsbuild/assets/3512122/8b5f47d6-0517-4912-978d-9c94d04ce182)

**Comment by theCapypara** [comment]
Here's the results:

I'm not 100% convinced the "normal" label text looks *much* better, but at least a bit? The GtkSource text looks 1000x times better though. I'll open a PR.
![grafik](https://github.com/wingtk/gvsbuild/assets/3512122/6b689394-e9b5-4e91-a653-c5644afc52ca)
![grafik](https://github.com/wingtk/gvsbuild/assets/3512122/bb5d2bc8-9aef-41d0-b41a-b2ad3a2e33ab)

**Comment by danyeaw** [comment]
I tried to test this as well, I didn't see any noticeable difference with normal fonts or with GtkSourceview with GTK4. I am not against merging the patch if it is helping you though.

In general, I think the fonts don't look great on Windows. I get `Pango-WARNING **: 10:03:29.777: couldn't load font "MyriadPro Not-Rotated 7.654", falling back to "Sans Not-Rotated 7.654", expect ugly output.` warnings with and without this patch.

**Comment by theCapypara** [comment]
Yeah, this might for some reason only affect GTK 3. I have another app using GTK 4 and didn't notice major font issues there before, but I also didn't check it with this patch yet and I don't use GtkSourceView there.

**Comment by theCapypara** [comment]
Hm.... #1328 fixed the GtkSourceView issue. However font quality overall is still poor without #1325.
It is better, but still not great. You can see yellow and blue artifacts.

Here is the same screenshots as above but just with the current master, #1328 included (but not my PR):

![grafik](https://github.com/wingtk/gvsbuild/assets/3512122/8bdc0591-0d4b-45e2-b76a-1c7179023c20)
![grafik](https://github.com/wingtk/gvsbuild/assets/3512122/30ff93c2-6924-4fb3-8e1d-433c9a20488e)
