### ISSUE TITLE
Rendering issues under Windows 10 and 11

### ISSUE THREAD

**Issue by theCapypara** [wingtk/gvsbuild#1405]
This is a follow-up to https://github.com/wingtk/gvsbuild/issues/1337

As I reported in that issue, I have really weird font rendering issues with gvsbuild under Windows 11. 
It seems to not just be isolated to font but also icons.
I was able to reproduce this by just running the Adwaita demo app in 2024.8.0:

![grafik](https://github.com/user-attachments/assets/4e58daf0-130a-49fd-ac90-f2f2b64b5bf4)
![grafik](https://github.com/user-attachments/assets/0cfadca1-867a-4155-9941-be3083cad9fe)
![grafik](https://github.com/user-attachments/assets/7d3f76e0-d629-4cb0-aa8d-aea98819a73e)
![grafik](https://github.com/user-attachments/assets/e9b1370b-15f6-439d-ac7b-20cfbbfbae34)

What's really strange is that I've tried to go through the timeline again and am now a bit confused. I originally submitted a PR to patch out pango dwrite support to fix font rendering in GTK 3 (#1325). While that did fix font issues in GTK 3 it *seemingly* caused the issues I observe here with GTK 4. However that PR was reverted (#1338) and now it's still looking like this? After I originally reverted the PR the users that originally had these font rendeirng issues seemingly didn't have them anymore, it's all so strange.
I was wondering, is it maybe #1328 that is causing this issue instead? In my original issue I just asumed it was my PR that broke rendering, but maybe it's that one, both were added at roughly the same time. I don't understand then why reverting my PR seemingly did fix it for a while. But at that time I was also not even able to really reproduce this on my own, so it's hard to say.

Of course it's also possible that neither of these PRs actually causes this...

I am also still not sure what actually needs to happen for this to occur. I can reproduce this on one of my Windows machines but not the others. The amount of corruption is also random with each launch.

**Comment by theCapypara** [comment]
Could it maybe be that *any* enabled direct write support, be it for harfbuzz, cairo or pango causes this?
I am pretty sure I had my users test with a version of my fork again which had NEITHER #1325 or #1328 in them...
I can give that a go...

**Comment by theCapypara** [comment]
Disabling direct write again does not fix this issue.

**Comment by theCapypara** [comment]
I should also add that I ran the demo app with windbg to see which DLLs are loaded. Only system DLLs and DLLs of the GTK ecosystem are loaded.

**Comment by theCapypara** [comment]
I was told people are also experience this under Windows 10, but I can't reproduce it myself on my Windows 10 test machine.

**Comment by jspast** [comment]
I am also facing the exact same issue on Windows 11, and it seems to happen in Gaphor (which uses gvsbuild) as well: gaphor/gaphor#3352

**Comment by danyeaw** [comment]
What type of video card do you have? I am only able to reproduce the icon corruption on newer AMD Ryzen laptop.

**Comment by theCapypara** [comment]
On the PC where I can reproduce it I have an AMD Radeon RX 7800 XT, on the two where I can *not* reproduce this I have Intel integrated graphics 13th Gen and Virtio graphics driver (KVM/QEMU VM)

I'll do a survey with my users to see what graphics cards they have.

**Comment by theCapypara** [comment]
Another user with an AMD Ryzen CPU with hybrid graphics using an NVIDIA mobile GPU also experiences this issue, this is their screenshot they shared:
![grafik](https://github.com/user-attachments/assets/1a5bd10c-223f-4002-8621-2ec75b43c7fa)

**Comment by theCapypara** [comment]
Another user reports they have a NVIDIA GeForce GTX 1650 on a desktop PC.

**Comment by danyeaw** [comment]
Ok, to try to isolate what is causing this, let's do an Is / Is-not analysis:

Text and Icon Corruption

| Category  | IS | IS NOT |
| ------------- | ------------- | ---------- |
| GPU | Nvidia, AMD  | Intel |
| Windows Version | 10 and 11 | |
| GTK Version  | GTK 4.14.4  | GTK 3.24.43? |
| Build System | Gvsbuild | MSYS2? |

Is that a good summary, and is there other things we should check?

**Comment by theCapypara** [comment]
That seems like a good summary. So far I had no reports of anybody using just Intel graphics to run into the issue.

I actually don't know if this issue happens with MSYS2. Last time I tested it didn't, but that's been quite a while ago.

**Comment by theCapypara** [comment]
I just tested it with MSYS2. I can not reproduce this issue, the fonts and icons look perfectly fine.

**Comment by theCapypara** [comment]
I asked on the MSYS2 Discord server, they pointed me to this patch they have: 
https://github.com/msys2/MINGW-packages/blob/365df49c1b798bb1bde02ac9986ae2edfb2c1088/mingw-w64-gtk4/PKGBUILD#L51C5-L52C51
https://github.com/msys2/MINGW-packages/blob/365df49c1b798bb1bde02ac9986ae2edfb2c1088/mingw-w64-gtk4/0001-ngl-icon-drawing-fix.patch

That seems promising! I won't have time to test it today or tomorrow (probably), I could give it a go after that.

**Comment by danyeaw** [comment]
@theCapypara I couldn't reproduce the issue in MSYS2 either. Good find and teamwork with the MSYS2 team, I am building GTK4 now with the patch to test it.

**Comment by danyeaw** [comment]
@theCapypara This does fix the issue for me, I submitted #1408.

**Comment by theCapypara** [comment]
Great! We might also want to pull in the other patch in another PR, it really seems to improve font rendering for small fonts.

**Comment by danyeaw** [comment]
I think that 2nd patch is already in the latest GTK stable.

**Comment by theCapypara** [comment]
Ah. I haven't tested applying it yet, so it's possible, I thought the MSYS2 Adwaita demo had slightly sharper fonts than the gvsbuild one. I guess I could actually compare them later, maybe it was just my imagination.

**Comment by TheSpartaPT** [comment]
issue seems to be back ?

while trying to make a GTK4 application i noticed the text was not being anti-aliased, tried messing around with `gtk-xft-antialias` and `gtk-xft-hinting` Settings and as far as i can tell nothing changes visually.

| Category |   |
|--------|--------|
| GPU | Nvidia |
| Windows Version | 11 |
| GTK Version | 4.16.3 |
| Build System | Gvsbuild@<https://github.com/wingtk/gvsbuild/commit/733de98be46c4021e62c71579eaaedd3c01aa418> | 

Examples:
![image](https://github.com/user-attachments/assets/1de9c16b-5844-4ca0-ab0e-ecea101c1889)
![image](https://github.com/user-attachments/assets/39d4b9d6-ad96-4707-8ae4-97161b1b93e4)

**Comment by danyeaw** [comment]
Please open a new issue rather than posting on one that has been closed for 2 months, thanks!
