### ISSUE TITLE
Missing packages fontconfig, pangoft2

### ISSUE THREAD

**Issue by manuvarkey** [wingtk/gvsbuild#1411]
It seems `pango` is build without `fontconfig`, `pangoft2`. Is it possible to build pango with support for these libraries ?

**Comment by manuvarkey** [comment]
I was using `gvs-build` to distribute an application using `weasyprint` which depends on `fontconfig` and `pangoft2`. Recently updated `gvs-build` to latest version and found that these libraries are not getting build.

**Comment by danyeaw** [comment]
Hi @manuvarkey, we removed fontconfig in #1279 to work around build failures we were seeing in Gtksourceview. I wasn't aware that apps on Windows were depending on it.

We could try to re-enable it and look for a different solution. However, GTK only requires PangoFT2 on X11 and Wayland, does this app need to depend on PangoFT2 on Windows?
