### ISSUE TITLE
release more binaries

### ISSUE THREAD

**Issue by DjLegolas** [wingtk/gvsbuild#1412]
currently, only GTK4 with python 3.12 are being released as binaries.

why don't include all supported variants?
this means, all python (`3.8`-`3.12`) and both `GTK3` and `GTK4`.

this will help users to add it more easily.
in projects that require only some of the packages, the maintainer will compile it for the specific needs.

**Comment by danyeaw** [comment]
Hi DjLegolas, I think releasing GTK3 binaries is a possibility. For supporting different Python versions, we really need to work upstream with PyGObject and pycairo to build and release wheels with the Gvsbuild DLLs dynamically linked. Ideally, we shouldn't be providing any wheels ourselves.

Does Deluge have any plans to update to GTK4?

**Comment by DjLegolas** [comment]
TBH, I was planning to migrate `Deluge` to GTK4, but it turns out `twisted` has an issue with GTK on Windows.
It effects both GTK3 and GTK4, so we had to remove the possibility to upgrade `twisted` to newer versions.

https://github.com/twisted/twisted/issues/11987

Regarding the releases, I agree that upstream should be responsible for that, but, and correct me if I'm wrong, the upstream does not provide any binaries, neither the base GTK not for pyGObject.
This means that this repository is one of the only please where one can find binaries for Windows.
Also, I think that one of the usages for this is for other projects to be able to use the binaries for internal testing.
This is exactly the reason why `twisted` is now not usable on Windows with GTK support.

**Comment by danyeaw** [comment]
Hi @DjLegolas, binaries of GTK won't be provided upstream for Windows - that's definitely Gvsbuild. However, binaries in the Wheel format of PyGObject and pycairo that don't require any `os.add_dll_directory` call or other work arounds should be provided by those projects in my view. I'm a maintainer of PyGObject so I'll be pushing for this.

**Comment by glyph** [comment]
> so we had to remove the possibility to upgrade `twisted` to newer versions

We would really like to support your use-case here, so please don't count Twisted out fully.  If we really can't make GTK work with sockets like it's supposed to on Windows, we can reinstate the old hack of the "portable" GTK reactor, as long as we can get it passing tests in CI.

**Comment by DjLegolas** [comment]
@glyph we did it only as a temporary solution only for Windows.
As I don't know when it will be fixed, we had to do it as we are installing the latest version of `twisted` on our CI each time.

The main reason I opened this discussion is the issue with `twisted` and the missing of `GTK` binaries for Windows for CI.
This way, one will always have a latest version available much more easily (even if a complete package might be an overkill).

**Comment by glyph** [comment]
Thanks, I figured it was something like that (and thank you for taking care to pin only on Windows!); mainly I just wanted to proactively reach out once I noticed this issue.  Having more of these binaries available would definitely make life easier, particularly if (as @danyeaw implies?) we can get `pip install`-able PyGTK binary wheels in the same way e.g. wxpython and pyqt work out of the box.
