### ISSUE TITLE
glib: turn off debug

### ISSUE THREAD

**Issue by pbor** [wingtk/gvsbuild#1419]
See https://gitlab.gnome.org/GNOME/glib/-/issues/3421#note_2206315

**Comment by DjLegolas** [comment]
I can add the relevant flag into the project, but this can be done in 2 ways:
1. just add it statically and always have turned off
2. use the `--configuration=debug` option parameter and configure it dynamically

@danyeaw what do you think?

**Comment by danyeaw** [comment]
I like how you used the --configuration parameter!

**Comment by danyeaw** [comment]
Closed by #1422. Thanks @pbor and @DjLegolas!
