### ISSUE TITLE
Build glib-openssl with meson

### ISSUE THREAD

**Issue by nacho** [wingtk/gvsbuild#142]
I just pushed an initial version of the meson support for meson, if needed we will need to make some fixes upstream.

**Comment by nacho** [comment]
I was checking this a bit today, I think we need to first provide PC files for Openssl and then meson should be able to find it easily.

**Comment by TingPing** [comment]
You can hardcode library checks for windows too, but provding a pkgconfig file is convient for other linuxy projects.

**Comment by guruDanny67** [comment]
Added the .pc pkg-config for openssl

**Comment by guruDanny67** [comment]
I try to build glib-openssl with meson, using the 2.50.3 version from the gnome ftp site.

Seems that the mesonscript/ dir is missing (is present if you got the .tar.gz release file from the github site).

I've got an error (from meso) when I try to pass the certitifcate file for windows: I'll investigate, maybe it's only a matter of updating meson

**Comment by nacho** [comment]
Let me know if u find any issue since I am the maintainer

**Comment by guruDanny67** [comment]
Apart from what is in the PR request I tried to run the tests and, for all, I've got an error:

(connection.exe:10084): GLib-GObject-WARNING **: Two different plugins tried to register 'GTlsBackendOpenssl'.

It would be nice if at the end of the build we can run the test to ensure that the build is ok :)

**Comment by nacho** [comment]
Did you manage to figure out the issue with the test?

**Comment by guruDanny67** [comment]
No, and I didn't try :(

I've got almost no idea on how openssl works so I'm not the best man for the job. I see if I can find something.

**Comment by nacho** [comment]
I released and update glib-openssl to 2.50.4 so now we don't have to keep the copy of the files.

**Comment by nacho** [comment]
I think this is all now fixed.
