### ISSUE TITLE
Specify MSVC runtime used

### ISSUE THREAD

**Issue by alex-tee** [wingtk/gvsbuild#1442]
Hi, as you may know, it's illegal to distribute a GPL-based application that uses the windows MSVC runtime statically linked in (and also illegal to distribute the runtime lib DLLs). Does gvsbuild use `/MD` to link to the dynamic runtime libs? Is this configurable?

**Comment by danyeaw** [comment]
Hi @alex-tee, I'm linking to the applicable portion of the GPL FAQ:
https://www.gnu.org/licenses/gpl-faq.html#WindowsRuntimeAndGPL

I don't think we are statically compiling against the Windows runtime. You would want to package your app without the Windows Runtime DLLs:
https://learn.microsoft.com/en-us/cpp/windows/deploying-visual-cpp-application-by-using-the-vcpp-redistributable-package?view=msvc-170

I think Gvsbuild would allow for this.

**Comment by alex-tee** [comment]
I see, looks good then. Thanks!
