### ISSUE TITLE
Cannot load in (Microsoft Store version of) Python

### ISSUE THREAD

**Issue by gan-lin** [wingtk/gvsbuild#1447]
I'm new to PyGTK and met the following problem:
> ** (process:xxxx): WARNING **: xx:xx:xx.xxx: Failed to load shared library 'gio-2.0-0.dll' referenced by the typelib: 'gio-2.0-0.dll': The specified module could not be found.

I'm using the prebuilt binaries from `releases`. I've installed `pygobject` and `pycairo` in a venv and added the binaries directory to PATH.
I'm sure I followed the steps in README, and have read <https://gitlab.gnome.org/GNOME/pygobject/-/issues/545>. I've checked the dependency dlls of `gio-2.0-0.dll` and found no missing.
- GTK version: GTK4_Gvsbuild_2024.9.0_x64 (recent from `releases`)
- Python version: 3.12.6 amd64
- System version: Windows 11 22631.4169

------------

Sorry but I found the problem. Previously I used the Microsoft Store version of Python. `_gi.cp312-win_amd64.pyd` depends on `python312.dll` which is missing in the this Python version. There's no problem on the official Python version.
So is it necessary to keep this issue? And is it necessary to consider about the Microsoft Store Python? Another problem is the error message is not relative to the actual problem.

**Comment by danyeaw** [comment]
Hi @gan-lin, thanks for the issue report and sorry you were having issues. I have found the official installers from python.org to be the most reliable for Windows. If the Microsoft Store version is missing DLLs, I'm not sure what to do about that, except maybe make the README more explicit to not use that version.

**Comment by danyeaw** [comment]
Going ahead and closing this since we can't change the Microsoft Store Python.

**Comment by gan-lin** [comment]
Sorry. I made a mistake: `python312.dll` actually **exists** in the Microsoft Store version of Python. The bug exists, but I'm not sure about the reason, it may relate to the difference of dll search path of the official Python and the Microsoft store Python. These links may be related:<https://github.com/numpy/numpy/issues/12667> <https://github.com/python/cpython/issues/79869>
