### ISSUE TITLE
Provide prebuilt releases

### ISSUE THREAD

**Issue by selaux** [wingtk/gvsbuild#145]
Having prebuilt releases for each gtk version would be cool. Those could be built via appveyor. What do you think?

**Comment by nacho** [comment]
Can u explain a bit more your use case? Btw having everything built with appveyor sounds good to me. Not sure about releases here though since this is not about grk only anymore, and what you can consider as part of a gtk release is very ambiguous.

**Comment by selaux** [comment]
Well the use case would basically be to reduce the CI cycle time of a project. E.g. We have [a project](https://github.com/ja2-stracciatella/ja2-stracciatella) for which we might want to use gtk. But this would currently either mean:

- Integrate gtk build into the applications build, which would probably double CI cycle time
- Checkin a prebuilt version, where we would need docs how to build it if a new version comes out and where people basically need to trust the "creator" of this lib

If we would have releases here they would basically be more "trustworthy" and updates would be easier. Imho this would lower the entry barrier into writing cross-platform applications in gtk as well, as I dont have to figure out how to build it in windows first, but can just download a prebuilt version and link that (as it is with other libraries as SDL). In terms of what Is gtk there could be multiple built versions:

- Minimal (which would only contain gtk and its absolutely needed dependencies)
- Normal (which would contain everything)

**Comment by selaux** [comment]
BTW: I would take on the appveyor built and pose a PR.

**Comment by TingPing** [comment]
This would be great as an answer to the never ending question "Where can I download Gtk" new devs have too.

**Comment by nacho** [comment]
In general the idea looks pretty good to me, we just need to understand which packages would go on "minimal" but we can add for now gtk, glib-openssl, libsoup and adwaita-icon-theme with all the deps and then we can see if we need more

**Comment by TingPing** [comment]
I Imagine outside of `ffmpeg` most of the libs are not terribly large? `adwaita-icon-theme` is probably the bulk of the size.

**Comment by guruDanny67** [comment]
We should keep some of them separated: I looked at my src folder and I have two tarball of adwaita-icon-theme (3.22.0 and 3.24.0) but six for gtk 3.22.xx, so while we upgrade Gtk+ say every month to fix things the adwaita-icon-theme is update only twice a year and in this way we can limit the sizes of the download: after the first big install one downloads and upgrades only the gtk3 packages.

And for the extra packages (say librsvg, gtksourceview3, emeus, graphene, ...) It will be really cool if we can have separate downloads so one can get what is really needed.

This is a packaging / installation task, really useful to have a better adoption and test of Gtk on windows (actually the doc says to go via the msys2 route, ok if you're used to gcc and similar, a little bit difficult if one is used to visual studio) but not so easy and trivial.

Another thing to consider is which vs version we would support: if we go for the full route at the end we should have packages for Vs2013, Vs2015, (sooner also for Vs2017) and for each compiler 32 and 64 bit version, with and without debug.

**Comment by lazka** [comment]
As of a1bc6c5d0 the appveyor build now contains a tarball of the install directory as build artifacts.
That doesn't address most of the use cases mentioned here, but it's a start. I don't plan to extend it any further myself.

**Comment by TingPing** [comment]
I also am hosting bundles with hexchat's deps: https://dl.hexchat.net/gtk/

I may extend this appveyor to include what we need but that is still a bit of work.

**Comment by intity** [comment]
This is a very good idea, and very much in demand for novice developers. I think it would be good to define a standard directory as the base infrastructure of the GTK+ stack to provide support for user applications targeting the windows platform.

**Comment by TingPing** [comment]
@demberto I would start with:

- Some CI routine that builds all packges
- Uploads an archive of all build outputs as a `.7z` archive

That alone would be extremely valuable to everybody. Breaking it up into smaller packages is trivial and can be done later.

**Comment by danyeaw** [comment]
@demberto, I did work on this. I created installers for the major GTK related packages in #466. It sounds like if we want to work on this more we need to create a new repository that builds GTK with gvsbuild and then packages up all the installers and releases them.

**Comment by danyeaw** [comment]
Would you like to make a PR? We always appreciate contributions!

When I was trying to speed up our build, I spent quite a lot of time trying to put all the built files into an archive to be used by other build steps. My tests had archiving this on CI taking about as long as the build itself. This included much more than just the built binaries and libs, and maybe we'll find a good solution, but this may not be as easy as just zipping up some files.

**Comment by stephanlachnit** [comment]
Would it also be possible to bundle all libraries in a wheel and upload them to PyPI directly? That would make it extremely easy to use for Python users. The package name could be something like `PyGObject-Windows`.

**Comment by TingPing** [comment]
@stephanlachnit I'm not super familiar with wheels but I doubt it. The whole stack (GLib, GTK) expect a specific layout of files on the system. Also most of the stack doesn't support static linking if that's required.
