### ISSUE TITLE
Rename project

### ISSUE THREAD

**Issue by nacho** [wingtk/gvsbuild#146]
This is not really a fork anymore the script has been rewritten completely in python, moreover, renaming it would give us more visibility when doing searchs about it on google.

**Comment by guruDanny67** [comment]
I'm obviously fine with this (some tough about the name?) but we should split the script in some pieces, say:
 * Base module, with the base classes (Project, Builder, utility functions)
 * Tool module, where we add all the tools needed
 * Gtk builder, with all the projects related to Gtk2/Gtk3/Gtk4
 * Video builder, say for ffmpeg, h264, ...
 * Archive builder
 * ---

We can automatically load the various script from a plugin directory where we put 'build-gtk.py', 'build-video.py', 'build-misc.py' and so on.

Thinking about #145 it will be good to have also builders for different version of the Gtk stack, if we look at the Gtk3 version having a 'build-gtk3-20.py', 'build-gtk3-22.py' can be ok (to use it on the new Gtk4 line, the gtk3 should never have a 3.24.xxx if I'm not wrong).

But I don't know if at the end the work is too much and the gain too little :(

**Comment by nacho** [comment]
Yeah, at some point I thought about making branches, but a branch of gtk 3.20 should still get updates for other packages....
Maybe the right approach is to follow something similar to jhbuild and have xml deifnitions or separate modules as you say

**Comment by nacho** [comment]
About your comment, I would say that we should start by splitting out the base module

**Comment by nacho** [comment]
So if everybody agrees I will rename it to gvsbuild

**Comment by guruDanny67** [comment]
I agree, even if I don't know what gvsbuild means :) 

Gtk Visual Studio Build ? 
Generic Visual Studio Build ? 
Greatest Visual Studio Build ? 

Tomorrow if I have a little bit of time I try to see what means splitting the source. For the different release if we have a module for gtk (say build-gtk.py) I would simply copy it as build-gtk-3_22.py so, loading it, we can build old releases but I think that using external configuration it's, actually, overkill: what I like in this project is that is, actually, manageable.

**Comment by guruDanny67** [comment]
I agree, even if I don't know what gvsbuild means :) 

Gtk Visual Studio Build ? 
Generic Visual Studio Build ? 
Greatest Visual Studio Build ? 

Tomorrow if I have a little bit of time I try to see what means splitting the source. For the different release if we have a module for gtk (say build-gtk.py) I would simply copy it as build-gtk-3_22.py so, loading it, we can build old releases but I think that using external configuration it's, actually, overkill: what I like in this project is that is, actually, manageable.

**Comment by nacho** [comment]
yeah, let's go simple for now

**Comment by nacho** [comment]
Done, feel free to open another issue about the split
