### ISSUE TITLE
How to build gtk3 with gtkmm3 ?

### ISSUE THREAD

**Issue by crades** [wingtk/gvsbuild#1488]
I use gtk3 & gtkmm3 to develop application in ubuntu，I want build gtkmm3 in windows use visual studio 2022.
How should I do，need your help, thanks

**Comment by crades** [comment]
I read gtkmm.py file, this is gtkmm 4.16 only used gtk4.
In gitlab gnome website，https://gitlab.gnome.org/GNOME/glibmm.git
gtkmm 3.24 dep ( in subprojects dir)

- atkmm-2-28
- cairomm-1-14
- gdk-pixbuf
- glibmm-2-66
- gtk-3-24
- libepoxy
- pangomm-2-46

how i build gtk3.24 with gtkmm3.24 use gvsbuild, thanks

**Comment by danyeaw** [comment]
Hi @crades, thanks for the feature request! Would you be interested in adding gtkmm3 to the gtkmm module as a pull request?

**Comment by crades** [comment]
Ok, I will try it

**Comment by danyeaw** [comment]
Ok, please let us know if you run into any issues, glad to help!

**Comment by crades** [comment]
In the past two days, i build gtkmm3 successfully, but have some issues

1.

**Comment by danyeaw** [comment]
Hi @crades, it looks like you are making great progress!

1. Gtkmm4 should not depend on Atk at all. Atk is a legacy system for accessibility and the new system was integrated in to GTK itself. I think you should only need Atkmm for Gtkmm3.
2. Could you push your changes to a branch of your fork and open a draft pull request? I can then try to reproduce the errors you are getting.

Thanks!

**Comment by crades** [comment]
Hi @danyeaw , i open a draft pull request #1493 , please try to reproduce the errors and review

Thanks!
