### ISSUE TITLE
Using Pygobject with separately built gstreamer

### ISSUE THREAD

**Issue by ben-xD** [wingtk/gvsbuild#1494]
Thanks for making this repo. This is the closest I've been to getting my project working on windows, natively without MSYS2 or Docker! It's super easy to build gstreamer, pygobject, pycairo etc. **So much** smoother than the gstreamer repo.

However, I already have gstreamer built using meson separately from gvsbuild, which has my code changes and some extra plugins enabled.

I'm running the commands in powershell 7 in admin mode:
```powershell
# Build to C:\gtk-build\gtk\x64\release
gvsbuild build gtk4 pygobject pycairo --enable-gi --py-wheel

# Create venv
py -3.13 -m venv .venv

# Activate env
.\.venv\Scripts\activate

# Install python wheels
uv pip install --force-reinstall (Resolve-Path C:\gtk-build\build\x64\release\pygobject\dist\PyGObject*.whl)
uv pip install --force-reinstall (Resolve-Path C:\gtk-build\build\x64\release\pycairo\dist\pycairo*.whl)

# confirm pip uses both of these by reading output of
py -3.13 -m pip freeze

# Execute the file below
py -3.13 .\main.py
```

Unfortunately my test script crashes with no exception or error message on `from gi.repository import Gst`. This only happens when using gstreamer that I build. This gstreamer works when I play videos etc (e.g. `.\gst-launch-1.0 ...` in `C:\gstreamer-python/bin`. This problem doesn't exist if I include `gstreamer` in the `gvsbuild build` command.

### `main.py`

```python
from pathlib import Path
import sys
import os

gtk_dir = Path(r"C:\gtk-build\gtk\x64\release")
gtk_bin_dir = str(gtk_dir / 'bin')
os.add_dll_directory(gtk_bin_dir)

# This line below causes the crash later on
os.environ["PATH"] =  r"C:\gstreamer-python\bin" + ";" + os.environ["PATH"]

from gi.repository import Gst  # 👈🏼️ `py -3.13 .\main.py` just crashes on this line if I use add the gst_bin_dir to PATH.
# $LASTEXITCODE in powershell is -1073741819
```

## Extra: My working gstreamer command

```
PS C:\gstreamer-python\bin> .\gst-launch-1.0.exe udpsrc uri=udp://127.0.0.1:11024 ! `
>>     application/x-rtp,media=video,encoding-name=MP2T,clock-rate=90000,payload=33 ! `
>>     rtpmp2tdepay ! queue ! tsdemux ! queue ! `
>>     h265parse ! avdec_h265 ! queue ! videoconvert ! queue ! `
>>     autovideosink sync=false
Use Windows high-resolution clock, precision: 1 ms
Setting pipeline to PAUSED ...
Pipeline is live and does not need PREROLL ...
Got context from element 'autovideosink0': gst.d3d11.device.handle=context, device=(GstD3D11Device)"\(GstD3D11Device\)\ d3d11device3", adapter=(uint)0, adapter-luid=(gint64)0, device-id=(uint)1, vendor-id=(uint)2, hardware=(boolean)true, description=(string)"Intel\(R\)\ Iris\(R\)\ Xe\ Graphics";
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock
Redistribute latency...
Redistribute latency...
0:00:53.0 / 99:99:99.
```

**Comment by ben-xD** [comment]
As an alternative, I'm applying a patch in https://github.com/wingtk/gvsbuild/blob/main/gvsbuild/projects/gstreamer.py#L164-L166

**Comment by danyeaw** [comment]
Hi @ben-xD, yes, adding a patch is a great way to go. Did you originally build GStreamer using MSVC?

**Comment by ben-xD** [comment]
Hey @danyeaw, yes I originally followed https://fluendo.com/blog/gstreamer-python-bindings-for-windows/, which includes cloning the gstreamer repo and running commands in powershell, etc.:
```
meson setup build -Dintrospection=enabled --prefix c:/gstreamer-python # i added more build options here to customize
meson compile -C .\build
meson install -C .\build
```

I assume this uses MSVC but it's not very explicit. I don't use the MinGW shell and i don't think it uses a linux environment. I can't see any trace of MSYS2 either.

Doesn't gvsbuild also use MSVC?

**Comment by danyeaw** [comment]
Yes it does

**Comment by danyeaw** [comment]
Hi @ben-xD, incompatibility between GStreamer built outside Gvsbuild and libraries built with Gvsbuild is out of scope of this project. A couple of options:

1. If the options you are passing or patches you are applying to build GStreamer would be useful for others, then we would be glad to have them added to Gvsbuild
2. You can continue to work on your own local version of Gvsbuild
3. We can get #1423 merged which allows users to apply more options to Meson projects via the command line

**Comment by ben-xD** [comment]
Thanks. My changes are not super relevant for others because it's just a potential bug fix which I've already opened in a PR to gstreamer. I've been doing 2 with local patch files, 3 also seems interesting.

I'll go along with building gstreamer and webrtcbin with gvsbuild, thanks! https://github.com/wingtk/gvsbuild/issues/1496

**Comment by danyeaw** [comment]
Hi @ben-xD, ok sounds great. Are we ready to close this issue?
