### ISSUE TITLE
Build is missing webrtc plugin (`gstwebrtc.dll` or `webrtcbin` element)

### ISSUE THREAD

**Issue by ben-xD** [wingtk/gvsbuild#1496]
Even though gvsbuild builds gst-plugins-bad [which includes `webrtcbin`](https://gstreamer.freedesktop.org/documentation/webrtc/index.html?gi-language=c), the actual webrtc plugin is not built. I only see `gstwebrtc-1.0-0.dll` which is a "webrtc helper library", but does not contain the plugin, `webrtc.dll`.

https://github.com/ben-xD/gvsbuild/blob/b849b7cd356944850c46d22d64c7b438f2f2b410/gvsbuild/projects/gstreamer.py#L147-L185

I've noticed no references/dependency on libnice, which is a dependency of webrtc:
https://gitlab.freedesktop.org/gstreamer/gstreamer/-/blob/main/subprojects/gst-plugins-bad/gst-libs/gst/webrtc/meson.build#L106

 https://gitlab.freedesktop.org/gstreamer/gstreamer/-/blob/main/subprojects/gst-plugins-bad/gst-libs/gst/webrtc/nice/meson.build

How could we build webrtcbin as part of the build? This would be an extension on https://github.com/wingtk/gvsbuild/pull/1389, which only builds `gstwebrtcdsp`.

This would allow us to use gstreamer for webrtc on windows too

Thanks for reading

**Comment by danyeaw** [comment]
Hi @ben-xD, adding libnice as a project was straightforward since it uses Meson for the build system. I opened #1509 which results in `C:\gtk-build\gtk\x64\release\lib\gstreamer-1.0\gstwebrtc.dll` being built

**Comment by ben-xD** [comment]
That's amazing, thanks!
