### ISSUE TITLE
Use ninja on cmake projects

### ISSUE THREAD

**Issue by nacho** [wingtk/gvsbuild#155]
Currently we use nmake for the cmake projects, instead we could use ninja which should be faster.

**Comment by guruDanny67** [comment]
Start with libssh2.

With cmake & nmake the times to rebuild from scratch, build after deleting all the object file and launch the build on an already builded and up to date source takes 50, 30 and 7 seconds.

With ninja the times goes to 21, 7 and 2: on my PC the creation of the definition file takes 12/13 seconds in both cases than for the other parts ninja is a little bit faster.

The test are made with a 4 cores/8 threads intel processor on as SSD disk: are not meant to be exaustive but simply give an idea of the improvement: bigger projects problably gain more, little gain less.

**Comment by nacho** [comment]
Very nice results!

**Comment by guruDanny67** [comment]
I should have converted all the project: the one that are using cmake are: libarchive libcurl libjpeg-turbo libpng libssh2 libyuv libzip portaudio protobuf protobuf-c win-iconv 

Rebuilding all this library (--no-deps --clean) without ninja takes 1047 seconds, a second build (dropping --clean) take 309 seconds.

Using ninja a complete rebuild takes 450 seconds and the second build 83 seconds (the git project got the regeneration of the ninja/nmake files that takes a lot of time).

Apart from the results now all the projects uses the CmakeProject class so if we decide, for example, to make the build out of source like we do with meson we need to change only one places.

I think the issue can be closes :)

**Comment by guruDanny67** [comment]
Modiified the script to build the cmake project out of source (in a dir like libpng-cmake, like we do for meson): the time to rebuild the libraries (the second time) is now less then 15 seconds and the source and the build file are separated.

**Comment by nacho** [comment]
Awesome!
