### ISSUE TITLE
Report download progress

### ISSUE THREAD

**Issue by nacho** [wingtk/gvsbuild#156]
See https://github.com/wingtk/gvsbuild/pull/154 for ref

**Comment by nacho** [comment]
Since you are at it feeling like fixing the certificate problem as well? :)

**Comment by guruDanny67** [comment]
I take a (fast) look but it's not seems so easy: AFAIK using urllib.request.urlretrieve() there is non chance to setup the certification chain: probably there is the need to use the urllib package with better options/ function.

I take a look and see if I can found something.

**Comment by guruDanny67** [comment]
I'll take a deeper look at the question and I made some test but I don't have any error downloading from sourceforge ...

Any idea of the way to get the error (so we can see if the modification are good) without changing all the certificates / permission, I don't know very well how it works and I don't would have an unstable system :)

Thanks

**Comment by nacho** [comment]
Adding @muntyan here
