### ISSUE TITLE
Donwload automatically needed msys packages

### ISSUE THREAD

**Issue by guruDanny67** [wingtk/gvsbuild#162]
I'm taking a look at the Appveyor integration and the setup script use directly pacman from msys to install needed packages, with 
```bash
c:\msys64\usr\bin\pacman --noconfirm -S nasm patch pkg-config
```

We can automatize the download of the packages, checking the presence of the package looking for one exe file (make.exe for make, patch.exe for patch, msgfmt for textutils, ...) so the user must only installa msys2 and update it the first time as stated in the (msys2) homepage.

**Comment by nacho** [comment]
I wonder some things here:
 - can we build nasm ourselves? the upstream projects seems to provide nmake scripts for that.
 - do we still need pkg-config from msys2 or can we use the one we build?
 - do we still need gettext from msys2 or can we use our one?

**Comment by guruDanny67** [comment]
For pkg-config I think our (the builded one) is already used, directory by meson (having put the gtk stack bin dir in the path).

For gettext it was used by gtk/gtk3 to update the mo files and now the script use directly our.

For the project that uses in their script the gettext program should be the same situation as with pkg-config: the files are in the path so there are found.

For nasm the package is downloaded and installed in the tools.
