### ISSUE TITLE
Use Meson to build ATK

### ISSUE THREAD

**Issue by ebassi** [wingtk/gvsbuild#171]
[Meson](http://mesonbuild.com) support landed in ATK's master branch.

**Comment by nacho** [comment]
Filed https://github.com/mesonbuild/meson/issues/1860
For now we could just keep a downstream patch removing the gir generation.

**Comment by nacho** [comment]
ATK should be ready to be built, we just need a new release from ATK. @infapi00 any chance to get a new one?

**Comment by infapi00** [comment]
Ups, seems that I forgot that this Monday was scheduled 3.27.1. I usually follow GNOME schedule, and do new releases if there is new stuff to add. Sorry for that.

I will try to do the release today

**Comment by infapi00** [comment]
Just released:
https://download.gnome.org/sources/atk/2.27/atk-2.27.1.tar.xz 

I think that it is too late for gnome 3.27.1 release in any case. Just added a comment on #release-team channel in any case.

**Comment by nacho** [comment]
@infapi00 no chance that you can actually make a 2.26.1?

**Comment by infapi00** [comment]
All the commits were safe enough:
https://download.gnome.org/sources/atk/2.26/atk-2.26.1.tar.xz

**Comment by nacho** [comment]
@infapi00 thanks!
