### ISSUE TITLE
Use Meson to build libgxps

### ISSUE THREAD

**Issue by nacho** [wingtk/gvsbuild#179]
Now that libgxps has been released we can definitely switch to meson with it.

**Comment by guruDanny67** [comment]
I made a couple of test and there is some problem: using meson the library / dependencies are forund using pkg-config so the first step is to put the .pc config file for each library used (freetype, libjepg) and be sure that the one present are correct (libarchive.pc uses wrong parameter for the lib to link so meson generate an error).

So the first step is to add the pkg-config file to all the dependencies of libgxps (or to all the projects we build ...) and the second one is check that they are correct.

I'm building a simple meson project to test this (foe each library I print simply the address of one symbol from the library itself) and see if using each library from the outside (not from the internal test) works.

**Comment by guruDanny67** [comment]
Done, after fixing some of the .pc files that were missing.

I had to put a small patch to let the script ignore the m library: in the old meson version on windows the check for the library was always ok but meson create, when linking, the commands without it so it work, even if in the doc clearly states that you need to NOT require the m lib.

I see if I can open a ticket / bug report to libgxps.

**Comment by nacho** [comment]
I can push to libgxps the patch u tell me

**Comment by guruDanny67** [comment]
The one in the gvsbuild source: add 'required: false' to the m lib dependence:

# Maths functions might be implemented in libm
libm_dep = cc.find_library('m', required: false)

**Comment by nacho** [comment]
Pushed upstream, thanks!
