### ISSUE TITLE
Use meson to build gdk-pixbuf

### ISSUE THREAD

**Issue by nacho** [wingtk/gvsbuild#180]
Now that gdk-pixbuf is ported to meson we should try to use it. We should probably pass in -Dwith_gir=no

**Comment by nacho** [comment]
The last bit to build gdk-pixbuf with meson on windows was just pushed upstream. We should be ready once there is a new release to move forward.

**Comment by guruDanny67** [comment]
I made a couple of test with the master branch: I put a little change on libpng to let the program find the library (it looks for libpng16.pc instead of libpng.pc) and I made a pull request to add Jasper and everything seems ok.

As soon as the release is out we can switch.

**Comment by nacho** [comment]
With the new release out we should be able to go ahead with this right @guruDanny67 ?

**Comment by guruDanny67** [comment]
Yes, I'll take a look now!
