### ISSUE TITLE
Build libyuv

### ISSUE THREAD

**Issue by guruDanny67** [wingtk/gvsbuild#181]
I just push a commit that, with cmake and ninja, build the lòibyuv from google.

It uses a very old CMakeLists.txt file that I have to change (and put in our source tree) to make the compilation ends.

The static library and the conversion program (yuvconvert.exe) seems right but the dll is not installed in the right place (bin), gots some unresolved symbols (jpeg62) and seem that there is no exported symbols.

At first sight it can be that the CmakeList was build and tested under some linux environment and not on windows (for example the .exe extension for yuvconvert was missing in the install part and so it generate an error).

**Comment by nacho** [comment]
@guruDanny67 is this still an issue?

**Comment by nacho** [comment]
Enjoy!

**Comment by guruDanny67** [comment]
Update the project, linking with the jpeglib so to avoid the missing external.

There is probably something wrong in the dll/lib (the lib is the static one and the dll doesn't export anything) but for now I think is enough.
