### ISSUE TITLE
Using python 3.5/3.6

### ISSUE THREAD

**Issue by guruDanny67** [wingtk/gvsbuild#183]
I'm working on a little patch to create zip files of the various library build, to prepare for (a future) installation and to check exactly what's in any library and I'm using some function available only on python 3.5 + (namely, scandir()).

I can use a different approach (the old listdir() or os.walk()) but considering that python 3.4 is now in security fix mode (the 3.4.6 is the last binary release, the 3.4.7 is available only as a source download) what do you think of requiring directly a 3.6 python (minconda is also on 3.6) ?

On windows, where there is nothing like the system python as in the Red Hat distro, having a new or an old release is only a matter of downloading the right version, you don't break the system (and differents versions can be installed side by side).

Thanks.

**Comment by nacho** [comment]
I have no problem updating python.
