### ISSUE TITLE
build pygtk, pycairo, pygobject from git 

### ISSUE THREAD

**Issue by guruDanny67** [wingtk/gvsbuild#184]
These 3 projects uses Mercurial to get the source from github (muntyan repositories): there is a reason for not using directly git as we do in other places ?

Using git means we don't have to install also mercurial (b.t.w, we should mention on the readme that git is needed to build some projects, even if you shoud have it if you download the script ...)

**Comment by nacho** [comment]
I think there is no reason to use mercurial, we should definitely use the upstream projects
