### ISSUE TITLE
MSYS2 questions

### ISSUE THREAD

**Issue by lab313ru** [wingtk/gvsbuild#187]
So, if it compiles with Visual Studio, why the MSYS2 is used here?
Does it actually compile with cygwin-dependencies?

**Comment by nacho** [comment]
We use it for some utilities, see i.e https://github.com/wingtk/gvsbuild/blob/master/gvsbuild/utils/builder.py#L92

This way we do not have to ask the user to install several utilites manually but just to install one, msys2

**Comment by lab313ru** [comment]
Is it will be enough? http://unxutils.sourceforge.net/

**Comment by guruDanny67** [comment]
Some projects (ffmpeg & x264) uses a bash shell, with a .sh script to coordinate the build, using the classical configure from the linux system so it's not an easy task to remove the msys2 dependencies without dropping some projects.

At the beginning we use more tools from msys2 (yasm & nasm to name a few), now  we try to download, where possible, the native tools but is not always an easy task.

**Comment by nacho** [comment]
I hope the answers from @guruDanny67 helped you. I am closing this issue, feel free to open it if you have more questions.
