### ISSUE TITLE
Error building libpng

### ISSUE THREAD

**Issue by Adriatic1** [wingtk/gvsbuild#188]
Just tried to rebuild GTK3 stack using latest version of the project (i.e. "git pull").
It fails to build libpng with this error:

cmd.exe /C "cd . && C:\PROGRA~2\MINGW-~1\I686-4~1.2-P\mingw32\bin\gcc.exe   -O2 -g -DNDEBUG   -shared -o libpng16.dll -Wl,--out-implib,libpng16.dll.a -Wl,--major-image-version,16,--minor-image-version,28 CMakeFiles/png.dir/png.c.obj CMakeFiles/png.dir/pngerror.c.obj CMakeFiles/png.dir/pngget.c.obj CMakeFiles/png.dir/pngmem.c.obj CMakeFiles/png.dir/pngpread.c.obj CMakeFiles/png.dir/pngread.c.obj CMakeFiles/png.dir/pngrio.c.obj CMakeFiles/png.dir/pngrtran.c.obj CMakeFiles/png.dir/pngrutil.c.obj CMakeFiles/png.dir/pngset.c.obj CMakeFiles/png.dir/pngtrans.c.obj CMakeFiles/png.dir/pngwio.c.obj CMakeFiles/png.dir/pngwrite.c.obj CMakeFiles/png.dir/pngwtran.c.obj CMakeFiles/png.dir/pngwutil.c.obj  C:/gtk/lib/libz.dll.a -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && cd ."
CMakeFiles/png.dir/pngrutil.c.obj: In function `png_inflate_claim':
C:/gtk-build/build/Win32/release/libpng/pngrutil.c:425: undefined reference to `inflateValidate'
collect2.exe: error: ld returned 1 exit status
[22/51] Building C object CMakeFiles/png_static.dir/pngread.c.obj
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "c:\gtk-build\gvsbuild\gvsbuild\utils\builder.py", line 209, in build
    self.__build_one(p)
  File "c:\gtk-build\gvsbuild\gvsbuild\utils\builder.py", line 281, in __build_one
    proj.build()
  File "c:\gtk-build\gvsbuild\gvsbuild\projects.py", line 793, in build
    CmakeProject.build(self, use_ninja=True)
  File "c:\gtk-build\gvsbuild\gvsbuild\utils\base_builders.py", line 108, in build
    self.builder.exec_vs('ninja install', working_dir=work_dir)
  File "c:\gtk-build\gvsbuild\gvsbuild\utils\builder.py", line 493, in exec_vs
    self.__execute(self.__sub_vars(cmd), working_dir=working_dir, add_path=add_path, env=self.vs_env)
  File "c:\gtk-build\gvsbuild\gvsbuild\utils\builder.py", line 525, in __execute
    subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
  File "C:\Python\Python35\lib\subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'ninja install' returned non-zero exit status 1
Error: libpng build failed

Any advice here?

**Comment by Adriatic1** [comment]
BTW, command I used was:
python.exe .\build.py build gtksourceview3 gtk3 adwaita-icon-theme --msys-dir c:\msys32

**Comment by nacho** [comment]
Can you try to remove the c:\gtk-build\gtk and c:\gtk-build\build directories and try again?

**Comment by Adriatic1** [comment]
Removed those two directories, but it did not help.
Then I've reinstalled somewhat older mysys2 with latest 64-bit version. I also removed both src and tools folders.
New command was:
python build.py build gtksourceview3 gtk3 adwaita-icon-theme

Unfortunately, this fails now on gettext :-(

  grep.vcxproj -> C:\gtk-build\build\Win32\release\gettext\build\win32\vs12\Rel
  ease\Win32\bin\grep.lib
Traceback (most recent call last):
  File "c:\gtk-build\gvsbuild\gvsbuild\utils\builder.py", line 209, in build
    self.__build_one(p)
  File "c:\gtk-build\gvsbuild\gvsbuild\utils\builder.py", line 281, in __build_one
    proj.build()
  File "c:\gtk-build\gvsbuild\gvsbuild\projects.py", line 346, in build
    self.exec_msbuild(r'build\win32\vs%(vs_ver)s\gettext.sln')
  File "c:\gtk-build\gvsbuild\gvsbuild\utils\base_project.py", line 74, in exec_msbuild
    self.exec_vs('msbuild ' + cmd + ' /p:Configuration=' + configuration + ' %(msbuild_opts)s', add_path=add_path)
  File "c:\gtk-build\gvsbuild\gvsbuild\utils\base_project.py", line 69, in exec_vs
    self.builder.exec_vs(cmd, working_dir=self._get_working_dir(), add_path=add_path)
  File "c:\gtk-build\gvsbuild\gvsbuild\utils\builder.py", line 493, in exec_vs
    self.__execute(self.__sub_vars(cmd), working_dir=working_dir, add_path=add_path, env=self.vs_env)
  File "c:\gtk-build\gvsbuild\gvsbuild\utils\builder.py", line 525, in __execute
    subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
  File "C:\Python\Python35\lib\subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'msbuild build\win32\vs12\gettext.sln /p:Configuration=release /nologo /p:Platform=Win32 /p:PythonPath=C:\Python\Python35   /v:minimal' returned non-zero exit status 1
Error: gettext build failed

**Comment by Adriatic1** [comment]
Tried this:
c:\gtk-build>msbuild
'msbuild' is not recognized as an internal or external command,
operable program or batch file.

Do I need to set some path variable or add some parameter to build?

**Comment by nacho** [comment]
See that I think Python36 is now required, maybe that is the problem?

**Comment by Adriatic1** [comment]
Updated to new Python36, still no luck:
  grep.vcxproj -> C:\gtk-build\build\Win32\release\gettext\build\win32\vs12\Rel
  ease\Win32\bin\grep.lib
Traceback (most recent call last):
  File "c:\gtk-build\gvsbuild\gvsbuild\utils\builder.py", line 209, in build
    self.__build_one(p)
  File "c:\gtk-build\gvsbuild\gvsbuild\utils\builder.py", line 281, in __build_one
    proj.build()
  File "c:\gtk-build\gvsbuild\gvsbuild\projects.py", line 346, in build
    self.exec_msbuild(r'build\win32\vs%(vs_ver)s\gettext.sln')
  File "c:\gtk-build\gvsbuild\gvsbuild\utils\base_project.py", line 74, in exec_msbuild
    self.exec_vs('msbuild ' + cmd + ' /p:Configuration=' + configuration + ' %(msbuild_opts)s', add_path=add_path)
  File "c:\gtk-build\gvsbuild\gvsbuild\utils\base_project.py", line 69, in exec_vs
    self.builder.exec_vs(cmd, working_dir=self._get_working_dir(), add_path=add_path)
  File "c:\gtk-build\gvsbuild\gvsbuild\utils\builder.py", line 493, in exec_vs
    self.__execute(self.__sub_vars(cmd), working_dir=working_dir, add_path=add_path, env=self.vs_env)
  File "c:\gtk-build\gvsbuild\gvsbuild\utils\builder.py", line 525, in __execute
    subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
  File "C:\Python36\lib\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'msbuild build\win32\vs12\gettext.sln /p:Configuration=release /nologo /p:Platform=Win32 /p:PythonPath=C:\Python36   /v:minimal' returned non-zero exit status 1.
Error: gettext build failed

Then I tried to run this (i.e. specify the precise VS2003 install location):
c:\gtk-build\gvsbuild>python.exe build.py build gtksourceview3 gtk3 adwaita-icon-theme --vs-install-path "c:\Program Files (x86)\Microsoft Visual Studio 12.0\"

but got this error:
Traceback (most recent call last):
  File "build.py", line 37, in <module>
    args.func(args)
  File "c:\gtk-build\gvsbuild\gvsbuild\utils\parser.py", line 104, in do_build
    builder = Builder(opts)
  File "c:\gtk-build\gvsbuild\gvsbuild\utils\builder.py", line 58, in __init__
    self.__check_vs(opts)
  File "c:\gtk-build\gvsbuild\gvsbuild\utils\builder.py", line 152, in __check_vs
    raise Exception("'%s' could not be found. Please check you have Visual Studio installed at '%s' and that it supports the target platform '%s'." % (vcvars_bat, opts.vs_install_path, opts.platform))
Exception: 'c:\Program Files (x86)\Microsoft Visual Studio 12.0"\VC\Auxiliary\Build\vcvars32.bat' could not be found. Please check you have Visual Studio installed at 'c:\Program Files (x86)\Microsoft Visual Studio 12.0"' and that it supports the target platform 'Win32'.

Note that my "vcvars32.bat" for 32-bit builds is placed here:
c:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\vcvars32.bat 
i.e. there is no "Auxiliary\Build" folder.

I am using VS 2003 Community edition, could that be a problem?

**Comment by nacho** [comment]
https://github.com/wingtk/gvsbuild/blob/master/gvsbuild/utils/builder.py#L138

It seems to me like we are looking for vcvars32.bat in the correct place no?

**Comment by Adriatic1** [comment]
Code looks OK, but the exception string is strange:
Exception: 'c:\Program Files (x86)\Microsoft Visual Studio 12.0"\VC\Auxiliary\Build\vcvars32.bat' could not be found. 

It appears as if the command line parameter was not unquoted properly, see double quote after 12.0 part. Could that be a problem?

**Comment by nacho** [comment]
can you try printing vcvars_bat and see what is what you get there? I wonder why the check  if not os.path.exists(vcvars_bat): is true for you

**Comment by Adriatic1** [comment]
I actually added these two lines, one line before the one you point:
            print("Install path: " + opts.vs_install_path)
            opts.vs_install_path = opts.vs_install_path.replace('"', '')

Running now proceeds further:
c:\gtk-build\gvsbuild>python.exe build.py build gtksourceview3 gtk3 adwaita-icon-theme --vs-install-path "c:\Program Files (x86)\Microsoft Visual Studio 12.0\"
Building project perl
Building project cmake
Building project ninja
Building project win-iconv
-- Configuring done
-- Generating done
-- Build files have been written to: C:/gtk-build/build/Win32/release/win-iconv-cmake
ninja: no work to do.
[0/1] Running tests...
Test project C:/gtk-build/build/Win32/release/win-iconv-cmake
    Start 1: win_iconv_test
1/1 Test #1: win_iconv_test ...................   Passed    0.08 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) =   0.09 sec
[0/1] Install the project...
-- Install configuration: "RelWithDebInfo"
-- Installing: C:/gtk-build/build/Win32/release/win-iconv-rel/lib/libiconv.dll.a
-- Installing: C:/gtk-build/build/Win32/release/win-iconv-rel/bin/iconv.dll
-- Installing: C:/gtk-build/build/Win32/release/win-iconv-rel/bin/win_iconv.exe
-- Installing: C:/gtk-build/build/Win32/release/win-iconv-rel/include/iconv.h
Building project gettext
  grt.vcxproj -> C:\gtk-build\build\Win32\release\gettext\build\win32\vs12\Rele
  ase\Win32\bin\grt.lib
  asprintf.vcxproj -> C:\gtk-build\build\Win32\release\gettext\build\win32\vs12
  \Release\Win32\bin\asprintf.dll
LINK : fatal error LNK1181: cannot open input file 'iconv.lib' [C:\gtk-build\bu
ild\Win32\release\gettext\build\win32\vs12\intl.vcxproj]
  gnu.vcxproj -> C:\gtk-build\build\Win32\release\gettext\build\win32\vs12\Rele
  ase\Win32\bin\gnu.lib
  glib_rpl.vcxproj -> C:\gtk-build\build\Win32\release\gettext\build\win32\vs12
  \Release\Win32\bin\glib_rpl.lib
  libxml_rpl.vcxproj -> C:\gtk-build\build\Win32\release\gettext\build\win32\vs
  12\Release\Win32\bin\libxml_rpl.lib
  libcroco_rpl.vcxproj -> C:\gtk-build\build\Win32\release\gettext\build\win32\
  vs12\Release\Win32\bin\libcroco_rpl.lib
  grep.vcxproj -> C:\gtk-build\build\Win32\release\gettext\build\win32\vs12\Rel
  ease\Win32\bin\grep.lib
Traceback (most recent call last):
  File "c:\gtk-build\gvsbuild\gvsbuild\utils\builder.py", line 210, in build
    self.__build_one(p)
  File "c:\gtk-build\gvsbuild\gvsbuild\utils\builder.py", line 282, in __build_one
    proj.build()
  File "c:\gtk-build\gvsbuild\gvsbuild\projects.py", line 346, in build
    self.exec_msbuild(r'build\win32\vs%(vs_ver)s\gettext.sln')
  File "c:\gtk-build\gvsbuild\gvsbuild\utils\base_project.py", line 74, in exec_msbuild
    self.exec_vs('msbuild ' + cmd + ' /p:Configuration=' + configuration + ' %(msbuild_opts)s', add_path=add_path)
  File "c:\gtk-build\gvsbuild\gvsbuild\utils\base_project.py", line 69, in exec_vs
    self.builder.exec_vs(cmd, working_dir=self._get_working_dir(), add_path=add_path)
  File "c:\gtk-build\gvsbuild\gvsbuild\utils\builder.py", line 494, in exec_vs
    self.__execute(self.__sub_vars(cmd), working_dir=working_dir, add_path=add_path, env=self.vs_env)
  File "c:\gtk-build\gvsbuild\gvsbuild\utils\builder.py", line 526, in __execute
    subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
  File "C:\Python36\lib\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'msbuild build\win32\vs12\gettext.sln /p:Configuration=release /nologo /p:Platform=Win32 /p:PythonPath=C:\Python36   /v:minimal' returned non-zero exit status 1.
Error: gettext build failed

c:\gtk-build\gvsbuild>python.exe build.py build gtksourceview3 gtk3 adwaita-icon-theme --vs-install-path "c:\Program Files (x86)\Microsoft Visual Studio 12.0\"
Install path: c:\Program Files (x86)\Microsoft Visual Studio 12.0"
Building project perl
Building project cmake
Building project ninja
Building project win-iconv
-- Configuring done
-- Generating done
-- Build files have been written to: C:/gtk-build/build/Win32/release/win-iconv-cmake
ninja: no work to do.
[0/1] Running tests...
Test project C:/gtk-build/build/Win32/release/win-iconv-cmake
    Start 1: win_iconv_test
1/1 Test #1: win_iconv_test ...................   Passed    0.06 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) =   0.08 sec
[0/1] Install the project...
-- Install configuration: "RelWithDebInfo"
-- Installing: C:/gtk-build/build/Win32/release/win-iconv-rel/lib/libiconv.dll.a
-- Installing: C:/gtk-build/build/Win32/release/win-iconv-rel/bin/iconv.dll
-- Installing: C:/gtk-build/build/Win32/release/win-iconv-rel/bin/win_iconv.exe
-- Installing: C:/gtk-build/build/Win32/release/win-iconv-rel/include/iconv.h
Building project gettext
  grt.vcxproj -> C:\gtk-build\build\Win32\release\gettext\build\win32\vs12\Rele
  ase\Win32\bin\grt.lib
  asprintf.vcxproj -> C:\gtk-build\build\Win32\release\gettext\build\win32\vs12
  \Release\Win32\bin\asprintf.dll
LINK : fatal error LNK1181: cannot open input file 'iconv.lib' [C:\gtk-build\bu
ild\Win32\release\gettext\build\win32\vs12\intl.vcxproj]
  gnu.vcxproj -> C:\gtk-build\build\Win32\release\gettext\build\win32\vs12\Rele
  ase\Win32\bin\gnu.lib
  glib_rpl.vcxproj -> C:\gtk-build\build\Win32\release\gettext\build\win32\vs12
  \Release\Win32\bin\glib_rpl.lib
  libxml_rpl.vcxproj -> C:\gtk-build\build\Win32\release\gettext\build\win32\vs
  12\Release\Win32\bin\libxml_rpl.lib
  libcroco_rpl.vcxproj -> C:\gtk-build\build\Win32\release\gettext\build\win32\
  vs12\Release\Win32\bin\libcroco_rpl.lib
  grep.vcxproj -> C:\gtk-build\build\Win32\release\gettext\build\win32\vs12\Rel
  ease\Win32\bin\grep.lib
Traceback (most recent call last):
  File "c:\gtk-build\gvsbuild\gvsbuild\utils\builder.py", line 211, in build
    self.__build_one(p)
  File "c:\gtk-build\gvsbuild\gvsbuild\utils\builder.py", line 283, in __build_one
    proj.build()
  File "c:\gtk-build\gvsbuild\gvsbuild\projects.py", line 346, in build
    self.exec_msbuild(r'build\win32\vs%(vs_ver)s\gettext.sln')
  File "c:\gtk-build\gvsbuild\gvsbuild\utils\base_project.py", line 74, in exec_msbuild
    self.exec_vs('msbuild ' + cmd + ' /p:Configuration=' + configuration + ' %(msbuild_opts)s', add_path=add_path)
  File "c:\gtk-build\gvsbuild\gvsbuild\utils\base_project.py", line 69, in exec_vs
    self.builder.exec_vs(cmd, working_dir=self._get_working_dir(), add_path=add_path)
  File "c:\gtk-build\gvsbuild\gvsbuild\utils\builder.py", line 495, in exec_vs
    self.__execute(self.__sub_vars(cmd), working_dir=working_dir, add_path=add_path, env=self.vs_env)
  File "c:\gtk-build\gvsbuild\gvsbuild\utils\builder.py", line 527, in __execute
    subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
  File "C:\Python36\lib\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'msbuild build\win32\vs12\gettext.sln /p:Configuration=release /nologo /p:Platform=Win32 /p:PythonPath=C:\Python36   /v:minimal' returned non-zero exit status 1.
Error: gettext build failed

So it seems unquoting algorithm has issues (last quote was not stripped).
Additionally, when algorithm falls back to VS2017 version of the path, why that path was not checked for existence as well ?

**Comment by Adriatic1** [comment]
> Additionally, when algorithm falls back to VS2017 version of the path, why that path was not checked for existence as well ?
Sorry, ignore this part. I've just seen the code below the if block.

**Comment by guruDanny67** [comment]
Normally I got errors when I have some linux utility in my path and some
library are not the one just built but something in the path.

I've got a mk.bat that sets the minimum path (git, windows & nothing more)
and than launch the script: in this way I reduce a lot errors (on one Pc
everything was ok, on another, randomly, some library fails).

Il 06 set 2017 15:57, "Miroslav Rajčić" <notifications@github.com> ha
scritto:

**Comment by guruDanny67** [comment]
As a reference, my batch is:

```
set _SVPATH=%PATH%
set PATH=c:\windows;c:\windows\system32;C:\Program Files\Git\cmd;C:\Program Files (x86)\Windows Kits\8.1\bin\x86;c:\Windows\System32\WindowsPowerShell\v1.0

py -3 build.py %WINGTK_PRE% build --msys-dir c:\msys64 --vs-ver 14 --vs-install-path c:\dev\vs2015 --python-dir c:\dev\py35 %*

set PATH=%_SVPATH%
set _SVPATH=

```
with set WINGTK_PRE=-d I enable the debug, the other switch are for my setup (I don't like the standard installation paths ...)

**Comment by Adriatic1** [comment]
Thanks, will try this.

**Comment by Adriatic1** [comment]
Thanks guys, using the script similar to the one of Daniele did the trick.
So I guess it was the issue of something being in the PATH.
The only remaining bug I can see here is that when the --vs-install-path parameter is used with double quoted path (because the path contains the spaces), python code seems to strip the first quote, but not the closing one, so that doesn't work. That's why I have to rely on default studio path calculation.

My batch script in case someone is interested:
@ECHO OFF
set _SVPATH=%PATH%
set PATH=c:\windows;c:\windows\system32

set _SV_VSTUDIO_VER=12
set _SV_MSYS2_DIR=c:\msys64
set _SV_PYTHON_DIR=c:\python36
set _SV_PROJECTS=gtksourceview3 adwaita-icon-theme

PUSHD c:\gtk-build\gvsbuild\
py -3 build.py build %_SV_PROJECTS% --msys-dir %_SV_MSYS2_DIR% --vs-ver %_SV_VSTUDIO_VER% --python-dir %_SV_PYTHON_DIR%
POPD

set PATH=%_SVPATH%
set _SVPATH=
