### ISSUE TITLE
pycairo/pygobject build fails

### ISSUE THREAD

**Issue by tom2x2** [wingtk/gvsbuild#192]
The setup is up-to-date msys2, python 3.6 in C:\Python36, visual studio 14.  When trying to build with the following command line:

`python build.py build pycairo pygobject pango --msys-dir /e/Programs/msys64/ --vs-ver 14`

It fails with the error message below. Same thing happens when trying to build pycairo or pygobject alone. Setting --python-dir, PATH, PYTHONPATH etc. environment variables does not seem to affect it.

---

Building project pycairo
Cloning into '/c/gtk-build/build/Win32/release/pycairo-tmp'...
remote: Counting objects: 32, done.
Receiving objects: remote: Total 32 (delta 0), reused 0 (delta 0), pack-reused 32 2
Receiving objects: 100% (32/32), 59.07 KiB | 0 bytes/s, done.
Resolving deltas: 100% (6/6), done.
-- The C compiler identification is MSVC 19.0.23026.0
-- The CXX compiler identification is MSVC 19.0.23026.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at C:/gtk-build/tools/cmake-3.7.2-win64-x64/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find PythonLibs (missing: PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS)
  (Required is at least version "TRUE")
Call Stack (most recent call first):
  C:/gtk-build/tools/cmake-3.7.2-win64-x64/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  C:/gtk-build/tools/cmake-3.7.2-win64-x64/share/cmake-3.7/Modules/FindPythonLibs.cmake:255 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:5 (find_package)

-- Configuring incomplete, errors occurred!
See also "C:/gtk-build/build/Win32/release/pycairo/CMakeFiles/CMakeOutput.log".
Traceback (most recent call last):
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 214, in build
    self.__build_one(p)
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 286, in __build_one
    proj.build()
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\base_builders.py", line 98, in build
    self.builder.exec_vs(cmd, working_dir=work_dir)
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 498, in exec_vs
    self.__execute(self.__sub_vars(cmd), working_dir=working_dir, add_path=add_path, env=self.vs_env)
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 530, in __execute
    subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
  File "C:\Python36\lib\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'cmake -G "NMake Makefiles" -DCMAKE_INSTALL_PREFIX="C:\gtk-build\build\Win32\release\pycairo-rel" -DGTK_DIR="C:\gtk-build\gtk\Win32\release" -DCMAKE_BUILD_TYPE=RelWithDebInfo' returned non-zero exit status 1.
Error: pycairo build failed

**Comment by guruDanny67** [comment]
I think that this library is intended to be used with a 2.7.x python: to run the script and build a 3.5/3.6 is needed but the module pyxxx are linked to the 2.7 version (in my setup it says "found asuitable version "2.7.13", minimu required is "TRUE").

So probably you need to install also a python 2.7 but if you want to use the module in python you should also recompile all the python stack (from www.python.org, the interpreter, library, ...) with the same compiler you used for the module to avoid runtime mismatch that can lead to errors and corruptions (you alloc a block on memory from python in the vs2008 format and you free the same block from the gtk in a way that is expectiong a vs2015 format memory block).

What the use of the library ? You need this or you jast want to build everything ? Thanks.

**Comment by guruDanny67** [comment]
The project we have in gvsbuild are really old: pycairo is version 1.8.10 and doen't support Python 3 in the C code. If I let cmake find the library (from a 3.4 version I have) the compilation starts but there are a lot of errors due to the python 2 -> 3 switch in the C API (for example it give warning on 'PyInt_FromLong(...) not defined because that function is gone with python 3).

The current PyCairo (1.15.x) has support for 2.7 and 3.3+: I don't know if is worth trying to integrate it in our builds (we already built all the libraries needed so maybe it's not a big deal ...)

Many thank.

**Comment by tom2x2** [comment]
@guruDanny67 I want to render text with pango to a cairo surface, I don't use gtk as such otherwise. 

Pycairo 1.15.x can be compiled separately, and works fine with python 3.6. However, to use pango I need pygobject in order to import it like this:

`from gi.repository import Pango, PangoCairo`

Unfortunately, compiling pygobject fails in exactly the same way as pycairo.

**Comment by guruDanny67** [comment]
We are working on putting gi & pygobject on this stack, I have something
running from an old gtk 3.22.6 but it's not ready to go in the wild :)

If python 3.4 is enough for you on sf.net there is a pygobject installer
(for x86 and x64 platform) with a lot of modules (the full gtk3 stack is
present)

It's very high on my priority but it takes time.

Il 13 set 2017 13:44, "tom2x2" <notifications@github.com> ha scritto:

**Comment by tom2x2** [comment]
No worries, many thanks for making this project available actually!

I am able to use pycairo right now, and I have a kind of a workaround for text. However, pango is a much much better option for text layout, so as soon as I can get gi/pygobject from here, I will switch to pango.

**Comment by lazka** [comment]
pygobject master now also has a distutils/setuptools based build system, but it's only tested under MSYS2

**Comment by lazka** [comment]
See #241

**Comment by lazka** [comment]
Should be fixed now.
