### ISSUE TITLE
MSBUILD : error MSB1008 when python directory contains a space

### ISSUE THREAD

**Issue by dominicprice** [wingtk/gvsbuild#195]
For example, I tried to build with the option --python-dir "C:\Program Files\Python36" and it failed to build as the /p:PythonPath=<python-path> does not enclose the python directory in quotes and so VS thinks one is trying to supply Files\Python36 as the name of another project to build. 

Easily solved by temporarily copying the Python36 folder directly to C:\Python36 but thought I'd mention it anyway, particularly as the error message generated isn't immediately enlightening.

PS: Building on Windows 10 with VS2017

**Comment by nacho** [comment]
Can you give a try to the patch I just pushed? If it does not work please reopen the issue
