### ISSUE TITLE
Error building harfbuzz

### ISSUE THREAD

**Issue by guruDanny67** [wingtk/gvsbuild#201]
Update the script and the building of harfbuzz raise one error:
"NMAKE : fatal error U1052: file 'Makefile.vc' not found"

The updated version should be built with cmake ?

**Comment by anthrotype** [comment]
yes https://github.com/behdad/harfbuzz/pull/562

**Comment by nacho** [comment]
I tried to update harfbuzz to build with cmake but for some reason it gives a compile error when building the gobject library

**Comment by guruDanny67** [comment]
Version 1.7.1 ?

**Comment by nacho** [comment]
Yes, I tried that one

**Comment by anthrotype** [comment]
Maybe @ebraminio knows why?

**Comment by ebraminio** [comment]
> gives a compile error when building the gobject library

What compile error it gives?

**Comment by ebraminio** [comment]
As https://github.com/harfbuzz/harfbuzz/issues/634 the issue is our Windows CI stopped working and https://github.com/harfbuzz/harfbuzz/issues/635 is a Windows build fix.

**Comment by nacho** [comment]
I'll give a try to it in a couple of days. Thanks

**Comment by nacho** [comment]
1.7.2 did it. Thanks

**Comment by ebraminio** [comment]
Thats great! Thanks to @fanc999 for bringing back gobject/gir support to harfbuzz cmake https://github.com/harfbuzz/harfbuzz/pull/572 .
