### ISSUE TITLE
License Issue

### ISSUE THREAD

**Issue by BingTSC** [wingtk/gvsbuild#203]
I saw you add this commit https://github.com/wingtk/gvsbuild/blob/master/COPYING  

I forked your repo before and at that time seems no license file.  Currently there is.  Can I still use your repo to build the latest GTK?  

Also lots of GTK dependency are under LGPL 2.1 like Pango, Cairo,  why this one is GPL 2.0? Thank you.

**Comment by rjmporter** [comment]
👍  -- Specifically, the area of concern here is this question: is the GPL2.0 license intended to cover the code from the *.patches files? 

Since those files are not specifically excluded from the repo's GPL coverage, it seem the resulting binaries are now GPL 2.0 licensed as well.

**Comment by nacho** [comment]
The gpl license covers the scripts to build while project has to be analyzed independent. I.e gtk or glib are LGPL and that includes the patches applied to those projects

**Comment by BingTSC** [comment]
@nacho  I'm using project.py and build.py,  do you mean those are under GPL?

**Comment by nacho** [comment]
Yes those are under gpl. Do u have any issues with that?

**Comment by BingTSC** [comment]
> Yes those are under gpl. Do u have any issues with that?

No, we don't have any issues with GPL for the build scripts.

Our concern is that we aren't using any GPL licensed projects in our commercial application.

We will review each library's license that we intend to use.

Thanks for the clarification!

**Comment by pbor** [comment]
I think this is worth making explicit either in a "license" section of the readme or in a LICENSE.md file. Something like:

This build script is licensed under the GPL2.0 license, see the COPYING file for the full text.
The binaries produced by the build script are licensed under the license terms of the project that gets built (ie glib is LGPL so you can use glib.dll built with this script under the terms of LGPL).
Patches included in the repository are licensed under the license terms of the project they apply to.
