### ISSUE TITLE
I cannot push my branch

### ISSUE THREAD

**Issue by BingTSC** [wingtk/gvsbuild#204]
I have two commits
(1)  fix carios x64 bit crash
(2)  apply version info to libpng16.dll

but seems I cannot push my branch to your repo and open PR?  could you help please? thank you.

**Comment by anthrotype** [comment]
https://help.github.com/articles/creating-a-pull-request/

**Comment by BingTSC** [comment]
> https://help.github.com/articles/creating-a-pull-request/

this doesn't help.  seems I don't have permission to push for this branch

**Comment by anthrotype** [comment]
> If you don't have write access to the repository where you'd like to create a pull request, you must create a fork, or copy, of the repository first. For more information, see ["Creating a pull request from a fork"](https://help.github.com/articles/creating-a-pull-request-from-a-fork)...

**Comment by BingTSC** [comment]
@anthrotype  I tried that, the problem is I only want to cherry-pick some commits in my fork.

**Comment by TingPing** [comment]
You create a fork, on that fork you make a branch and push whatever to that branch, then on github you create a new pull request selecting your repo/branch and it will only pull in the new commits.

**Comment by BingTSC** [comment]
I made a fork long time ago which has commits I don't want to go into this gvsbuild repo.   Are you guys suggest me to make a new fork?  any other way to do it?

**Comment by TingPing** [comment]
According to github you have no forks. The term "fork" is a github-ism.

If you have created a messy master branch in your local repo then you will have to figure a way to clean that up, probably by make a new branch from an old commit, and cherry-picking what you need.

**Comment by BingTSC** [comment]
thanks for all help.

Here it is: https://github.com/wingtk/gvsbuild/pull/205
