### ISSUE TITLE
GdkPixbuf loader cache not rebuilt automatically

### ISSUE THREAD

**Issue by TingPing** [wingtk/gvsbuild#238]
`(gdk-pixbuf-pixdata.exe:10460): GdkPixbuf-WARNING **: Cannot open pixbuf loader module file 'c:\gtk-build\gtk\Win32\release\lib\gdk-pixbuf-2.0\2.10.0\loaders.cache': No such file or directory`

**Comment by nacho** [comment]
I guess we need to run it as we do with the stuff from gtk.
See https://github.com/wingtk/gvsbuild/blob/master/gvsbuild/projects.py#L611
