### ISSUE TITLE
gobject-introspection: cairo-1.0.gir references libcairo-gobject.so.2 instead of cairo-gobject.dll

### ISSUE THREAD

**Issue by lazka** [wingtk/gvsbuild#243]
The installed file current looks like this (and in the typelib as well):

```
<?xml version="1.0"?>
<repository version="1.2"
	    xmlns="http://www.gtk.org/introspection/core/1.0"
	    xmlns:c="http://www.gtk.org/introspection/c/1.0"
	    xmlns:glib="http://www.gtk.org/introspection/glib/1.0">
  <package name="cairo-gobject"/>
  <namespace name="cairo" version="1.0"
	     shared-library="libcairo-gobject.so.2"
	     c:identifier-prefixes="cairo"
	     c:symbol-prefixes="cairo">
...
```

This leads to warnings as can be seen in https://github.com/wingtk/gvsbuild/pull/242#issuecomment-371083690

In PyGObject we use pycairo directly in most cases which is probably why this doesn't lead to errors..

**Comment by nacho** [comment]
I guess we can make a hack and make a replacement in the installed file for now in gvsbuild, but this should be fixed in upstream IMHO

**Comment by lazka** [comment]
Note that the replacement needs to happen before the .typelib is generated.

**Comment by lazka** [comment]
Looks like this should compare to "windows" and not "win32": https://gitlab.gnome.org/GNOME/gobject-introspection/blob/wip/meson/gir/meson.build#L4

and it should use "cairo-gobject.dll" if msvc is used.

**Comment by nacho** [comment]
@TingPing can you check this out? ^^

**Comment by lazka** [comment]
https://bpaste.net/show/c5d1d0c635ce

**Comment by lazka** [comment]
Thanks, pushed.

**Comment by cas--** [comment]
This seems to be an issue again with recent builds @lazka what was the change that you made?

**Comment by lazka** [comment]
Hm, somehow this was lost in the official meson port. let me check

**Comment by cas--** [comment]
Any update on this? Could you re-open the issue?
