### ISSUE TITLE
Build fails on gettext (VS2017 v15.7.1)

### ISSUE THREAD

**Issue by Adriatic1** [wingtk/gvsbuild#260]
I've updated to latest VS, and the build fails on gettext:

c:\gtk-build\gvsbuild>python.exe build.py build gtk3 adwaita-icon-theme gtksourceview3 --platform x64 --vs-ver 15 --win-sdk-ver 10.0.16299.0 --vs-install-path "c:\Program Files (x86)\Microsoft Visual Studio\2017\Community"

Building project ninja
Building project meson
Building project pkg-config
HEAD is now at a50bf72... Fix incorrect comment (#178)
[0/1] Installing files.
Installing pkgconf-3.dll to C:\gtk-build\gtk\x64\release\bin\pkgconf-3.dll
Installing pdb file pkgconf-3.pdb to C:\gtk-build\gtk\x64\release\bin\pkgconf-3.pdb
Installing pkgconf.lib to C:\gtk-build\gtk\x64\release\lib\pkgconf.lib
Installing pdb file pkgconf.pdb to C:\gtk-build\gtk\x64\release\lib\pkgconf.pdb
Installing pkgconf.exe to C:\gtk-build\gtk\x64\release\bin\pkgconf.exe
Installing pdb file pkgconf.pdb to C:\gtk-build\gtk\x64\release\bin\pkgconf.pdb
Installing libpkgconf.h to C:\gtk-build\gtk\x64\release\include\libpkgconf
Installing stdinc.h to C:\gtk-build\gtk\x64\release\include\libpkgconf
Installing iter.h to C:\gtk-build\gtk\x64\release\include\libpkgconf
Installing bsdstubs.h to C:\gtk-build\gtk\x64\release\include\libpkgconf
Installing libpkgconf-api.h to C:\gtk-build\gtk\x64\release\include\libpkgconf
Installing C:\gtk-build\build\x64\release\pkg-config\man/pkgconf.1 to C:\gtk-build\gtk\x64\release\share/man\man1
Installing C:\gtk-build\build\x64\release\pkg-config\man/pkg.m4.7 to C:\gtk-build\gtk\x64\release\share/man\man7
Installing C:\gtk-build\build\x64\release\pkg-config\pkg.m4 to C:\gtk-build\gtk\x64\release\share/aclocal
        1 file(s) copied.
Building project perl
Building project cmake
Building project win-iconv
-- Configuring done
-- Generating done
-- Build files have been written to: C:/gtk-build/build/x64/release/win-iconv-cmake
ninja: no work to do.
[0/1] Running tests...
Test project C:/gtk-build/build/x64/release/win-iconv-cmake
    Start 1: win_iconv_test
1/1 Test #1: win_iconv_test ...................   Passed    0.07 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) =   0.08 sec
[0/1] Install the project...
-- Install configuration: "RelWithDebInfo"
-- Installing: C:/gtk-build/build/x64/release/win-iconv-rel/lib/iconv.lib
-- Installing: C:/gtk-build/build/x64/release/win-iconv-rel/bin/iconv.dll
-- Installing: C:/gtk-build/build/x64/release/win-iconv-rel/bin/win_iconv.exe
-- Installing: C:/gtk-build/build/x64/release/win-iconv-rel/include/iconv.h
Building project gettext
  memchr.c
  memmove.c
c:\gtk-build\build\x64\release\gettext\gettext-runtime\gnulib-lib\memmove.c(12)
: error C2169: 'memmove': intrinsic function, cannot be defined [C:\gtk-build\b
uild\x64\release\gettext\build\win32\vs15\grt.vcxproj]
c:\gtk-build\build\x64\release\gettext\gettext-runtime\gnulib-lib\memchr.c(60):
 error C2169: 'memchr': intrinsic function, cannot be defined [C:\gtk-build\bui
ld\x64\release\gettext\build\win32\vs15\grt.vcxproj]
  asprintf.vcxproj -> C:\gtk-build\build\x64\release\gettext\build\win32\vs15\R
  elease\x64\bin\asprintf.dll
  intl.vcxproj -> C:\gtk-build\build\x64\release\gettext\build\win32\vs15\Relea
  se\x64\bin\intl.dll
  memchr.c
c:\gtk-build\build\x64\release\gettext\gettext-tools\msvc\config.h(2587): warni
ng C4005: 'ICONV_CONST': macro redefinition [C:\gtk-build\build\x64\release\get
text\build\win32\vs15\gnu.vcxproj]
  c:\gtk-build\build\x64\release\gettext\gettext-tools\msvc\config.h(2587): not
  e: command-line arguments:  see previous definition of 'ICONV_CONST'
c:\gtk-build\build\x64\release\gettext\gettext-tools\libgettextpo\memchr.c(60):
 error C2169: 'memchr': intrinsic function, cannot be defined [C:\gtk-build\bui
ld\x64\release\gettext\build\win32\vs15\gnu.vcxproj]
  glib_rpl.vcxproj -> C:\gtk-build\build\x64\release\gettext\build\win32\vs15\R
  elease\x64\bin\glib_rpl.lib
  libxml_rpl.vcxproj -> C:\gtk-build\build\x64\release\gettext\build\win32\vs15
  \Release\x64\bin\libxml_rpl.lib
  libcroco_rpl.vcxproj -> C:\gtk-build\build\x64\release\gettext\build\win32\vs
  15\Release\x64\bin\libcroco_rpl.lib
  gettextlib.vcxproj -> C:\gtk-build\build\x64\release\gettext\build\win32\vs15
  \Release\x64\bin\gettextlib.dll
  gettextsrc.vcxproj -> C:\gtk-build\build\x64\release\gettext\build\win32\vs15
  \Release\x64\bin\gettextsrc.dll
  msgcmp.vcxproj -> C:\gtk-build\build\x64\release\gettext\build\win32\vs15\Rel
  ease\x64\bin\msgcmp.exe
  msgfmt.vcxproj -> C:\gtk-build\build\x64\release\gettext\build\win32\vs15\Rel
  ease\x64\bin\msgfmt.exe
  msgmerge.vcxproj -> C:\gtk-build\build\x64\release\gettext\build\win32\vs15\R
  elease\x64\bin\msgmerge.exe
  msgunfmt.vcxproj -> C:\gtk-build\build\x64\release\gettext\build\win32\vs15\R
  elease\x64\bin\msgunfmt.exe
  xgettext.vcxproj -> C:\gtk-build\build\x64\release\gettext\build\win32\vs15\R
  elease\x64\bin\xgettext.exe
  recode-sr-latin.vcxproj -> C:\gtk-build\build\x64\release\gettext\build\win32
  \vs15\Release\x64\bin\recode-sr-latin.exe
  msguniq.vcxproj -> C:\gtk-build\build\x64\release\gettext\build\win32\vs15\Re
  lease\x64\bin\msguniq.exe
  msginit.vcxproj -> C:\gtk-build\build\x64\release\gettext\build\win32\vs15\Re
  lease\x64\bin\msginit.exe
  msgfilter.vcxproj -> C:\gtk-build\build\x64\release\gettext\build\win32\vs15\
  Release\x64\bin\msgfilter.exe
  msgexec.vcxproj -> C:\gtk-build\build\x64\release\gettext\build\win32\vs15\Re
  lease\x64\bin\msgexec.exe
  msgen.vcxproj -> C:\gtk-build\build\x64\release\gettext\build\win32\vs15\Rele
  ase\x64\bin\msgen.exe
  msgconv.vcxproj -> C:\gtk-build\build\x64\release\gettext\build\win32\vs15\Re
  lease\x64\bin\msgconv.exe
  msgcomm.vcxproj -> C:\gtk-build\build\x64\release\gettext\build\win32\vs15\Re
  lease\x64\bin\msgcomm.exe
  msgcat.vcxproj -> C:\gtk-build\build\x64\release\gettext\build\win32\vs15\Rel
  ease\x64\bin\msgcat.exe
  msgattrib.vcxproj -> C:\gtk-build\build\x64\release\gettext\build\win32\vs15\
  Release\x64\bin\msgattrib.exe
  grep.vcxproj -> C:\gtk-build\build\x64\release\gettext\build\win32\vs15\Relea
  se\x64\bin\grep.lib
  msggrep.vcxproj -> C:\gtk-build\build\x64\release\gettext\build\win32\vs15\Re
  lease\x64\bin\msggrep.exe
Traceback (most recent call last):
  File "c:\gtk-build\gvsbuild\gvsbuild\utils\builder.py", line 325, in build
    self.__build_one(p)
  File "c:\gtk-build\gvsbuild\gvsbuild\utils\builder.py", line 404, in __build_one
    proj.build()
  File "c:\gtk-build\gvsbuild\gvsbuild\projects.py", line 375, in build
    self.exec_msbuild(r'build\win32\vs%(vs_ver)s\gettext.sln')
  File "c:\gtk-build\gvsbuild\gvsbuild\utils\base_project.py", line 76, in exec_msbuild
    self.exec_vs('msbuild ' + cmd + ' /p:Configuration=' + configuration + ' %(msbuild_opts)s', add_path=add_path)
  File "c:\gtk-build\gvsbuild\gvsbuild\utils\base_project.py", line 71, in exec_vs
    self.builder.exec_vs(cmd, working_dir=self._get_working_dir(), add_path=add_path)
  File "c:\gtk-build\gvsbuild\gvsbuild\utils\builder.py", line 614, in exec_vs
    self.__execute(self.__sub_vars(cmd), working_dir=working_dir, add_path=add_path, env=self.vs_env)
  File "c:\gtk-build\gvsbuild\gvsbuild\utils\builder.py", line 646, in __execute
    subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
  File "C:\Python36\lib\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'msbuild build\win32\vs15\gettext.sln /p:Configuration=release /nologo /p:Platform=x64 /p:PythonPath="C:\Python36" /p:PythonDir="C:\Python36"   /v:minimal /p:WindowsTargetPlatformVersion="10.0.16299.0"' returned non-zero exit status 1.
Error: gettext build failed

To see why it failed I ran:
cd c:\gtk-build\build\x64\release\gettext\
msbuild build\win32\vs15\gettext.sln /p:Configuration=release /nologo /p:Platform=x64 /p:PythonPath="C:\Python36" /p:PythonDir="C:\Python36"   /v:minimal /p:WindowsTargetPlatformVersion="10.0.16299.0"

These two errors seem to be the cause:
  memmove.c
c:\gtk-build\build\x64\release\gettext\gettext-runtime\gnulib-lib\memmove.c(12): error C2169: 'memmove': intrinsic function, cannot be defined [c:\gtk-build\build\x64\release\gettext\build\win32\vs15\grt.vcxproj]
c:\gtk-build\build\x64\release\gettext\gettext-runtime\gnulib-lib\memchr.c(60): error C2169: 'memchr': intrinsic function, cannot be defined [c:\gtk-build\build\x64\release\gettext\build\win32\vs15\grt.vcxproj]
  asprintf.vcxproj -> c:\gtk-build\build\x64\release\gettext\build\win32\vs15\Release\x64\bin\asprintf.dll
  intl.vcxproj -> c:\gtk-build\build\x64\release\gettext\build\win32\vs15\Release\x64\bin\intl.dll
  memchr.c
c:\gtk-build\build\x64\release\gettext\gettext-tools\msvc\config.h(2587): warning C4005: 'ICONV_CONST': macro redefinition [c:\gtk-build\build\x64\release\gettext\build\win32\vs15\gnu.vcxproj]
  c:\gtk-build\build\x64\release\gettext\gettext-tools\msvc\config.h(2587): note: command-line arguments:  see previous definition of 'ICONV_CONST'
c:\gtk-build\build\x64\release\gettext\gettext-tools\libgettextpo\memchr.c(60): error C2169: 'memchr': intrinsic function, cannot be defined [c:\gtk-build\build\x64\release\gettext\build\win32\vs15\gnu.vcxproj]

Regards,
  Miroslav

**Comment by dsorber** [comment]
@nacho As we discussed in #229  here is a patch that ifdefs out the `memmove()` and `memchr()` functions, to allow the gettext build to succeed for MSVC 15: https://gist.github.com/dsorber/bb8be27a36fd34011b98447549128ebf

**Comment by Adriatic1** [comment]
Thanks, this fixed this particular issue, will open new issues for the rest of the problems.

**Comment by nacho** [comment]
Any chance you could make a pull request with the patch? Though I think it needs a change to check the visual studio version.

**Comment by nacho** [comment]
@fanc999 thoughts?

**Comment by Adriatic1** [comment]
I've created a commit here: https://github.com/wingtk/gvsbuild/commit/b955b07a35f10070e22e467ee50161eb355ca025
Creating PR unfortunately pulls 2 old commits + 2 new reverts of these, so it's kind of messy (and I am low on free time) :(
Can you cherry pick this commit only ?

I've modified the code to disable the code if VS 2017 detected and version is newer than 15.5 (I did not find precise info on when this became the issue).

**Comment by nacho** [comment]
Pushed to master thanks!

**Comment by dsorber** [comment]
Awesome @Adriatic1! Thanks for cleaning up the patch and creating the pull request.

**Comment by Adriatic1** [comment]
I hope we'll be fix the rest of the issues soon :) 
I am looking forward to promote GTK3 port of my app (NoteCase Pro) from beta to an official version.

**Comment by guruDanny67** [comment]
We absolutely need to fix all the issues, especially the ones with the Vs 2017 but if you are in a hurry you can build all the Gtk stack with vs2015 (or the vs2017 faking the version) and use vs2017 for all your source code; this should work, better than mixing vs2010/2013 with the new one because they have, now, a unified runtime so the calloc/free and new/delete from the two languages are, in the end, the same (or, at least, is what Microsoft said).

It can be a fast way to see if everything works as expected :)

With best regards
