### ISSUE TITLE
Build fails on libjpeg-turbo (VS2017 v15.7.1) 

### ISSUE THREAD

**Issue by Adriatic1** [wingtk/gvsbuild#261]
After patching the gettext with the patch from issue #260, build process now crashes on libjpeg-turbo.

The command is the same:

[24/255] Generating jchuff-sse2-64.obj
FAILED: simd/jchuff-sse2-64.obj
cmd.exe /C "cd /D C:\gtk-build\build\x64\release\libjpeg-turbo-cmake\simd && C:\gtk-build\tools\nasm-2.13.01\nasm.exe -fwin64 -DWIN64 -D__x86_64__ -IC:/gtk-build/build/x64/release/libjpeg-turbo/win/ -IC:/gtk-build/build/x64/release/libjpeg-turbo/simd/ -g C:/gtk-build/build/x64/release/libjpeg-turbo/simd/jchuff-sse2-64.asm -oC:/gtk-build/build/x64/release/libjpeg-turbo-cmake/simd/jchuff-sse2-64.obj"
ninja: build stopped: subcommand failed.

**Comment by Adriatic1** [comment]
The command:
c:\gtk-build\gvsbuild>python.exe build.py build gtk3 adwaita-icon-theme gtksourceview3 --platform x64 --vs-ver 15 --win-sdk-ver 10.0.16299.0 --vs-install-path "c:\Program Files (x86)\Microsoft Visual Studio\2017\Community"

Note that I've tried to execute the failing command manually, no error output is generated.

**Comment by Adriatic1** [comment]
I've tried with latest 15.7.2 and with installed toolset for VS2015, no luck.
But then I've changed SDK to an older one, and that works (until it fails with libcroco who is missing .sln file for vs15):
c:\gtk-build\gvsbuild>python.exe build.py build gtk3 adwaita-icon-theme gtksourceview3 --platform x64 --vs-ver 15 --win-sdk-ver 10.0.14393.0  --vs-install-path "c:\Program Files (x86)\Microsoft Visual Studio\2017\Community"

To conclude: SDK "10.0.16299.0" doesn't work correctly (with both VS2017 and VS2015 toolset), but SDK "10.0.14393.0" works correctly!
I guess you can close the ticket :)

**Comment by nacho** [comment]
Thanks for the testing. For libcroco feel free to send a pull request adding the projects for vs 2017
