### ISSUE TITLE
Vs2013 build

### ISSUE THREAD

**Issue by guruDanny67** [wingtk/gvsbuild#263]
I try to build the stack with the vs2013 (to check some regression & some modification to build cogl & clutter now that mkenums & marshal are python script) but it stops with errors on pkg-config (the new pkgconf, really).

I take a look at the errors (some inline that's missing in the vs2013, __func__ instead of __FUNCTION__, missing snprintf, ...) but is something we want to fix because we need/want/like to build all with vs2013 or is simply useless because other projects cannot be compiled now with this toolchain ?

On the README.md we say we focus on 2017 but we claim we support also the 2013: if it's not the case anymore we can adjust the doc and drop the vs12 dirs on some projects.

The fact that the build stop with the pkg-config means I cannot test some other projects and I don't want to fix all on pkgconf just to discover that other bigger libs doesn't compile :(

Thanks

**Comment by nacho** [comment]
If this is a hard stop for you I'd rather go back to the old pkgconfig to keep you happy.

**Comment by guruDanny67** [comment]
For me it's not an hard stop (I use the 2015 & 2017 version, the 2015 to
make python 3.6 happy and the 2017 for the gtkmm stack) but someone could
use it.

I'll try with the old pkg-config just to see if the other libs have
problems (if the current glib cannot be compiled with the vs2013 it's
useless try to mantain this compiler ...) and decide how to proceed.

Actually we can't use different projects based on the vs version we are
using (or some startup option): this thing may help keep old version
around.

While I'm looking this I try also to put in the lst output the current
version of the project we build so we don't need to go through all the code.

Thank

2018-06-11 22:54 GMT+02:00 Ignacio Casal Quinteiro <notifications@github.com

**Comment by guruDanny67** [comment]
At the end was easier to make the new pkg-config compile on vs2013 (the old one depends on glib that depends on pkg-config ...)
I try to build the full gtk3 stack and it seems to work, so I close the issue.
