### ISSUE TITLE
Kill glib-networking

### ISSUE THREAD

**Issue by nacho** [wingtk/gvsbuild#265]
@guruDanny67 I think we should remove this project now that we have glib-openssl.

**Comment by guruDanny67** [comment]
I'm fine with that, I don't use them, for now :)

The two library do the same thing ? It seems the glib-networking is actively developed. I ask because I don't know anything about the two (and on the github pages there is not much, only 'Network related giomodules ...')

**Comment by nacho** [comment]
they provide the same one using gnutls and the other using openssl. glib-networking has some more features and it is definitely more tested. glib-openssl is maintained by me so it is still used but not so many users. It compiles on windows with visual studio properly as well. Also the glib-networking one was using a branch which was basically glib-openssl since we forked from that branch.

**Comment by nacho** [comment]
Just a note on this, see https://gitlab.gnome.org/GNOME/glib-networking/merge_requests/10
Basically we are merging back the openssl backend in glib-networking, so soon we should probably use that one instead of glib-openssl.

**Comment by danyeaw** [comment]
@nacho Should we still remove glib-networking?

**Comment by nacho** [comment]
nope, I actually removed glib-openssl since it was merged back into glib-networking
