### ISSUE TITLE
Get Build failure

### ISSUE THREAD

**Issue by BerndDemian** [wingtk/gvsbuild#268]
Installing C:\gtk-build\build\Win32\release\glib-meson\glib-gettextize to C:\gtk-build\gtk\Win32\release\bin
Running custom install script 'C:\\Python36\\python.exe C:\\gtk-build\\tools\\meson-0.46.1\\meson.py --internal gettext install --subdir=po --localedir=share/locale --pkgname=glib20'
msgfmt: iconv failure: No error
Traceback (most recent call last):
  File "C:\gtk-build\tools\meson-0.46.1\meson.py", line 26, in <module>
    sys.exit(main())
  File "C:\gtk-build\tools\meson-0.46.1\meson.py", line 23, in main
    return mesonmain.run(sys.argv[1:], launcher)
  File "C:\gtk-build\tools\meson-0.46.1\mesonbuild\mesonmain.py", line 320, in run
    sys.exit(run_script_command(args[1:]))
  File "C:\gtk-build\tools\meson-0.46.1\mesonbuild\mesonmain.py", line 269, in run_script_command
    return cmdfunc(cmdargs)
  File "C:\gtk-build\tools\meson-0.46.1\mesonbuild\scripts\gettext.py", line 116, in run
    if gen_gmo(src_sub, bld_sub, langs) != 0:
  File "C:\gtk-build\tools\meson-0.46.1\mesonbuild\scripts\gettext.py", line 66, in gen_gmo
    '-o', os.path.join(bld_sub, l + '.gmo')])
  File "C:\Python36\lib\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['msgfmt', 'C:\\gtk-build\\build\\Win32\\release\\glib\\po\\af.po', '-o', 'C:\\gtk-build\\build\\Win32\\release\\glib-meson\\po\\af.gmo']' returned non-zero exit status 1.
FAILED: meson-install
"C:\\Python36\\python.exe" "C:\\gtk-build\\tools\\meson-0.46.1\\meson.py" "--internal" "install" "C:\\gtk-build\\build\\Win32\\release\\glib-meson\\meson-private\\install.dat"
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 361, in build
    if self.__build_one(p):
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 477, in __build_one
    skip_deps = proj.build()
  File "C:\gtk-build\github\gvsbuild\gvsbuild\projects.py", line 394, in build
    Meson.build(self, meson_params='-Dinternal_pcre=true')
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\base_builders.py", line 61, in build
    self.builder.exec_vs('ninja install', working_dir=ninja_build)
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 705, in exec_vs
    self.__execute(self.__sub_vars(cmd), working_dir=working_dir, add_path=add_path, env=self.vs_env)
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 737, in __execute
    subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
  File "C:\Python36\lib\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'ninja install' returned non-zero exit status 1.
Error: glib build failed

I use VS 2017 Community and start with vs-install-path
Please help me, because I have no Idea
Thanks Bernd

**Comment by guruDanny67** [comment]
It seems something related to gettext/iconv, looking at the error.

A test that can be done is, as usual, build everything from scratch (it take time ...) to see if it's something related to some old stuff lying around. Add --from-scratch to your command line (the first run) to let the script clean everything and see what's happen.

With best regards.

**Comment by BerndDemian** [comment]
Hallo guru,
thanks for your quick answer, but i was in business travel.
today i have a new try, from scratch
1. git clone https://github.com/wingtk/gvsbuild.git
2. python .\build.py build gtk3 -p x64 --vs-install-path="C:\Program Files
(x86)\Microsoft Visual Studio 14.0" --from-scratch

but i get the same error message:
...
Installing C:\gtk-build\build\x64\release\glib-meson\glib-gettextize to
C:\gtk-build\gtk\x64\release\bin
Running custom install script 'C:\\Python36\\python.exe
C:\\gtk-build\\tools\\meson-0.46.1\\meson.py --internal gettext install
--subdir=po --localedir=share/locale --pkgname=glib20'
msgfmt: iconv failure: No error

Traceback (most recent call last):
  File "C:\gtk-build\tools\meson-0.46.1\meson.py", line 26, in <module>
    sys.exit(main())
  File "C:\gtk-build\tools\meson-0.46.1\meson.py", line 23, in main
    return mesonmain.run(sys.argv[1:], launcher)
  File "C:\gtk-build\tools\meson-0.46.1\mesonbuild\mesonmain.py", line 320,
in run
    sys.exit(run_script_command(args[1:]))
  File "C:\gtk-build\tools\meson-0.46.1\mesonbuild\mesonmain.py", line 269,
in run_script_command
    return cmdfunc(cmdargs)
  File "C:\gtk-build\tools\meson-0.46.1\mesonbuild\scripts\gettext.py",
line 116, in run
    if gen_gmo(src_sub, bld_sub, langs) != 0:
  File "C:\gtk-build\tools\meson-0.46.1\mesonbuild\scripts\gettext.py",
line 66, in gen_gmo
    '-o', os.path.join(bld_sub, l + '.gmo')])
  File "C:\Python36\lib\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['msgfmt',
'C:\\gtk-build\\build\\x64\\release\\glib\\po\\af.po', '-o',
'C:\\gtk-build\\build\\x64\\release\\glib-meson\\po\\af.gmo']' returned
non-zero exit status 1.
FAILED: meson-install

Installed python : 3.6.6
Installed msvs  2015 cmmunity

Thanks for every hint
Bernd



2018-08-03 14:19 GMT+02:00 guruDanny67 <notifications@github.com>:

**Comment by guruDanny67** [comment]
If you are using the vs 2015 you should tell the script that (I don't know
if it's something that can change the resul, but it's better to avoid
doubts) with the '--vs-ver 14' option (the default is 12, corresponding to
visual studio 2013).

You probably need to run the script, the first time, with the
--from-scratch to clean.up everything.

if you got the same error one try is to build the x86 (32 bit) version to
see what's happen (I normally build the 32 bit version) and if the problem
is due to the x64/x86 architecture.

Another fast test you can do is, in x64 mode, to build only the dev-shell
project (WITHOUT the --from-scratch option, you should leave all you've
build before): this puts you in a shell with the (hopefully) correct visual
studio environment, all the tools and the gtk bin build directory in the
path: from this you can try to launch the msgfmt command (simply typing
msgfm.exe) and see what's happen, if the msgfmt executable can get all the
.dll it needs

We need to write a 'troubleshooting' or 'developer' guide soon :)

With best regards



Il giorno mer 1 ago 2018 alle ore 10:13 BerndDemian <
notifications@github.com> ha scritto:

**Comment by guruDanny67** [comment]
I've made a fast test with the vs2015 but setting --vs-ver 12: the results
are the one you have, with the 'msgfmt: iconv failure: No error' so you
definetely need to pass the correct version to the script.

I have a couple of batch, named with a lot of fantasy mk15.bat & mk17.bat,
that sets all the parameters I need for the two version and I only add some
option and the project(s) I want to build.





Il giorno mer 15 ago 2018 alle ore 19:05 Daniele Forghieri <
daniele.forghieri@gmail.com> ha scritto:

**Comment by guruDanny67** [comment]
Issue resolved? We can close it ?

**Comment by KhaledSMQ** [comment]
@guruDanny67 I have exactly same issue, the build works with only on x86.
