### ISSUE TITLE
Build script options for Platform Toolset with VS2017

### ISSUE THREAD

**Issue by Praseodia** [wingtk/gvsbuild#270]
How can I set the platform toolset when running the build script? I can see in the script to use "15" for VS2017, but when I open the generated solution in VS2017, in project property, it sets Platform Toolset to V150. VS2017 is V141.

Below is the command I used:
python .\build.py build -p x64 -c debug --msys-dir C:\msys64 --vs-ver 15 --win-sdk-ver 8.1 glib

**Comment by guruDanny67** [comment]
We don't generate the solution, these ones are from the glib source
tarballs: you may ask on the glib mailing list or, with an editor, change
from v150 to 141 in the solution/projects files.

For glib we now use meson to build it so we don't generate/use the visual
studio solution but, from a series of meson.build files, a build.ninja file
is created, used by ninja to build everything.

With best regards

Il giorno ven 17 ago 2018 alle ore 03:31 Jen <notifications@github.com> ha
scritto:

**Comment by Praseodia** [comment]
Oh I see. I thought it was related to the python script because the --win-sdk-ver argument does affect the project files. I did have to manually change from v150 to v141, but that is one of the only two things I had to modify to build successfully, which is much better than all the other builds I have tried. I will try the glib mailing list instead, thank you so much.
