### ISSUE TITLE
pygtk not building

### ISSUE THREAD

**Issue by guruDanny67** [wingtk/gvsbuild#277]
Now, with vs2015 & 2017, pygtk is the only project that gives errors and cannot be built. 

It's really needed now with pygobject or we can drop it (or, if it's possible, fix it)?

If I remember correctly it's used for the gtk2 on python 2.7 and should be built with the same compiler of the python interpreter (vs2010) so even if we get pygtk built correctly I don't know if it's usable or not.

Thoughts?

Thanks.

**Comment by TingPing** [comment]
`pygtk` is super dead, even more dead than `gtk2` itself. I don't think it should be packaged at all.

**Comment by lazka** [comment]
remove it!
