### ISSUE TITLE
linking against the glib-2.0.lib library

### ISSUE THREAD

**Issue by black13** [wingtk/gvsbuild#279]
I want to use the debug libraries in C:\gtk-build\build\Win32\debug\glib-meson\glib 
 or glib-2.0.lib in Visual Studio 2015/2017 what settings have to be defined and what headers should be included?

**Comment by nacho** [comment]
when you build the debug version, you will get the final headers, .lib and dlls in the gtk folder.

**Comment by danyeaw** [comment]
This issue is stale, if building the debug version doesn't work, please open a new issue.
