### ISSUE TITLE
use option vs-ver but still use gcc

### ISSUE THREAD

**Issue by whdxwym** [wingtk/gvsbuild#288]
I have vs and gcc installed on windows10, I use options --vs-ver and --vs-install-path to build, but it still use gcc. I want it auto disable gcc while I specified --vs-ver or --vs-install-path option.

**Comment by danyeaw** [comment]
There isn't enough information about your setup to help you troubleshoot this, and this issue is stale. Please open another issue if you are still having an issue with gvsbuild incorrectly using gcc.
