### ISSUE TITLE
libpsl issue

### ISSUE THREAD

**Issue by nacho** [wingtk/gvsbuild#299]
@guruDanny67 hey, yesterday I was fighting libpsl and one thing I saw on my system is that when it tries to run a python script from meson to generate a file it fails. Instead if I first go inside a dev-shell and then I run meson/ninja manually then it works fine. Any idea?

**Comment by guruDanny67** [comment]
Maybe you just have to add python as a dependency of the project. 
In the dev-shell ALL the tools are added to the path so you can launch cmake or go or ninja.

**Comment by nacho** [comment]
Hey @guruDanny67, you were right thanks. Adding python fixes it. I guess I was expecting that having meson as a dep that was adding python as well.
