### ISSUE TITLE
Drop the build/list command

### ISSUE THREAD

**Issue by guruDanny67** [wingtk/gvsbuild#311]
Looking at #306 to have some custom project I realize that I need to repeat the options for the build command and for the list command (say you have a custom command that builds a new or different release of some base project, gtk3 for examples).

I really don't like very much this (as a programmer I'm really lazy ...) and, in a minor way, is a problem already present (from the list command you can't see the gtk 3.22 version).

I propose to remove the build / list command: the script always builds and you can have only the list with an option (--list), list that is updated with the other options you use (gt3 version, projects presents only with the gi active, ...)

What do you think? 

Thanks in advance

**Comment by danyeaw** [comment]
I think simplifying this is a good idea 👍

**Comment by danyeaw** [comment]
Since we have updated the CLI to use Typer and added additional commands like `outdated`, I don't think this issue still applies.
