### ISSUE TITLE
Upgrading gtk to 3.24.7

### ISSUE THREAD

**Issue by behrisch** [wingtk/gvsbuild#312]
I am hunting a bug which may be related to the gtk version used so I tried to update and got the following error: NMAKE : fatal error U1073: don't know how to make 'vs14\release\Win32\bin\Gdk-3.0.gir'

The full log is here: https://ci.appveyor.com/project/behrisch/gvsbuild/builds/23113573/job/1iy7l4v328iogfwh?fullLog=true

3.24.6 shows the same error, log is here: https://ci.appveyor.com/project/behrisch/gvsbuild/builds/23451458/job/cam6jfyo2v75033x?fullLog=true

**Comment by guruDanny67** [comment]
This should be ok now, update gtk3 to 3.24.7

**Comment by behrisch** [comment]
Thank you!
