### ISSUE TITLE
libssh [failed] dowload

### ISSUE THREAD

**Issue by Voskrese** [wingtk/gvsbuild#315]
failed
https://red.libssh.org/attachments/download/218/libssh-0.7.5.tar.xz

mirror
https://www.libssh.org/files/0.7/libssh-0.7.5.tar.xz

**Comment by nacho** [comment]
Can you please create a pull request with the change?

**Comment by Voskrese** [comment]
https://github.com/wingtk/gvsbuild/pull/316
