### ISSUE TITLE
Icons are messaged up

### ISSUE THREAD

**Issue by Aphexus** [wingtk/gvsbuild#320]
When building a debug version(I haven't tried release), the icons for the app are all messed up.

Most look like a small computer screen. The interface was build using glade so I do not know what is going on. It's as if the icon enum mapping is wrong, and a default icon is being used.

Any ideas on this?

**Comment by guruDanny67** [comment]
Try with the included demo (gtk3-demo from the build dir) and see what's happening.

Maybe you're simply missing the adwaita-icon-theme and the hicolor project

**Comment by Aphexus** [comment]
None of the demos were built. do I have to build with some command line parameter? And suppose I'm missing those things you mentioned, how do I add them? (I'm very unfamiliar with gtk internals)

**Comment by guruDanny67** [comment]
When the script builds the gtk3 stack on the bin dir there will be an executable, gtk3-demo, that you can run to see if everything works as expected.
If the icons are 'wrong' try to build also adwaita-icon-theme and hicolor-icon-theme, always using the script: the icons should then be ok.
After that, for your application, you must be sure to install/use the gtk3 correctly: if you simply copy the gtk3-xxxx.dll, without all the subdirs (share, etc, ...) the library will not work 100%.

With Best Regards

**Comment by Aphexus** [comment]
Ok, I originally copied the entire dir but don't know. I'm trying to rebuild using the script but I get errors:

test-script.obj : error LNK2019: unresolved external symbol __imp_libintl_textdomain referenced in function test_script_main [D:\Projects\gvsbuild-master\build\build\x64\debug\clutter\build\win32\vs12\test-interactive-clutter.vcxproj]
test-script.obj : error LNK2019: unresolved external symbol __imp_libintl_setlocale referenced in function test_script_main [D:\Projects\gvsbuild-master\build\build\x64\debug\clutter\build\win32\vs12\test-interactive-clutter.vcxproj]
D:\Projects\gvsbuild-master\build\build\x64\debug\clutter\build\win32\vs12\Debug\x64\bin\test-interactive-clutter.exe : fatal error LNK1120: 2 unresolved externals [D:\Projects\gvsbuild-master\build\build\x64\debug\clutter\build\win32\vs12\test-interactive-clutter.vcxproj]
Traceback (most recent call last):
  File "D:\Projects\gvsbuild-master\gvsbuild\utils\builder.py", line 477, in build
    if self.__build_one(p):
  File "D:\Projects\gvsbuild-master\gvsbuild\utils\builder.py", line 599, in __build_one
    skip_deps = proj.build()
  File "D:\Projects\gvsbuild-master\gvsbuild\projects.py", line 129, in build
    self.exec_msbuild_gen(r'build\win32', 'clutter.sln')
  File "D:\Projects\gvsbuild-master\gvsbuild\utils\base_project.py", line 153, in exec_msbuild_gen
    self.exec_msbuild(cmd, configuration, add_path)
  File "D:\Projects\gvsbuild-master\gvsbuild\utils\base_project.py", line 113, in exec_msbuild
    self.exec_vs('msbuild ' + cmd + ' /p:Configuration=' + configuration + ' %(msbuild_opts)s', add_path=add_path)
  File "D:\Projects\gvsbuild-master\gvsbuild\utils\base_project.py", line 108, in exec_vs
    self.builder.exec_vs(cmd, working_dir=self._get_working_dir(), add_path=add_path)
  File "D:\Projects\gvsbuild-master\gvsbuild\utils\builder.py", line 839, in exec_vs
    self.__execute(self.__sub_vars(cmd), working_dir=working_dir, add_path=add_path, env=self.vs_env)
  File "D:\Projects\gvsbuild-master\gvsbuild\utils\builder.py", line 879, in __execute

.\build.py -p x64 -c debug --build-dir D:\Projects\gvsbuild-master\build build gtk3-full

I was able to build this previously with a different command line. It seems though that the dll's were built.

**Comment by Aphexus** [comment]
Using that build there was gtk-demo and some of them worked but some crashed... I think because some of the demo's failed. Specifically the tool palette crashed. Most of the others seem to work fine.

**Comment by Zueuk** [comment]
Not sure if related, but I'm trying to compile a GTK app for Windows here, and while most icons are fine (if I copy them from the GTK folder into a local /share/icons), the most basic icons are somehow missing - like the triangles/arrows on the menu tool buttons.
![image](https://user-images.githubusercontent.com/5717247/104322195-b5dfdd00-54f5-11eb-8043-b48ed7fc7b04.png)
The rotating spinner icon appears to be missing too.

I suspect there might be something missing in my GTK configuration on Windows, any advice?
Both my exe and GTK (gvsbuild) is built using MSVC 2017

**Comment by danyeaw** [comment]
This issue is stale so I am closing.
