### ISSUE TITLE
CI: switch to azure pipelines

### ISSUE THREAD

**Issue by lazka** [wingtk/gvsbuild#328]
They have VS 2015/2017/2019 images and 10 parallel builds: https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops#use-a-microsoft-hosted-agent

If someone thinks this would be useful I can look into it.

**Comment by guruDanny67** [comment]
If we can make the build faster I think it's ok to look and see if the improvement is worth the job: actually, one platform/version take 35/45 minutes to build on the actual ci so there is room to improve.

So +1 from me.

**Comment by lazka** [comment]
I've started something in https://github.com/wingtk/gvsbuild/tree/azure-ci but it always gets stuck downloading pango, so I've given up for now.

**Comment by lazka** [comment]
I've pushed something to master. The complete CI time is now around 40 minutes.

**Comment by lazka** [comment]
I've removed appveyor now

**Comment by lazka** [comment]
I just got an email from azure that they are going to remove the support for the vs2015 image next month. Bad timing, I hope that's not that big of a problem.

**Comment by nacho** [comment]
Thanks for letting us know.

**Comment by lazka** [comment]
The jobs started failing now because of this. I've removed them in 593caa785
