### ISSUE TITLE
Build failure : unresolved symbol 

### ISSUE THREAD

**Issue by boxerab** [wingtk/gvsbuild#335]
Environment:
Windows 10
VS 2017
Python 3.6.2
No `PKG_CONFIG_PATH` is set.

Command:

`python .\build.py build @vs2015-release.pro -p x64 gtk3-full`

where the `.pro` file sets the VS version, SDK version, and release build.

Error:
```
FAILED: gio/gio-2.0-0.dll
link @gio/gio-2.0-0.dll.rsp
   Creating library gio\\gio-2.0.lib and object gio\\gio-2.0.exp
gsettingsschema.c.obj : error LNK2019: unresolved external symbol __imp_g_libintl_bind_textdomain_codeset referenced in function g_settings_schema_source_lookup
gio/gio-2.0-0.dll : fatal error LNK1120: 1 unresolved externals
[771/960] Linking target glib/tests/testing.exe.
```

**Comment by guruDanny67** [comment]
Actually the gtk3-full roup builds with vs2015 end 2017 in win32 & x64 mode, aslo in the ci, so this should be something on your side.

Have you tried to use the --from-scratch to have a clean build ?

Try also to use the last version of the script.
