### ISSUE TITLE
Buttons stop being clickable

### ISSUE THREAD

**Issue by Adriatic1** [wingtk/gvsbuild#337]
Hi,
I've been keeping a GTK 3.x build of my program in beta due to this problem:
sometimes (most of the time), the buttons on a popup window are not being clickable with mouse (for example "OK" or "x"). Using Tab key to set focus on them and then pressing Enter to activate them works OK. 
Even more strange, using mouse to click on "OK" button toggles the state of check box placed above it. It looks as if some calculation of x,y mouse pointer coordinates is messed related to some offset (but button hover effects when pointer is over it work OK).

Note that all other GTK 3.x build for other platforms (different Linux distros) do not have this problem at all. The code for this dialog is standard, same code works fine in GTK2.x for years.

Any idea what might happen here? Is there any Windows-specific patch applied in gvsbuild that might cause something like this ? Or some GTK locking issue (I use gdk_threads_enter() only in builds older than GTK3.6.0 though) ?

If you want to give it a try, you can download GTK3 build from this page:
https://www.notecasepro.com/download.php
(click on a Windows tab and download the beta build at the bottom).
After opening program (in trial mode) you can add a new note to the tree view at the right side using "Ins" key. When trying to delete the same note with "Del" key, the dialog pops up that exhibits the described issue.

Any comments are welcome, I am puzzled by this.
Let me know if you need more info.

Regards,
  Miroslav

**Comment by Adriatic1** [comment]
For more info, the beta build I mentioned uses gvsbuild of GTK 3.24.8.

**Comment by danyeaw** [comment]
This issue is stale and it looks like you are using mingw for your build now.

**Comment by Adriatic1** [comment]
I've finally revisited the issue and found the minimal example that demonstrates the problem (see below).

Note that code below may not be correct in terms of correctly exiting the program, but it shows the issue itself.
If I comment the "**gdk_window_set_decorations**" line, everything works OK. With this line included, I cannot click the "OK" button anymore.
This is ancient code that worked fine ever since GTK 2.x on all platforms (including old GTK 2.x binaries for Windows by Tor Lillqvist), now works fine in GTK 3.x on Linux, Windows Mingw, macOS, BSD, ..., i.e. everywhere except in gsvbuild (tested on recent gsvbuild).
Knowing the root case, I now have a workaround (comment this line in all the dialogs I have), but it would be nice to fix the issue as well. 

#include <gtk/gtk.h>

int gtkMessageBox(const char* szText)
{
    GtkWidget* msgbox = gtk_dialog_new();
    
    gtk_window_set_title(GTK_WINDOW(msgbox), "Info");
    gtk_window_set_modal(GTK_WINDOW(msgbox), TRUE);
    
    g_signal_connect(msgbox, "destroy", G_CALLBACK(gtk_main_quit), nullptr);
 
    gtk_window_set_type_hint(GTK_WINDOW(msgbox), GDK_WINDOW_TYPE_HINT_DIALOG);
    gtk_window_set_skip_taskbar_hint(GTK_WINDOW(msgbox), TRUE);
    gtk_window_set_resizable(GTK_WINDOW(msgbox), FALSE);
    gtk_widget_realize(msgbox);
    **// NOTE: commenting line below makes the issue dissapear
    gdk_window_set_decorations(gtk_widget_get_window(msgbox), (GdkWMDecoration)(GDK_DECOR_BORDER | GDK_DECOR_TITLE));**
    gtk_window_set_position(GTK_WINDOW(msgbox), GTK_WIN_POS_CENTER);

    GtkWidget* dialog_vbox3 = gtk_dialog_get_content_area(GTK_DIALOG(msgbox));
    gtk_widget_show(dialog_vbox3);
    gtk_container_set_border_width(GTK_CONTAINER(dialog_vbox3), 7);
    gtk_box_set_spacing(GTK_BOX(dialog_vbox3), 10);

    GtkWidget* label21 = gtk_label_new(szText);
    gtk_label_set_selectable(GTK_LABEL(label21), TRUE); // user must be able to copy an error message
    gtk_widget_show(label21);
    gtk_box_pack_start(GTK_BOX(dialog_vbox3), label21, TRUE, TRUE, 0);

    gtk_dialog_add_button(GTK_DIALOG(msgbox), GTK_STOCK_OK, GTK_RESPONSE_OK);

    gtk_widget_grab_focus(msgbox);
    const gint result = gtk_dialog_run(GTK_DIALOG(msgbox));
    gtk_widget_destroy(msgbox);
    return result;
}

int main(int argc, char* argv[])
{
    gtk_init_check(&argc, &argv);
    gtkMessageBox("test message!");
    gtk_main();
    return 0;
}

#ifdef _WIN32

#include <windows.h>
#ifdef _MSC_VER
int WINAPI WinMain(__in HINSTANCE /*hInstance*/, __in_opt HINSTANCE /*hPrevInstance*/, __in LPSTR /*lpCmdLine*/, __in int /*nCmdShow*/)
#else
int WINAPI WinMain(HINSTANCE /*hInstance*/, HINSTANCE /*hPrevInstance*/, LPSTR /*lpCmdLine*/, int /*nShowCmd*/)
#endif
{
    return main(__argc, __argv);
}

#endif  // _WIN32

**Comment by danyeaw** [comment]
@Adriatic1 Do you think this is an upstream issue with GTK3?

Is there a reason you aren't using gtk_window_set_decorated instead of calling the GDK method directly?

**Comment by Adriatic1** [comment]
No idea on upstream (could be), but it is peculiar that the issue is visible only on gvsbuild.
Note that my project dates back to year 2004, so it's hard to know why I chose this code at the time.
The fact that it worked before makes it likely that some change in GTK introdced the breakage.

Replacing the offending line with "gtk_window_set_decorated(GTK_WINDOW(msgbox), TRUE);" makes the issue go away.
