### ISSUE TITLE
Another CMD issue

### ISSUE THREAD

**Issue by gvanem** [wingtk/gvsbuild#348]
I just did a `cmd /c py.exe -3 build.py  build --no-deps glib`, and got this from `CMD`:
```
Cleaning up the build environment
Checking msys tool
Checking Msvc tool
'vswhere.exe -property catalog_productSemanticVersion -path "f:\gv\vc_2019\Common7\Tools\VsDevCmd.bat"' is not recognized as an internal or external command,
operable program or batch file.
```
and:
```
'dir "f:\gv\vc_2019\Common7\Tools\vsdevcmd\ext\*.bat" /b /a-d-h /on' is not 
recognized as an internal or external command, operable program or batch file.
...
```

If I do the `vswhere` from my 4NT prompt, it works just fine and dandy.
Those errors seems to stem from inside `VsDevCmd.bat` though.
What could the problem?

**Comment by guruDanny67** [comment]
Try to pass the version & base directory of your visual studio installation to the script. 

The script finds it automatically only if it's installed in the standard directory, sorry.

**Comment by gvanem** [comment]
Huh! A more exact patch please.

**Comment by gvanem** [comment]
I just stumbled across this method to get a GTK+; `vcpkg install gtk:x86-windows`. Works like a charm!
Bye, bye, pacman!
