### ISSUE TITLE
Update to latest gtk 3.24.16 issue.

### ISSUE THREAD

**Issue by mhertz** [wingtk/gvsbuild#349]
I wanted to update gvsbuild to build newest gtk3 and so replicated last gtk3 update commit i.e. edited with new download-link and hash in gvsbuild/project.py, but am getting some errors which I posted here underneath. Googling them doesn't give me any help on it and I see no issues here neither regarding it, so would much appreciate any pointers regarding this please. The unmodified gvsbuld with gtk 3.24.14 builds fine using VC-2017 on win10.

Sorry I know this of-course isn't exactly supported behaviour I'd guess, and possibly need some patch(es) added which the devs will get to when adding official support, but just thought i'd ask here for help regardless and hope it's OK :) Thanks alot in advance!
```
Building project gtk3 (3.24.16)
Debug: directory C:\gtk-build\build\x64\release\gtk3-24 already exists
(tar) Updating C:\builds\gtk3build\DOWNLOADS\gtk+-3.24.16.tar.xz
Debug: patch gtk_update_icon_cache.patch already applied, skipping
Debug: running ninja install, cwd=C:\gtk-build\build\x64\release\gtk3-24-meson, path+=None
[5/468] Compiling C object gtk/89afd8d@@gtk-3@sha/gtkcolorpickerportal.c.obj.
FAILED: gtk/89afd8d@@gtk-3@sha/gtkcolorpickerportal.c.obj
cl @gtk/89afd8d@@gtk-3@sha/gtkcolorpickerportal.c.obj.rsp
../gtk3-24/gtk/gtkcolorpickerportal.c(52): error C2065: 'g_autofree': undeclared identifier
../gtk3-24/gtk/gtkcolorpickerportal.c(52): error C2143: syntax error: missing ';' before 'type'
../gtk3-24/gtk/gtkcolorpickerportal.c(53): error C4013: 'g_autoptr' undefined; assuming extern returning int
../gtk3-24/gtk/gtkcolorpickerportal.c(53): error C2275: 'GVariant': illegal use of this type as an expression
C:\gtk-build\gtk\x64\release\include\glib-2.0\glib/gvariant.h(34): note: see declaration of 'GVariant'
../gtk3-24/gtk/gtkcolorpickerportal.c(53): error C2146: syntax error: missing ';' before identifier 'ret'
../gtk3-24/gtk/gtkcolorpickerportal.c(53): error C2065: 'ret': undeclared identifier
../gtk3-24/gtk/gtkcolorpickerportal.c(53): error C4047: '=': 'int' differs in levels of indirection from 'void *'
../gtk3-24/gtk/gtkcolorpickerportal.c(82): error C2065: 'ret': undeclared identifier
../gtk3-24/gtk/gtkcolorpickerportal.c(82): error C4047: '=': 'int' differs in levels of indirection from 'GVariant *'
../gtk3-24/gtk/gtkcolorpickerportal.c(83): error C2065: 'ret': undeclared identifier
../gtk3-24/gtk/gtkcolorpickerportal.c(84): error C2065: 'ret': undeclared identifier
../gtk3-24/gtk/gtkcolorpickerportal.c(84): error C4047: 'function': 'GVariant *' differs in levels of indirection from 'int'
../gtk3-24/gtk/gtkcolorpickerportal.c(84): warning C4024: 'g_variant_get_uint32': different types for formal and actual parameter 1
[7/468] Compiling C object gtk/89afd8d@@gtk-3@sha/gtkcombobox.c.obj.
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 478, in build
    if self.__build_one(p):
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 602, in __build_one
    skip_deps = proj.build()
  File "C:\gtk-build\github\gvsbuild\gvsbuild\projects.py", line 848, in build
    Meson.build(self, meson_params='-Dtests=false -Ddemos=false -Dexamples=false')
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\base_builders.py", line 80, in build
    self.builder.exec_ninja(params='install', working_dir=ninja_build)
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 879, in exec_ninja
    self.__execute(self.__sub_vars(cmd), working_dir=working_dir, add_path=add_path, env=self.vs_env)
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 908, in __execute
    subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
  File "C:\Python\Python37\lib\subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'ninja install' returned non-zero exit status 1.
* Removing gtk3 dependents ...
```
(I had to rerun script to see/obtain relevant error output, as console-buffer wasen't big enough(by default) to pick up the errors, and the text-file log generated automatically, doesn't contain enough info, just a single line stating a ninja fail, listed there.)

**Comment by guruDanny67** [comment]
try to launch the script with

 [your options ...] --clean-built gtk3 

so it cleans (only) the gtk3 directory before extracting & building the library: sometime is enough to build correctly.
If you have time you can also put --from-scratch that starts from the void, erasing everything.
For the log I'm working on a patch to capture the output and put it in the log file, as soon I have a moment I try to put it upstream because is really useful: you launch the script, go to eat & drink something and when you return you have the log. 
All my command prompt have 9999 lines of screen buffer (the maximum windows allows) to cope with the long output.

**Comment by mhertz** [comment]
Thanks alot for your reply and help guruDanny67, much appreciated!

Sorry for being not fully clear possibly, but gvsbuild fails for me also with a completely clean and fresh build when having changed two lines in gvsbuild/project.py in regards to new link and hash of newest released gtk3 stable version(3.24.16), instead of the little older(3.24.14) used by default.

Thanks for the tricks with build-options that is handy and the patch you're working on for capturing full command-output to text-file is indeed a nice improvement coming in handy for many and often i'm sure.

Anyway, I was gonna look into changing default buffer in cmd-prompt, but as you stated only 1000'ish lines was allowed adding ontop of default so 9999 as you stated(instead of default 9001), which I added in settings and default setings too. I then ran completely clean/fresh(except for new gtk3 change) for full obtained logging and the buffer was way to small to capture it still, once again. 

I could then choose to select only clean-building gtk3 as you stated, but got fed up with cmd-prompt and it's low cap on max buffer size, and instead changed over to an alternative I remember reading about conemu, with a default(and max) of 32766, though that still wasen't enough for full output, but was enough for the specific gtk3 related part, so I have linked to a pastebin of that part below. I also had selected initially in conemu settings, that it by default should save command-output(scrollback-buffer) into text-file, and that did capture everything from start to finish, so I also uploaded the big almost 4mb text-file with the full log, just in case too, which can be searched through or whatnot, though it was to big for pastebin's free service, so had to use alternative file-hosting site instead for that.

Again, any tips on how to approach this, if possible, would be highly appreciated, and many thanks in advance.

gtk-3.24.16-only.txt: (only the gtk3 building part)
https://pastebin.com/7QcvJ6yD

gtk-3.24.16-full.txt: (full log of complete run)
https://gofile.io/?c=daYX1f

**Comment by guruDanny67** [comment]
Even the gtk 3.24.15 fails. 

The problem is in gtkcolorpickerportal.c that use some GCC/clang macro to help manage the resource (g_autofree & g_autoptr) that are not supported on windows.

I found this that say not to use it but maybe it's not true anymore: 
https://gitlab.gnome.org/GNOME/glib/commit/07731ff3fc6ede1155a690d71b8ae2caedf680ba 

This thing should be reported upstream, to the gtk3 team

**Comment by mhertz** [comment]
Thanks once again Danny for your help and expertise, truly appreciated!

Well, atleast I know it's not me doing something wrong then :) 

If anybody at some point ever find/make a patch for this, or instructions for manually fixing this issue, then it would be very much appreciated. If I could, I'd obviously do it myself and post here for others to use too.

**Comment by mhertz** [comment]
For anybody interested, then those functions where added for convenience 9 days ago in gtk3.24 branch, and then removed 2 days ago here, so little after 3.24.16 unfortunetly: https://github.com/GNOME/gtk/commit/fa16b682ef12a401b152f361b3cef7392619cdae

I'll revert those changes tomorrow and see if it hopefully resolves the issue and report back later, and thanks again Danny.

**Comment by mhertz** [comment]
I have tested that it works correctly now, so once again thank you very much for the help Danny, much appreciated!

Patches needed:

gtkcolorpickerportal.c patch:
https://github.com/GNOME/gtk/commit/fa16b682ef12a401b152f361b3cef7392619cdae.patch

gtkprivate.c patch:
https://github.com/GNOME/gtk/commit/8dfb1d197ae75c9a435e7e063e1cec96b141a301.patch

projects.py patch:
https://pastebin.com/aACeSWSV

Alternativelly, here's a single patch that does everything above i.e. patches gvsbuild/projects.py with new download-link, hash and patches to add, and then generates the two patches needed under the patches/gtk3-24 folder for gtkcolorpickerportal.c and gtkprivate.c. These two patches generated(and linked above), are official commits from gtk3's gtk-3-24 branch from 2 days ago, so a couple days after 3.24.16 was released, and so will be in next gtk3 release then, unless reverted for some reason.

gtk-3.24.16.patch
https://pastebin.com/T5Qrdq57

Sometimes, i've witnessed pastebin screwing with files pasted in and making them fail when used, so alternatively are here other filehosting links for the two pastebins, but gets inactive after 30 days without download or something like that, so if link dies later then let me know.

projects.patch
http://s000.tinyupload.com/index.php?file_id=89986331912593624793

gtk-3.24.16.patch:
http://s000.tinyupload.com/index.php?file_id=22700698288804480556

Thanks again to Danny and to everyone involved with gvsbuild, past and present, your efforts are truly appreciated!

**Comment by mhertz** [comment]
Just wanted to add that yesterdays gtk 3.24.17 release has these two previously mentioned needed commits included, and so now only the usual change to gvsbuild\projects.py needed if wanting newest gtk3 built i.e. as of today v3.24.17.

Here's patch for that:
https://pastebin.com/tGFeEnQ2

And as before, using other file-hosting just in case pasting-issues had occured:
http://s000.tinyupload.com/index.php?file_id=45493304813820479068

If deemed appropriate, then this post can be closed of-course. I'd rather leave it up to you guys to decide that :) Thanks again!

**Comment by guruDanny67** [comment]
Can you made a pull request so we can merge the modification (with your name)? 

After all your work I think you deserve it :)

**Comment by mhertz** [comment]
Thank you Danny, that is very nice of you and I appreciate that. Btw, looking forward to now utilizing your newly added logfile redirection/forwarding option, letting me to not anymore needing keep conemu or alike around, just for gvsbuild alone. Thanks again for everything mate, much appreciated!
