### ISSUE TITLE
Python 3.8.2 issues.

### ISSUE THREAD

**Issue by mhertz** [wingtk/gvsbuild#350]
I'm trying to get gvsbuild to build using latest python 3.8.2 instead of my previously used 3.7.7 that tworked fine. I got most fixed myself, but got one nagging issue still lingering i'm completely lost about.

Firstly, to even get gvsbuild to run properly without error'ing out during downloading packages, then I made this patch:
https://pastebin.com/G2fakqx0

Then gobject-introspection failed during trying to generate gir file, so found newer upstream commit fixing it and added as patch:
https://pastebin.com/jyGYe7wJ

Though as newer release with said commit included was released than the one currently used by gvsbuild, then alternatively, and probably better way, to simply upgrade to newest gobject-introspection instead:
https://pastebin.com/mTuPfKap

Okay now comes my last nagging issue I cannot fix. I update in gvsbuild\projects.py to build latest gtk 3.24.17, as posted ticket and patch about previously here. I then specify to build gtk, gtk-3.24, pycairo and pygobject and to make wheels and eggs of last two, and it's here the issue comes. Everything is fine, except pygobject fails building as only thing, because at a point needs import cairo(or _cairo), and fails. I then tried manually importing cairo(or _cairo), and it also fails with dll import error. When checking under my python site-packages\cairo* folder, then there is the pyd, but no cairo.dll(or _cairo.dll). If using py3.77 instead of py3.82, then this doesn't happen and there is cairo.dll(or _cairo.dll, can't remember). I found on 3'rd part site for whl's, an py3.8 whl version of pycairo latest version, so little newer than used from gvsbuild, and that had the dll in there, and when installing that package from pip from that whl I downloaded, and then build pygobject again using py3.82, then it builds without error. I then upgraded gvsbuild\projects.py to build same newest pycairo as the working one I downloaded, and same error happens during pygobject trying import cairo and no dll. There is though a file there isn't in the downloaded version, or the version when using py3.77, and that is _cairo.py, so for some reason then the dll is not built and instead left a py file. There are no error in output except the failing error from pygobject of failing because cannot import cairo or _cairo. There where some py3.8 commits for windows added for pycairo, but I used latest version released which should include all those commits.

Here's the patch I used containing the later two posted patches above, including updated to latest gtk3-24, pycairo and pygobject, which I hoped would fix the pycario issue with the update to newest version but exact same issue unfortunetly:
https://pastebin.com/aMyV9VW5

Here's a full log of completely clean run, with above patch applied, using py3.82 and msvc 2017 on win10, and catching the whole complete output using conemu and it's setting to catch everything to file automatically, as even max of 32766 scroll-back buffer isn't enough:
http://s000.tinyupload.com/index.php?file_id=27522742211987417674

Finally, i'm thinking that this is an issue in gvsbuild, because there is a downloadable wheel for pycairo latest version for py38 as stated, and also the changelog for that package states a couple of py38 and windows fixes already made and included, so should be compatible now from sound of it. There is no pygobject wheel from net for py38, hence I need to get this to work if possible + I wanna change in generel to latest python version for other stuff too, including gvsbuild if possible.

Thanks alot in advance!

**Comment by guruDanny67** [comment]
Some times ago I try to use python 3.8 (as soon as it was released) but I had some problem on building the .egg files (we can use the 3.8 for the build without problems).

The reason is a change in the way the python executable loads the DLL from the extensions: now you have to be explicit on which directories to look for them, using add_dll_directory(...) while before (3.7) the DLL are looked in the system path so, having our bin dir in the path was enough to load the cairo DLL used to build the pygobject .egg and to run all the gtk3 stack from python so I say to myself to wait if something is done on the pycairo/pygobject side about this.

I take a rapid look at the commit in the pycairo repository and they put some fixes but I don't know if everything is ok.

I think the correct strategy is to update pycairo & pygobject at the last version upstream, using python 3.7 to build so we have one problem to solve.

When we have the updated projects we can then try with python 3.8 and fix what's wrong.

**Comment by guruDanny67** [comment]
In the upstream version, there are the updated projects for pycairo, pygobject & gobject introspection.

To build for python 3.8 pass --python-ver 3.8.2 to the script and rebuild all: enjoy :)

I had to patch pycairo & pygobject to load the extensions (the add_dll_directory(...) stuff): before launching the python interpreter that uses the gtk stack the built directory bin must be on the path, like before (e.g. set PATH=c:\gtk-build\gtk\win32\release\bin;%PATH%)

**Comment by mhertz** [comment]
Wow, you sir are indeed awesome! :) Thanks alot! I'm so glad I refreshed the page so as to avoid spend hours on a wasted effort, since I just tested the lazka hack to __init__.py to get old behaviour back(add PATH entries into seperate os.dll_add_directory() calls), and when added to pycairo's __init__.py, then I could finally import cairo, so I was just about to make patches for pycairo and pygobject to add those hacks, and first see that working, before trying to see if I could somehow instead find out how to use the more correct method you did of using os.add_dll_directory for specific bin dir of PATH, but looking at what you did, i'm sure I atleast couldn't as elegant as you for sure, if at all even. Btw, I haven't had time to run it yet and will do first tomorow, but you didn't run into the issue of the first patch I posted, where splittype couldn't be imported, because needs to be _splittype, in two places of builder.py? During downloading missing packages I mean. Sorry if i'm missing something, which is most likely :) Anyway, I of-course shouldn't speak before having tested it, but just a quick thought as couldn't see it in your commits. Thank you again very much for your great work, really much appreciated!

**Comment by guruDanny67** [comment]
I don't have the splittype issue but this can be because I have a lot of tarballs already downloaded.
And for the build script, I use always an embedded python 3.7.3 I installed in c:\gtk-build\python, letting the script download the new pythons to use for the build.

**Comment by guruDanny67** [comment]
Found! 

Bad news: it's a problem in python 3.8

Good news: we don't use the function (now) so we can drop the two lines using splittype.

**Comment by mhertz** [comment]
Awesome, then I'll close this ticket now since issue non existing anymore thanks to your great work so again thanks alot mate!
