### ISSUE TITLE
gettext: link error

### ISSUE THREAD

**Issue by japm48** [wingtk/gvsbuild#354]
I am getting this error: 

    glib-2.0.lib(glib-2.dll) : error LNK2005: g_log already defined in glib-2.0.lib(glib-2.dll)
    glib-2.0.lib(glib-2.dll) : error LNK2005: g_printerr already defined in glib-2.0.lib(glib-2.dll)
    ...
    vs16\Release\x64\bin\gettextlib.dll : fatal error LNK1169: one or more multiply defined symbols found

While compiling with VS2019. The project name is `gettextlib`, I don't have any idea how to solve it.

**Comment by guruDanny67** [comment]
gettext doesn't depend on glib so this should not happen. Try to build only the gettext project, starting from scratch, e.g. 
[your build command ... options] --clean gettext

Apart from the tools the script should build only win-iconv & gettext

**Comment by japm48** [comment]
In the end, it was my fault. I had to disable vcpkg integration to get it working.

For the record: I was referring to the `gettextlib` VS project (`.vcxproj`) being built inside the `gettext` VS solution (`.sln`), but now everything compiles correctly.

Thanks!

**Comment by homandiy** [comment]
Same here, I've same error with VS2019+VS2017 build tool. "--clean gettext" is not working.
