### ISSUE TITLE
can you add gst-python as a project?

### ISSUE THREAD

**Issue by tjwilli58** [wingtk/gvsbuild#359]
Can you add gst-python as a project please? 
What is the procedure for doing this?
Thanks.

**Comment by nacho** [comment]
you can create a pull request modifying the gvsbuild/projects.py

**Comment by tjwilli58** [comment]
I'll fork this and give it a shot. Thanks. 
Is it only projects.py that needs modifying?

**Comment by nacho** [comment]
Just projects.py should be enough I hope :)

**Comment by tjwilli58** [comment]
Created #360

**Comment by tjwilli58** [comment]
I thought I closed this, but I guess it was just the PR.
