### ISSUE TITLE
Where are the pre-built binaries?

### ISSUE THREAD

**Issue by theAkito** [wingtk/gvsbuild#377]
I found [this](https://ci.appveyor.com/project/cas--/gvsbuild/build/artifacts), but, as can be seen, the binary has been already deleted. Where is the up to date CD location, where the binaries are already built and ready to use?

Setting up an entire development environment for a single package seems a bit of a stretch to a user that only needs the binary.

**Comment by lazka** [comment]
https://dev.azure.com/lazka/gvsbuild/_build/results?buildId=310&view=artifacts&type=publishedArtifacts
