### ISSUE TITLE
Add support for build on x86 CPU

### ISSUE THREAD

**Issue by EtianAM** [wingtk/gvsbuild#390]
Only that; it is possible to compile it in x86, but it is necessary to specify that it does not look for VS in "C:\Program Files x86..."(In 32-bit Win, it only exists as ProgramFiles) in addition to downloading CMake for x86, nasm for x86 and ninja for x86 (Actually it is not for x86 version, it is necessary to compile it, but it is compiled with VS easily and quickly)
I think that's all that needs to be changed/improved.

**Comment by mhertz** [comment]
Humble bump for if possible, this could be looked into, thanks. Or get clarification from devs about if this isn't something they wan't persuing.

I used the --platform=x86 switch which works for building 32 bit gtk3 stack on a x64 system, but I now tested building on a 32bit system, and fails currently, and log states downloading e.g. 64 versions of cmake, perl, yasm and go, and using 64 bit ninja too, I think, as EtianAM above stated. 

Thanks in advance.

**Comment by guruDanny67** [comment]
Fast answer: a lot of PC are 64 bit so it's easier to keep and maintain
only one series of tools and use the ones that will be updated (some
software I use at work are updated only for the 64 bit version, say the
eclipse platform).

Stated that you can build 32-bit software with the 64-bit tools it's
easier. Look at #107 for a longer description.

With best regards
    Daniele Forghieri

Il giorno gio 22 ott 2020 alle ore 13:58 Martin Hertz <
notifications@github.com> ha scritto:

**Comment by mhertz** [comment]
Thanks as usual for your help Danny, much appreciated.
