### ISSUE TITLE
Enhancement: MSVC Whole Program Optimizaiton

### ISSUE THREAD

**Issue by petersasi** [wingtk/gvsbuild#395]
Hi, 
I am wondering if in the past you ever considered /GL for compilations and /LTCG for linking to enable MSVC Whole Program Optimization that is supposed to be similat optimization to gcc's LTO?
My knowledge of the build system is very far from being able to do this myself, but if you give me pointers on where to add these I can give it a spin to see if it works.
As a first step: does the whole system all projects use meson and ninja?

**Comment by guruDanny67** [comment]
Each project uses its way of building: the gtk stack is moving to use meson with ninja, some other uses CMake (now with ninja), some other the Visual Studio solution and the MsBuild.exe, some Microsoft nmake with custom makefiles, and of some project I don't yet understand how :(

You should check on the singles projects to see if they already have tried something or see, in the meson/cmake/makefile, if there is something related.

With best regards

**Comment by petersasi** [comment]
Okay, then I will try it on a single project first and reopen this after I succeed there.
