### ISSUE TITLE
Building libpng fails

### ISSUE THREAD

**Issue by martinfischer8** [wingtk/gvsbuild#397]
Running gvsbuild with settings:

    Configuration: release
         Platform: x86
          Vs ver: 15
          Vs path: None
          Sdk ver: None

building libpng fails with the following messages:
pngrutil.c.obj : error LNK2019: unresolved external symbol _inflateReset2 referenced in function _png_inflate_claim
pngrutil.c.obj : error LNK2019: unresolved external symbol _inflateValidate referenced in function _png_inflate_claim

There are some reports for exact the same problem in Linux, eg. https://github.com/glennrp/libpng/issues/292 which indicate that this is a compatibility problem between zlib 1.2.11 and libpng 1.6.37

As there are no previous reports on this here I assume there must be a workaround available. 

So what can I do?

**Comment by guruDanny67** [comment]
You probably have some old zlib liying around that's used instead of the one from the script.
Try to build libpng with --clean option to be sure to start from scratch

With best regards

**Comment by martinfischer8** [comment]
Thanks, a closer search revealed another zlib. 

Regards
Martin
