### ISSUE TITLE
Replacement for PyGObject for Windows

### ISSUE THREAD

**Issue by abitrolly** [wingtk/gvsbuild#400]
Some Python GTK projects are stuck with now abandoned https://sourceforge.net/projects/pygobjectwin32/ which is Python 3.4 only. Maybe somebody can write a tutorial how to replace `pygi-aio.exe` with binaries produced by this project.

It might be then used as an alternative way of [using GTK and Python on Windows](https://pygobject.readthedocs.io/en/latest/getting_started.html#windows-getting-started).

**Comment by TingPing** [comment]
The upstream PyGObject supports Windows and is packaged here already: https://github.com/wingtk/gvsbuild/blob/master/gvsbuild/projects.py#L1881-L1892

**Comment by TingPing** [comment]
As for documentation maybe that belongs with the pygobject project itself.

**Comment by abitrolly** [comment]
@TingPing once it is clear how to use the binaries, it is possible to submit documentation upstream. However, I don't see anything installable for Python in Azure artifacts.
```
➜  gvsbuild-vs16-x64 fd py
share/doc/gettext/COPYING
share/doc/glib/COPYING
share/doc/pkgconf/COPYING
share/doc/win-iconv/COPYING
share/glib-2.0/codegen/__init__.py
share/glib-2.0/codegen/codegen.py
share/glib-2.0/codegen/codegen_docbook.py
share/glib-2.0/codegen/codegen_main.py
share/glib-2.0/codegen/config.py
share/glib-2.0/codegen/dbustypes.py
share/glib-2.0/codegen/parser.py
share/glib-2.0/codegen/utils.py
share/glib-2.0/gdb/glib_gdb.py
share/glib-2.0/gdb/gobject_gdb.py
```

**Comment by TingPing** [comment]
Thats fair, this is tracked in #145
