### ISSUE TITLE
fontconfig and pango recent commits make building them fail.

### ISSUE THREAD

**Issue by mhertz** [wingtk/gvsbuild#402]
On win10 with msvc 2019(14.27), py3.9 and a x64 build, the recent 2 commits for updating fontconfig and pango makes building these project fail for me, and works again after reverting them back. A file is not found in both cases I see.

First log is fontconfig build failing and second log is pango build failing, where I had reverted the fontconfig commit first, as is a dep to pango.

Let me know if you need more info or if I can do some testing on my end to help troubleshoot this.

Thanks in advance.

fontconfig: https://paste.c-net.org/BowlingUniquely
pango: https://paste.c-net.org/VitalsFlyer

**Comment by nacho** [comment]
thanks!

**Comment by nacho** [comment]
I reverted fontconfig. Can you try to change pango to version 1.46.x and see if that one works?

**Comment by mhertz** [comment]
Thank you!

Unfortunetly none of the three 1.46.x versions work - in testings, I reverted the 'enabled/disabled' to booleans and didn't re-add the old patch as unneeded I believe(in addition to the link and hash-changes obviously).

Please let me know if can do something to help test.

Thanks again.

1.46.2: http://paste.c-net.org/CountingFreeman
1.46.1: http://paste.c-net.org/AlexiUgliest
1.46.0: http://paste.c-net.org/TakerHeadway

**Comment by mhertz** [comment]
Just did new run test-run today after some time, and everything builds perfectly now without errors - tested using latest stable python 3.9.1 and msvc-2019! Great job as always guys, much appreciated! :)
