### ISSUE TITLE
gettext.sln not found for VS2019

### ISSUE THREAD

**Issue by JasonLCY3** [wingtk/gvsbuild#404]
```
Building project gettext (0.19.7)
Checking for 'C:\gtk-build\build\Win32\release\gettext\build\win32\vs19\gettext.sln'
Checking for 'C:\gtk-build\build\Win32\release\gettext\build\win32\ms-cl-19\gettext.sln'
Error: Solution file 'gettext.sln' for project 'gettext' not found!
Traceback (most recent call last):
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 492, in build
    if self.__build_one(p):
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 618, in __build_one
    skip_deps = proj.build()
  File "C:\gtk-build\github\gvsbuild\gvsbuild\projects.py", line 471, in build
    self.exec_msbuild_gen(r'build\win32', 'gettext.sln')
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\base_project.py", line 230, in exec_msbuild_gen
    log.error_exit("Solution file '%s' for project '%s' not found!" % (sln_file, self.name, ))
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\simple_ui.py", line 271, in error_exit
    sys.exit(1)
SystemExit: 1
Error: gettext build failed
```

**Comment by PeterLeipe** [comment]
How have you solved this issue?

**Comment by guruDanny67** [comment]
This issue, imho, is caused by an error in the script's parameter: probably the option --vs-ver is set to 19 (instead of 16, the correct value for vs2019) and so the script cannot found or create the solution.

**Comment by PeterLeipe** [comment]
> This issue, imho, is caused by an error in the script's parameter: probably the option --vs-ver is set to 19 (instead of 16, the correct value for vs2019) and so the script cannot found or create the solution.

Thanks, quite confusing, is it mentioned somewhere?

**Comment by guruDanny67** [comment]
Yes,, a lot confusing.

Launching the script with the help parameter (python build.py build -h)
should give you some info.

The vs2013 is version 12 (runtime v120), the 2015 is version 14 (runtime
v140), the 2017 in version 15 (runtime v141) and the 2019 is version 16
(runtime v142).

With best regards

Il ven 9 apr 2021, 00:56 PeterLeipe ***@***.***> ha scritto:
