### ISSUE TITLE
Building fails on Visual Studio 2019

### ISSUE THREAD

**Issue by NeoInversion** [wingtk/gvsbuild#406]
I'm completely dumbfounded why this happens.
![image](https://user-images.githubusercontent.com/40722286/101292642-a8805600-37c5-11eb-89ee-92bcaa530bf5.png)
The correct path for `vcvars32.bat` should be 
`C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars32.bat` but it seems to be going through an old path for versioning which is no longer used. If I'm wrong, please correct me.

**Comment by guruDanny67** [comment]
How's your command line ? It's possible that you put some command  to the script with the wrong path ?

**Comment by NeoInversion** [comment]
I followed the instructions in the README. The only change I made to the commands was the `vs-ver` parameter, set to 19 of course as thats the version of my Visual Studio installment. Everything else was done as instructed.

**Comment by guruDanny67** [comment]
To fix things you probably only need to give your installation path to the script: 
--vs-install-path "c;\program files (x86)\Mi .... "

Then we need to have a look at the default installation path (probably the old ones are installed in '...\Microsoft Visual Studio [vs-ver].0\ ,,,", the new ones with the year :(

**Comment by NeoInversion** [comment]
Wasn't aware of that argument! Appreciate it, should work now when I supply the argument.

**Comment by Ze-sys** [comment]
Here to thank the developers for the latest commit on the meson builder. It saved me a ton of effort trying to get it working. 
Might as well help out someone... @NeoInversion, if you haven't solved the batch file issue: First check if vcvars32.bat is on your machine. If it is not,  then try modifying your vs install by selecting the box next to  **MSVC v142 – VS 2019 C++ x64/x86 build tools (v14.28)** in the individual components tab. I got all the batch files I needed after I did that and solved a similar problem as yours.

**Comment by Junceol55** [comment]
I am getting the following error(s) when running the script. I have Visual Studio 2019 installed on my machine, and so am running the script for version 16 accordingly.

![image](https://user-images.githubusercontent.com/77214129/104110269-1260b380-52ce-11eb-9632-3f7354b841fb.png)

How do I resolve this problem so that the script finishes building successfully?

**Comment by Junceol55** [comment]
Nevermind, I figured out the error means I haven't installed the Git software.

Found it here: https://git-scm.com/book/en/v2/Getting-Started-Installing-Git

Installed that, and the script finished successfully.
