### ISSUE TITLE
Need static build

### ISSUE THREAD

**Issue by arnabanimesh** [wingtk/gvsbuild#407]
Ref. issue: [https://github.com/gtk-rs/cairo/issues/347](https://github.com/gtk-rs/cairo/issues/347)

> I use Windows 10. I used `gvsbuild` to build `glib-2.0.pc` and then ran my program usng `cargo` in both debug and release modes. It showed the following error:
> 
> `error: process didn't exit successfully: 'target\debug\draw.exe' (exit code: 0xc0000135, STATUS_DLL_NOT_FOUND)`
> 
> Entire code and logs are mentioned in this **[Github Gist](https://gist.github.com/arnabanimesh/77d4c63ea710d2a72b26ea57ae922eda)**.

I used `python .\build.py build -p x64 --vs-ver 16 gtk3` to compile. I need to create static libs so that dlls are not required with my program. Currently my program works but many dlls need to be there in the same folder.

I tried changing all instances of `DynamicLibrary` to `StaticLibrary` in this codebase but it doesn't work. Check [compilation error logs](https://gist.github.com/arnabanimesh/bb45d8cd2f94e894487df17fa8fca6b7).

**Comment by TingPing** [comment]
GTK and some of its dependencies aren't really designed to be built statically.

**Comment by arnabanimesh** [comment]
That's a shame. Thanks for responding anyway. 😢

**Comment by arnabanimesh** [comment]
Closing this issue since it seems to be fundamentally impossible to fix as of now.
