### ISSUE TITLE
Help with running in python's isolated mode, thanks.

### ISSUE THREAD

**Issue by mhertz** [wingtk/gvsbuild#413]
I know this isn't regular usage and undocumented behaviour, but I would like to run gvsbuild if possible in python's isolated mode i,e, add a 'python39._pth' file into the python dir, and with dirs added into it for module-lookups so it works as normal, but isolated from the host-systems possible own python setup.

I ran it a bunch of times and for each fail I inspected the log-output and added missing module-path to the _pth file and reran it, and now after adding the 6'th path then i'm almost in the clear, except one final hurdle I cannot understand, as pretty noob myself honestly and so hoped input from you clever lot around here :) 

It's adwaita-icon-theme, and I already added dirs for both that and librsvg, but get final error still, without clue imho to what to add to the _pth file.

This is the error:
````
 Generating adwaita-icon-theme.pc...
    	C:\Users\fooba\Downloads\deluge2\python\python.exe adwaitapc.py --prefix=C:\Users\fooba\Downloads\deluge2\gtk-build\gtk\x64\release --version=3.38.0
     Traceback (most recent call last):
      File "C:\Users\fooba\Downloads\deluge2\gtk-build\build\x64\release\adwaita-icon-theme\win32\adwaitapc.py", line 27, in <module>
        sys.exit(main(sys.argv))
      File "C:\Users\fooba\Downloads\deluge2\gtk-build\build\x64\release\adwaita-icon-theme\win32\adwaitapc.py", line 22, in main
        replace_multi(base_pc.top_srcdir + '/adwaita-icon-theme.pc.in',
      File "C:\Users\fooba\Downloads\deluge2\gtk-build\build\x64\release\librsvg\win32\replace.py", line 31, in replace_multi
        with open_file(src, 'r') as s:
      File "C:\Users\fooba\Downloads\deluge2\gtk-build\build\x64\release\librsvg\win32\replace.py", line 28, in open_file
        return open(filename, mode=mode, encoding='utf-8')
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\fooba\\Downloads\\deluge2\\gtk-build\\build\\x64\\release\\librsvg\\win32\\../adwaita-icon-theme.pc.in'
    NMAKE : fatal error U1077: 'C:\Users\fooba\Downloads\deluge2\python\python.exe' : return code '0x1'
    Stop.
2021-02-19 14:21:32 *** Error: Building project adwaita-icon-theme (3.38.0) (18.298 s)
````
I don't get why it suddently decides to look in librsvg's build-dir which is added btw, but doesn't have the adwaita-icon-theme.pc.in file in there, as is in adwaita-icon-theme's build-dir which too is added, so when running unisolated, it finds it in correct dir, but when running isolated, with corrects paths included for both adwaita and librsvg then fails to find it and even reports looking for it specifically in wrong dir i.e. librsvg's dir???

Here's same log-part for succesfull non-isolated run, and I cut it off further down as too long:
````
    Generating adwaita-icon-theme.pc...
    	C:\Users\fooba\Downloads\deluge2\python\python.exe adwaitapc.py --prefix=C:\Users\fooba\Downloads\deluge2\gtk-build\gtk\x64\release --version=3.38.0
    /usr/bin/mkdir: cannot create directory 'C:\\Users\\fooba\\Downloads\\deluge2\\gtk-build\\gtk\\x64\\release\\share\\icons\\Adwaita': File exists
    	copy index.theme C:\Users\fooba\Downloads\deluge2\gtk-build\gtk\x64\release\share\icons\Adwaita
            1 file(s) copied.
    	for /f %d in ('dir /b ..\Adwaita') do								 @(echo Copying files for %d...) & 										 @(mkdir C:\Users\fooba\Downloads\deluge2\gtk-build\gtk\x64\release\share\icons\Adwaita\%d) & 										 @(if not "%d" == "cursors"											 (for /f %f in ('dir /b /on ..\Adwaita\%d') do						 (mkdir C:\Users\fooba\Downloads\deluge2\gtk-build\gtk\x64\release\share\icons\Adwaita\%d\%f) &								 (copy /b ..\Adwaita\%d\%f\* C:\Users\fooba\Downloads\deluge2\gtk-build\gtk\x64\release\share\icons\Adwaita\%d\%f))				 else (copy /b ..\Adwaita\%d\* C:\Users\fooba\Downloads\deluge2\gtk-build\gtk\x64\release\share\icons\Adwaita\%d))
    Copying files for 16x16...
    C:\Users\fooba\Downloads\deluge2\gtk-build\build\x64\release\adwaita-icon-theme\win32>(mkdir C:\Users\fooba\Downloads\deluge2\gtk-build\gtk\x64\release\share\icons\Adwaita\16x16\actions )  & (copy /b ..\Adwaita\16x16\actions\* C:\Users\fooba\Downloads\deluge2\gtk-build\gtk\x64\release\share\icons\Adwaita\16x16\actions )
    ..\Adwaita\16x16\actions\.placeholder
            1 file(s) copied.
    C:\Users\fooba\Downloads\deluge2\gtk-build\build\x64\release\adwaita-icon-theme\win32>(mkdir C:\Users\fooba\Downloads\deluge2\gtk-build\gtk\x64\release\share\icons\Adwaita\16x16\apps )  & (copy /b ..\Adwaita\16x16\apps\* C:\Users\fooba\Downloads\deluge2\gtk-build\gtk\x64\release\share\icons\Adwaita\16x16\apps )
    ..\Adwaita\16x16\apps\.placeholder
            1 file(s) copied.
    C:\Users\fooba\Downloads\deluge2\gtk-build\build\x64\release\adwaita-icon-theme\win32>(mkdir C:\Users\fooba\Downloads\deluge2\gtk-build\gtk\x64\release\share\icons\Adwaita\16x16\categories )  & (copy /b ..\Adwaita\16x16\categories\* C:\Users\fooba\Downloads\deluge2\gtk-build\gtk\x64\release\share\icons\Adwaita\16x16\categories )
    ..\Adwaita\16x16\categories\.placeholder
            1 file(s) copied.
    C:\Users\fooba\Downloads\deluge2\gtk-build\build\x64\release\adwaita-icon-theme\win32>(mkdir C:\Users\fooba\Downloads\deluge2\gtk-build\gtk\x64\release\share\icons\Adwaita\16x16\devices )  & (copy /b ..\Adwaita\16x16\devices\* C:\Users\fooba\Downloads\deluge2\gtk-build\gtk\x64\release\share\icons\Adwaita\16x16\devices )
    ..\Adwaita\16x16\devices\.placeholder
    ..\Adwaita\16x16\devices\audio-headphones.png
    ..\Adwaita\16x16\devices\audio-headset.png
    ..\Adwaita\16x16\devices\computer.png
    ..\Adwaita\16x16\devices\drive-harddisk.png
    ..\Adwaita\16x16\devices\drive-removable-media.png
    ..\Adwaita\16x16\devices\input-gaming.png
    ..\Adwaita\16x16\devices\media-optical.png
    ..\Adwaita\16x16\devices\media-removable.png
    ..\Adwaita\16x16\devices\printer-network.png
    ..\Adwaita\16x16\devices\printer.png
           11 file(s) copied.
    C:\Users\fooba\Downloads\deluge2\gtk-build\build\x64\release\adwaita-icon-theme\win32>(mkdir C:\Users\fooba\Downloads\deluge2\gtk-build\gtk\x64\release\share\icons\Adwaita\16x16\emblems )  & (copy /b ..\Adwaita\16x16\emblems\* C:\Users\fooba\Downloads\deluge2\gtk-build\gtk\x64\release\share\icons\Adwaita\16x16\emblems )
    ..\Adwaita\16x16\emblems\.placeholder
    ..\Adwaita\16x16\emblems\emblem-readonly.png
````
Here's the called adwaitapc.py generating "wrong" lookup dir:
````
#!/usr/bin/python
#
# Utility script to generate .pc files for libsoup
# for Visual Studio builds, to be used for
# building introspection files

# Author: Fan, Chun-wei
# Date: March 10, 2016

import os
import sys

from replace import replace_multi
from pc_base import BasePCItems

def main(argv):
    base_pc = BasePCItems()

    base_pc.setup(argv)

    # Generate adwaita-icon-theme.pc
    replace_multi(base_pc.top_srcdir + '/adwaita-icon-theme.pc.in',
                  base_pc.srcdir + '/adwaita-icon-theme.pc',
                  base_pc.base_replace_items)

if __name__ == '__main__':
    sys.exit(main(sys.argv))
````
Thanks alot in advance for any input. I want to run in isolated mode because provide a script that builds gtk3 through gvsbuild, with provided dedicated copies of python and msvc etc, but want to make sure not interferring with the users host-system and possible own python install etc.

**Comment by guruDanny67** [comment]
You can use an embedded python version (I use it regularly) to launch the
script: just download the win32 or amd64 version .zip file, extract it in
c:\gtk-build\github\pyemb and then launch the script from
c:\gtk-build\github\gvsbuild as

..\pyemb\python.exe build.py build [options ...] projects

and you are sure you're not touching any python in the system.

You can also checkout the wip/wmb_python (I probably miss a w for an e so
it should be emb_python ...) and use the bld.bat batch to launch the script
with the same parameters of the script, e.g. 'bld.bat bulld --vs-ver 16
zlib' that has the embedded python in the git source: no change should be
made to the user: the python used for the script is the one in the script
itself, the one used by the projects is downloaded in the tools dir without
touching the other python(s) around.

With best regards

Il giorno ven 19 feb 2021 alle ore 20:28 Martin Hertz <
notifications@github.com> ha scritto:

**Comment by mhertz** [comment]
Thanks alot Danny for your always helpfull input, I I kinda hoped you would reply to me as you've always been so helpfull before, and you didn't let me down, thanks mate, appreciated! :)

I did initially use the embedded python zip, but had some errors, which instead of try fixing, I just changed to the nuget python version which can too be extracted and run likewise without installing, and I just add a python39._pth file to it's dir so that it's run isolated just like the embedded distribution

I'm surpriced you state to be able to do that without issue, as when isolated then only the dirs available for lookup as you define in said pth file, so I needed add 6 paths to build the full gtk stack myself.

That wip/wmb_python sounds like a great solution, thanks alot, will check that out later.

About my issue here, then after posting my issue, then I came to think about if the order of paths in said pth file did make a difference, and normally they shouldn't, but then I came to think about that both librsvg and adwaita had a module with same name i.e. replace.py, and so I rerun gvsbuild with the adwaita path further up in pth file and over the librsvg path, and sure enough, just finished succesfully. I came to think about that, because noticed in one of the called source-files that the "wrong" lookup dir for the file in the error get generated from a getdir() call of __file__, and that "wrong" path was originally ahead of the "correct" dir in the pth file, meaning the "wrong" replace.py got called and used to generate the "wrong" dir.

Anyway, I appreciate your help alot Danny, thank you!

**Comment by guruDanny67** [comment]
In my setup, I don't have any python in the path and I don't have the py launcher either so the scripts and the build files use the python downloaded from nuget (under the tools dir).

In one recent change in the python tool a python3.exe is created from the python.exe present to avoid getting the wrong one being used (if I remember correctly meson sometimes use the mingw python because it searches for python3) and this helped a lot.

As a fast test you can try to delete the tools dir so you start clean (and the python3 is created).

As another test you can try to uninstall the py launcher (it's in the windows system dir so the script has access to it).

Hope this helps

With best regards

**Comment by mhertz** [comment]
Always appreciate your replies Danny, and sure helps! Honestly I haven't even yet looked into how gvsbuild works i.e. use own python under tools and whatnot, and in my case I just have always in my script added my own python to the PATH, but at front so used first, and then just called python for gvsbuild with 'python', but see there's other ways to do it now :)

Anyway, as said I never install python or the loader etc, and just curl newest python from nuget and extract it into a folder and add in-front of path.

Reason for me wanting to run isolated, even when controling which python that's used, is there are edge-cases where isolation is warranted i.e. some apps or IDE's, or folks themselves, add e.g. PYTHONPATH env-vars, and such can potentially break a python project if own python also installed, additionally to the one used for gvsbuild. Hence, I originally tried use the embedded python zip, which has this isolated mode enabled through addition of python39._pth file, but got error with missing headers I believe, and so just reverted to the nuget version instead and manually added said *._pth file which enables isolated mode(so python env-vars ignored and you have to add lokkup paths for modules yourselves into that file, so never wrong version used).

Anyway, might as well remove my python from PATH and use direct path to call python with instead, as you stated also.

I thought I was finished adding paths for sys.path or whatever it's called, in said _pth file, but find still missing a few as still failed when trying build full gtk3 stack and not just a subset(I forgot didn't tested the full stack in my last post), and so in my script calling gvsbuild I use now, e.g. this snippet from it, which works:
````
[...]
for /f %%i in ('curl -s https://www.python.org/ ^| grep "Latest: " ^| cut -d/ -f5 ^| cut -d" " -f2 ^| tr -d "<"') do set var2=%%i
for /f %%i in ('echo %var2% ^| cut -d. -f1-2 ^| tr -d .') do set PYTHONVER=%%i
mkdir python & curl -L https://www.nuget.org/api/v2/package/python/%var2% | bsdtar xf - -C python --include tools --strip-components 1
%MSYSPATH%\echo -e Lib\nDLLs\nimport site >> python\python%PYTHONVER%._pth
curl https://bootstrap.pypa.io/get-pip.py | python\python.exe
git clone https://github.com/wingtk/gvsbuild gtk-build\gvsbuild
pushd gtk-build\gvsbuild
for /f %%a in ('grep "dir_part = 'meson" gvsbuild\tools.py ^| cut -d^"^'^" -f2') do %MSYSPATH%\echo %BUILD_DIR%/tools/%%a >> ..\..\python\python%PYTHONVER%._pth
%MSYSPATH%\echo %BUILD_DIR%/build/x64/release/adwaita-icon-theme/win32 >> ..\..\python\python%PYTHONVER%._pth
%MSYSPATH%\echo %BUILD_DIR%/build/x64/release/adwaita-icon-theme >> ..\..\python\python%PYTHONVER%._pth
%MSYSPATH%\echo %BUILD_DIR%/build/x64/release/librsvg/win32 >> ..\..\python\python%PYTHONVER%._pth
%MSYSPATH%\echo %BUILD_DIR%/build/x64/release/libcroco/win32 >> ..\..\python\python%PYTHONVER%._pth
%MSYSPATH%\echo %BUILD_DIR%/build/x64/release/atk >> ..\..\python\python%PYTHONVER%._pth
%MSYSPATH%\echo %BUILD_DIR%/build/x64/release/atk/atk >> ..\..\python\python%PYTHONVER%._pth
%MSYSPATH%\echo %BUILD_DIR%/build/x64/release/glib >> ..\..\python\python%PYTHONVER%._pth
%MSYSPATH%\echo %BUILD_DIR%/build/x64/release/glib/gobject >> ..\..\python\python%PYTHONVER%._pth
%MSYSPATH%\echo %BUILD_DIR%/build/x64/release/glib/glib >> ..\..\python\python%PYTHONVER%._pth
%MSYSPATH%\echo %BUILD_DIR%/build/x64/release/gio >> ..\..\python\python%PYTHONVER%._pth
%MSYSPATH%\echo %BUILD_DIR%/build/x64/release/gio/win32 >> ..\..\python\python%PYTHONVER%._pth
%MSYSPATH%\echo %BUILD_DIR%/build/x64/release/gobject-introspection >> ..\..\python\python%PYTHONVER%._pth
%MSYSPATH%\echo %BUILD_DIR%/build/x64/release/gobject-introspection/gir >> ..\..\python\python%PYTHONVER%._pth
%MSYSPATH%\echo %BUILD_DIR%/build/x64/release/gobject-introspection/giscanner >> ..\..\python\python%PYTHONVER%._pth
%MSYSPATH%\echo %BUILD_DIR%/build/x64/release/gobject-introspection/girepository >> ..\..\python\python%PYTHONVER%._pth
%MSYSPATH%\echo %BUILD_DIR%/build/x64/release/gobject-introspection/tools >> ..\..\python\python%PYTHONVER%._pth
%MSYSPATH%\echo %BUILD_DIR%/build/x64/release/gobject-introspection/subprojects >> ..\..\python\python%PYTHONVER%._pth
%MSYSPATH%\echo %BUILD_DIR%/build/x64/release/gobject-introspection/misc >> ..\..\python\python%PYTHONVER%._pth
%MSYSPATH%\echo %BUILD_DIR%/build/x64/release/gobject-introspection/m4 >> ..\..\python\python%PYTHONVER%._pth
%MSYSPATH%\echo %BUILD_DIR%/build/x64/release/gobject-introspection/examples >> ..\..\python\python%PYTHONVER%._pth
%MSYSPATH%\echo %BUILD_DIR%/build/x64/release/gobject-introspection/examples/girepository >> ..\..\python\python%PYTHONVER%._pth
%MSYSPATH%\echo %BUILD_DIR%/build/x64/release/gobject-introspection/examples/library >> ..\..\python\python%PYTHONVER%._pth
sed -i 's.\\\./.g' ..\..\python\python%PYTHONVER%._pth
[...]
```` 
The last few path's I probably don't need, and need test more to see how many can remove, but just was lazy and didn't want to run for 10'th time and so just added all the path's possibly could be needed from said last failing project, and also worked, but i'm sure not all is needed, e.g. examples and whatnot etc. I btw, use 'echo' from msys2, because the cmd native one adds some double-quotes from beginning of path and into about middle and continues un-quoted, which isn't supported and breaks the pth file lookup, but doesn't with msys's version.

Yeah, one could also use '-E' as python argument for avoidng env.vars like e.g. PYTHONPATH, but there is further benefits additionally for running in full isolated mode I believe, and as said, I provide the script for other users which possibly have own python setup etc.

Anyway, sorry for my long blabbing on, and i'll look into your pointers definetely - thanks mate as always, much appreciate it! :)
