### ISSUE TITLE
grpc fail with new cmake version

### ISSUE THREAD

**Issue by guruDanny67** [wingtk/gvsbuild#416]
Actually, the grpc project fails to build, with vs2019 & vs2017, due to some missing externals.

The reason should be the new cmake version (the grpc version 1.2, a little bit old): I try to use the old cmake and everything works as expected.

We can try to upgrade grpc to a new version, use the old cmake only for this project or try to fix the actual one.

Thoughts?

Thanks in advance.

**Comment by nacho** [comment]
do you need grpc? Otherwise I will be tempted to delete it since I am not using it anymore.

**Comment by guruDanny67** [comment]
I don't need it, it's also a little bit updated.

Normally, if there aren't some compelling reasons, I try to not remove anything (in real life you put 200 new fantastic features in your program and drop a 15-year hack used only in some strange configuration and THAT is the first thing the customer notice and you need to work in the weekend to enable it again ...).

I got a new 5950X Amd pc (16 cores/32 threads, used for dev, the rtx3090 is not for cyberpunk 2077 ...) so I'm looking to have some parallels built and I'm looking at the builder class to organize things and I'm testing a way to have different versions of some tool for different projects: in this way the fix is really trivial and the feature can be really useful in the future.

So I think is ok as it is now and will be fixed soon

**Comment by pbor** [comment]
I think given that nobody complained that it is broken and we do not need it, we should drop it :)
