### ISSUE TITLE
Vcvars64.bat could not be found!

### ISSUE THREAD

**Issue by jpie726** [wingtk/gvsbuild#418]
```
PS C:\gtk-build\github\gvsbuild> python .\build.py build -p x64 --vs-ver 19 --win-sdk 10 -c release gtk3
Cleaning up the build environment
Checking msys tool
Checking Msvc tool

Visual studio installation(s) found:
    Visual Studio Build Tools 2019 @ C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    Visual Studio Community 2019 @ C:\Program Files (x86)\Microsoft Visual Studio\2019\Community

Error:
  'C:\Program Files (x86)\Microsoft Visual Studio 19.0\VC\Auxiliary\Build\vcvars64.bat' could not be found.
  Please check you have Visual Studio installed at 'C:\Program Files (x86)\Microsoft Visual Studio 19.0'
  and that it supports the target platform 'x64'.
PS C:\gtk-build\github\gvsbuild>
```

Why does GVSBuild require Visual Studio to be installed in the (non default) location of `C:\Program Files (x86)\Microsoft Visual Studio 19.0`? Any way I can fix this?
It gives the same error (except x86) for `python .\build.py build --vs-ver 19 --win-sdk 10 -c release gtk3`.
I have MSYS2, Python 3.9.2 (and 3.6.8), and Visual Studio 2019 installed.

**Comment by alex-smtv** [comment]
I had a similar issue and after digging into the code I found this in the parser:
`if not opts.vs_install_path:
        if opts.vs_ver == "15":
            opts.vs_install_path = r'C:\Program Files (x86)\Microsoft Visual Studio\2017'
            opts._vs_path_auto = True
        elif opts.vs_ver == "16":
            opts.vs_install_path = r'C:\Program Files (x86)\Microsoft Visual Studio\2019'
            opts._vs_path_auto = True
        else:
            opts.vs_install_path = r'C:\Program Files (x86)\Microsoft Visual Studio %s.0' % (opts.vs_ver,)`

It's a bit counter-intuitive, but if you're using the 2019 edition you should specify `--vs-ver 16`.

**Comment by jpie726** [comment]
Thanks, I'll try that in a bit

**Comment by jpie726** [comment]
That got me closer, but it still fails to build pkg-config
```
PS C:\gtk-build\github\gvsbuild> python .\build.py build --vs-ver 16 --win-sdk 10 -c release gtk3
Cleaning up the build environment
Checking msys tool
Checking Msvc tool
Downloading packages
```
etc etc, successful up until
```
HEAD is now at 74133ed pkgconf 1.5.4.
Building project pkg-config (git/pkgconf-1.5.4)
patching file libpkgconf/bsdstubs.c
patching file libpkgconf/libpkgconf.h
The Meson build system
Version: 0.57.1
Source dir: C:\gtk-build\build\Win32\release\pkgconf
Build dir: C:\gtk-build\build\Win32\release\pkgconf\_gvsbuild-meson
Build type: native build
Project name: pkgconf
Project version: 1.4.0

meson.build:1:0: ERROR: Unknown compiler(s): ['icl', 'cl', 'cc', 'gcc', 'clang', 'clang-cl', 'pgcc']
The following exception(s) were encountered:
Running "icl " gave "[WinError 2] The system cannot find the file specified"
Running "cl /?" gave "[WinError 2] The system cannot find the file specified"
Running "cc --version" gave "[WinError 2] The system cannot find the file specified"
Running "gcc --version" gave "[WinError 2] The system cannot find the file specified"
Running "clang --version" gave "[WinError 2] The system cannot find the file specified"
Running "clang-cl /?" gave "[WinError 2] The system cannot find the file specified"
Running "pgcc --version" gave "[WinError 2] The system cannot find the file specified"
```
and
```
subprocess.CalledProcessError: Command 'C:\gtk-build\tools\pythonx86.3.9.2\tools\python.exe C:\gtk-build\tools\meson-0.57.1\meson.py C:\gtk-build\build\Win32\release\pkgconf C:\gtk-build\build\Win32\release\pkgconf\_gvsbuild-meson --prefix C:\gtk-build\gtk\Win32\release -Dtests=false --buildtype debugoptimized' returned non-zero exit status 1.
Error: pkg-config build failed
```
Running `gcc --version` gets me
```
PS C:\gtk-build\github\gvsbuild> gcc --version
gcc.exe (MinGW.org GCC-6.3.0-1) 6.3.0
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by jpie726** [comment]
Unresolved, and I am no longer on Windows.

**Comment by 3man001** [comment]
With the same problem on VS2022
[gvsbuild-log.txt](https://github.com/wingtk/gvsbuild/files/8646806/gvsbuild-log.txt)

**Comment by danyeaw** [comment]
@3man001 It would be better to open a new issue. Do you have visualstudio2022-workload-vctools installed?

**Comment by 3man001** [comment]
Installed because the result of running "choco install visualstudio2022-workload-vctools" is "visualstudio2022-workload-vctools v1.0.0 already installed.".
Only vcvars64.bat for some reason is located in "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build".

**Comment by danyeaw** [comment]
If you set `--vs-install-dir` to your BuildTools directory does it work?

**Comment by 3man001** [comment]
`--vs-install-path` only has such a parameter.
@[danyeaw](https://github.com/danyeaw) Thanks for the help. The problem was solved by deleting **visualstudio2022-workload-vctools** and **visualstudio2022buildtools** via chocolatey. With subsequent installation.
