### ISSUE TITLE
Error: libepoxy build failed (Build by VS2019)

### ISSUE THREAD

**Issue by yihuajack** [wingtk/gvsbuild#419]
Environment:
OS version: Windows 10 20H2
Visual Studio version: 2019
MSYS2 64bit version: 20201109
Build command: `python .\build.py build -p x64 --vs-ver 16 gtk3 --msys-dir='E:\Program_Files\msys64' --vs-install-path='D:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise'`
```
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 492, in build
    if self.__build_one(p):
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 618, in __build_one
    skip_deps = proj.build()
  File "C:\gtk-build\github\gvsbuild\gvsbuild\projects.py", line 1093, in build
    Meson.build(self)
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\base_builders.py", line 76, in build
    self.builder.exec_ninja(params='install', working_dir=ninja_build)
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 902, in exec_ninja
    self.__execute(self.__sub_vars(cmd), working_dir=working_dir, add_path=add_path, env=self.vs_env)
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 942, in __execute
    subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
  File "E:\Program_Files\Python39\lib\subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'ninja install' returned non-zero exit status 1.
Error: libepoxy build failed
```
Detailed log is attached.
[gvsbuild-log.txt](https://github.com/wingtk/gvsbuild/files/6483355/gvsbuild-log.txt)

**Comment by zhengxiaoFTD** [comment]
说真的，我可能能解决你这个问题。
我也遇到了你这个问题，已经解决了。
知道为嘛只有中国人才遇到这个问题了吗？因为系统语言和vs2019用的都是中文，你把系统语言和vs的语言都切换成英文（美国）试试。一定要你在win10中看到的所有字都是英文才顶事（除了你自己打的字）（其实就是全部切换成了utf-8编码）。
下面是我编译成功以后的样子：
> Installing C:\gtk-build\build\x64\release\gtk3-24\gtk\org.gtk.Settings.FileChooser.gschema.xml to C:/gtk-build/gtk/x64/release/share/glib-2.0/schemas
Installing C:\gtk-build\build\x64\release\gtk3-24\gtk\org.gtk.Settings.ColorChooser.gschema.xml to C:/gtk-build/gtk/x64/release/share/glib-2.0/schemas
Installing C:\gtk-build\build\x64\release\gtk3-24\gtk\org.gtk.Settings.EmojiChooser.gschema.xml to C:/gtk-build/gtk/x64/release/share/glib-2.0/schemas
Installing C:\gtk-build\build\x64\release\gtk3-24\gtk\org.gtk.Settings.Debug.gschema.xml to C:/gtk-build/gtk/x64/release/share/glib-2.0/schemas
Installing C:\gtk-build\build\x64\release\gtk3-24\gtk\gtk-keys.css.default to C:\gtk-build\gtk\x64\release\share/themes/Default/gtk-3.0
Installing C:\gtk-build\build\x64\release\gtk3-24\gtk\gtk-keys.css.emacs to C:\gtk-build\gtk\x64\release\share/themes/Emacs/gtk-3.0
Installing C:\gtk-build\build\x64\release\gtk3-24\gtk\gtkbuilder.rng to C:/gtk-build/gtk/x64/release/share/gtk-3.0
Installing C:\gtk-build\build\x64\release\gtk3-24\gtk\gtkbuilder.loc to C:/gtk-build/gtk/x64/release/share/gettext/its
Installing C:\gtk-build\build\x64\release\gtk3-24\gtk\gtkbuilder.its to C:/gtk-build/gtk/x64/release/share/gettext/its
Installing C:\gtk-build\build\x64\release\gtk3-24\_gvsbuild-meson\gail-3.0.pc to C:\gtk-build\gtk\x64\release\lib/pkgconfig
Installing C:\gtk-build\build\x64\release\gtk3-24\_gvsbuild-meson\gdk-3.0.pc to C:\gtk-build\gtk\x64\release\lib/pkgconfig
Installing C:\gtk-build\build\x64\release\gtk3-24\_gvsbuild-meson\gdk-win32-3.0.pc to C:\gtk-build\gtk\x64\release\lib/pkgconfig
Installing C:\gtk-build\build\x64\release\gtk3-24\_gvsbuild-meson\gtk+-3.0.pc to C:\gtk-build\gtk\x64\release\lib/pkgconfig
Installing C:\gtk-build\build\x64\release\gtk3-24\_gvsbuild-meson\gtk+-win32-3.0.pc to C:\gtk-build\gtk\x64\release\lib/pkgconfig
Installing C:\gtk-build\build\x64\release\gtk3-24\m4macros/gtk-3.0.m4 to C:\gtk-build\gtk\x64\release\share/aclocal
Running custom install script 'C:\\gtk-build\\tools\\python.3.9.2\\tools\\python.exe C:\\gtk-build\\tools\\meson-0.57.1\\meson.py --internal gettext install --subdir=po --localedir=share/locale --pkgname=gtk30'
Running custom install script 'C:\\gtk-build\\tools\\python.3.9.2\\tools\\python.exe C:\\gtk-build\\tools\\meson-0.57.1\\meson.py --internal gettext install --subdir=po-properties --localedir=share/locale --pkgname=gtk30-properties'
Running custom install script 'C:\\gtk-build\\tools\\python.3.9.2\\tools\\python.exe C:\\gtk-build\\build\\x64\\release\\gtk3-24\\build-aux/meson/post-install.py 3.0 3.0.0 C:/gtk-build/gtk/x64/release/bin C:/gtk-build/gtk/x64/release/lib C:/gtk-build/gtk/x64/release/share'

> 

Project(s) built:
    nuget                     (0.013 s)
    python                    (0.016 s)
    ninja                     (0.005 s)
    meson                     (0.008 s)
    pkg-config                (3.079 s)
    cmake                     (0.006 s)
    win-iconv                 (1.361 s)
    gettext                   (4.002 s)
    libffi                    (3.925 s)
    zlib                      (0.111 s)
    glib                      (8.621 s)
    atk                       (4.987 s)
    nasm                      (0.005 s)
    libjpeg-turbo             (1.782 s)
    libtiff-4                 (4.561 s)
    jasper                    (2.092 s)
    libpng                    (1.496 s)
    gdk-pixbuf                (7.852 s)
    freetype                  (1.494 s)
    libxml2                   (0.897 s)
    fontconfig                (1.360 s)
    pixman                    (0.692 s)
    cairo                     (2.168 s)
    harfbuzz                  (1.029 s)
    fribidi                   (3.231 s)
    pango                     (0.993 s)
    libepoxy                  (2.069 s)
    gtk3                      (71.214 s)

C:\gtk-build\github\gvsbuild>

**Comment by yihuajack** [comment]
@zhengxiaoFTD Thank you for your solution that to change the system language and the language of Visual Studio to English.

**Comment by North2Tree** [comment]
> @zhengxiaoFTD Thank you for your solution that to change the system language and the language of Visual Studio to English.

Hello, I also encountered the same problem as you. After changing the system language and the language of Visual Studio to English, this problem still occurs. In addition to these operations, have you set other options?
