### ISSUE TITLE
Microsoft Visual Studio 2019 Professional Install GTK -  Version GTK-3

### ISSUE THREAD

**Issue by charleswri631** [wingtk/gvsbuild#426]
Any suggestions on this error that I get for x86 install of GTK-3
I still have not tried to install x64 install GTK-3

![ERROR_1_GTK3](https://user-images.githubusercontent.com/65590698/122733111-e10bec80-d24a-11eb-8df0-a0aca2d25e49.png)

Any help that would guide me in the correct direction to solve this issue would be truly appreciated due to my extreme need to use GTK-3 GUI features for C programming. 

GTK-3 looks great. Everyone should code C programming and have GUI interfaces available to use with C language Code.

**Comment by charleswri631** [comment]
![GTK-image1](https://user-images.githubusercontent.com/65590698/122733848-92ab1d80-d24b-11eb-9eb2-82ec8afc6397.png)

![GTK-image2](https://user-images.githubusercontent.com/65590698/122733856-93dc4a80-d24b-11eb-947b-9b30a45335c3.png)

**Comment by charleswri631** [comment]
Is there a way to install the entire library as well

**Comment by charleswri631** [comment]
gtk3-full if its similar to that command which goes with other text before return is pressed!

**Comment by charleswri631** [comment]
https://github.com/wingtk/gvsbuild/issues/415

**Comment by charleswri631** [comment]
I read a related issue at the link above.

**Comment by charleswri631** [comment]
![Error_GTK_3](https://user-images.githubusercontent.com/65590698/122838942-0f2e1280-d2c5-11eb-90a1-f7a1b77fc98b.png)

**Comment by charleswri631** [comment]
python .\build.py build -p x86 -c release gtk3 --vs-ver 19 --vs-install-path "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional"

**Comment by charleswri631** [comment]
I passed this error but now I get an error which is:

**Comment by charleswri631** [comment]
![Error_GTK_3_NEW](https://user-images.githubusercontent.com/65590698/122839063-51575400-d2c5-11eb-8850-8e161fc2f005.png)

**Comment by charleswri631** [comment]
This is the error I get!

**Comment by charleswri631** [comment]
After correcting the install path and getting the command build to function correctly but it results in this new error.

**Comment by charleswri631** [comment]
python .\build.py build -p x86 -c release gtk3 --vs-ver 19 --vs-install-path "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional"

This command above solved my build error! But now I get an ERROR: gettext build failed!

**Comment by charleswri631** [comment]
It seems to be building a project. Do I need to have a project downloaded and put in a folder somewhere?

**Comment by charleswri631** [comment]
I notice that v15 is the highest version I have in the build folder for gettext project .sln which I assume is Visual Studio 2015. I am using visual studio 2019 should there be a folder v19 for gettext .sln for it to work correctly.

This seems to be why I get a gettext build error solution .sln is not found.

**Comment by charleswri631** [comment]
When I run the command: python .\build.py build -p x86 -c release gtk3 --vs-ver 19 --vs-install-path "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional"

**Comment by Linoprit** [comment]
Hi, if you use Visual Studio 2019, your version is 16. => try --vs-ver 16
15 = VS2017
14 = VS2015

This command worked for me:
python .\build.py build --same-python --build-dir "c:\gtk" -c debug --vs-ver 16 gtk3-full --msys-dir e:\tools\msys64

Set the build dir as short as possible.
If your build fails with at building clutter (I suppose, it will), goto  clutter-stage.c, line 3799 and remove 'return'.

**Comment by charleswri631** [comment]
This is a new error I get with Visual Studio 2017 Professional when I run command:

python .\build.py build -p x86 -c release gtk3-full --vs-ver 15 --vs-install-path "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional"

I tried Visual Studio 2013, 2017, 2019 Professional. Although I will look into the command you provided me with and see what I can do to solve my problem.

Your command which is:

python .\build.py build --same-python --build-dir "c:\gtk" -c debug --vs-ver 16 gtk3-full --msys-dir e:\tools\msys64

I will analyze to see what I can do and if it will solve my problem.

Thank You!

 ![2_ERROR_GTK3-2017](https://user-images.githubusercontent.com/65590698/122981893-3e499000-d368-11eb-9aa0-ac42abc14c7d.png)

**Comment by charleswri631** [comment]
This is the error I get when trying to install GTK3 into Visual Studio 2017 Professional.

I was using this command.

python .\build.py build -p x86 -c debug gtk3-full --build-dir "C:\gtk-build\gtk-build-assembly" --msys-dir "C:\msys64" --vs-ver 15 --vs-install-path "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional" --same-python

I do plan to install both the x64 and x86 versions on my system for Visual Studio 2017 Professional.
These are the arguments I have given to these parameters.

-p x86
--same-python
--build-dir "C:\gtk-build\gtk-build-assembly"   
--msys-dir "C:\msys64"
-c debug gtk3-full
--vs-ver 15 
--vs-install-path "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional"



![3_ERROR_GTK3-2017](https://user-images.githubusercontent.com/65590698/122985342-0e9c8700-d36c-11eb-82a5-6ef2549b2794.png)

**Comment by charleswri631** [comment]
I tried to take advice from the person who commented on my issue. Any suggestions?
Could I have a problem with the build directory or the msys directory?

**Comment by charleswri631** [comment]
I was still unsuccessful to install GTK3 on any of my Visual Studio 2013, 2017, 2019 Professional Versions.
If you have any suggestions I would truly appreciate it!!!

Thank You!

I have had much more success with vcpkg.exe which was fairly simple to install and works on Visual Studio 2017 and 2019.
Although my ability to install vcpkg.exe on Visual Studio 2013 was a failure and a disappointment. I truly wanted to use Visual Studio 2013 for everything I was doing.

It seems that GTK3 works on Visual Studio 2013 but I was unable to install it on Visual Studio 2013 Professional.
So I tried using Visual Studio 2017 Professional Preferably.

**Comment by Linoprit** [comment]
Did you try a clean build ( --from-scratch)? 
And your --build-dir path is too long. Use C:\gtk. 
After compiling, you can move the folder, or just the results from gtk/win32/debug.

**Comment by charleswri631** [comment]
Is there a command argument to add to this full command to create a clean build.
I changed the build directory so that it is short.
I will check to see if I have msys64 up to date!

python .\build.py build -p x86 -c debug gtk3-full --build-dir "C:\gtk" --msys-dir "C:\msys64" --vs-ver 15 --vs-install-path "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional" --same-python

**Comment by charleswri631** [comment]
python .\build.py build -p x86 -c debug gtk3-full --build-dir "C:\gtk" --msys-dir "C:\msys64" --vs-ver 15 --vs-install-path "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional" --same-python --clean

**Comment by charleswri631** [comment]
--clean    command used for a clean build from scratch.

**Comment by Linoprit** [comment]
Same result?
Is there a possibility to upload the built files? I could give you my recent build with visual studio 2017, x86, release or debug.
It's about 500Mb.

**Comment by charleswri631** [comment]
This is the new error I get when I do all that was mentioned which is --clean from scratch also shorten build-dir to "c:\gtk" and also Update msys2 so that it is up to date. 

![ERROR_GTK3-VS-2017](https://user-images.githubusercontent.com/65590698/123062479-915c2b00-d3da-11eb-8bb2-59ec7e5a2631.png)

**Comment by charleswri631** [comment]
Sure however you would like to help me I would truly appreciate the help! What should my next step be?

**Comment by charleswri631** [comment]
And yes msys2 updated files a bunch of files!

**Comment by Linoprit** [comment]
pkg_resources is a python module. So the problem lies in your python installation. 
If you start python in your cmd-window: 
python
>>> import pkg_resources
(ctrl-Z to leave)
You should get no error message. So, next step is to check/fix this.

**Comment by danyeaw** [comment]
We updated the README to walk through a good setup to build GTK, if you are still having issues please open a new issue, thanks!
