### ISSUE TITLE
Error: gtk3 build failed

### ISSUE THREAD

**Issue by zhmmmm** [wingtk/gvsbuild#433]
(tar) Exporting gtk3
Building project gtk3 (3.24.28)
[1/522] Generating gtkresources_h with a custom command
FAILED: gtk/gtkresources.h
"C:\gtk-build\gtk\x64\release\bin\glib-compile-resources.EXE" "gtk/gtk.gresources.xml" "--sourcedir" "C:/gtk-build/build/x64/release/gtk3-24/_gvsbuild-meson/gtk" "--sourcedir" "C:/gtk-build/build/x64/release/gtk3-24/gtk" "--sourcedir" "../gtk" "--c-name" "_gtk" "--internal" "--generate" "--target" "gtk/gtkresources.h" "--manual-register"
[2/522] Generating gtkresources_c with a custom command
FAILED: gtk/gtkresources.c
"C:\gtk-build\gtk\x64\release\bin\glib-compile-resources.EXE" "gtk/gtk.gresources.xml" "--sourcedir" "C:/gtk-build/build/x64/release/gtk3-24/_gvsbuild-meson/gtk" "--sourcedir" "C:/gtk-build/build/x64/release/gtk3-24/gtk" "--sourcedir" "../gtk" "--c-name" "_gtk" "--internal" "--generate" "--target" "gtk/gtkresources.c" "--manual-register" "--dependency-file" "gtk/gtkresources.c.d"
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "H:\library\libgtk\gvsbuild\gvsbuild\utils\builder.py", line 493, in build
    if self.__build_one(p):
  File "H:\library\libgtk\gvsbuild\gvsbuild\utils\builder.py", line 624, in __build_one
    skip_deps = proj.build()
  File "H:\library\libgtk\gvsbuild\gvsbuild\projects.py", line 897, in build
    Meson.build(self, meson_params='-Dtests=false -Ddemos=false -Dexamples=false')
  File "H:\library\libgtk\gvsbuild\gvsbuild\utils\base_builders.py", line 76, in build
    self.builder.exec_ninja(params='install', working_dir=ninja_build)
  File "H:\library\libgtk\gvsbuild\gvsbuild\utils\builder.py", line 908, in exec_ninja
    self.__execute(self.__sub_vars(cmd), working_dir=working_dir, add_path=add_path, env=self.vs_env)
  File "H:\library\libgtk\gvsbuild\gvsbuild\utils\builder.py", line 948, in __execute
    subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'ninja install' returned non-zero exit status 1.
Error: gtk3 build failed

**Comment by zhmmmm** [comment]
../gdk/gdkdevice.c(640): warning C4244: “=”: 从“double”转换到“gint”，可能丢失数据
../gdk/gdkdevice.c(642): warning C4244: “=”: 从“double”转换到“gint”，可能丢失数据
../gdk/gdkdevice.c(729): warning C4244: “=”: 从“double”转换到“gint”，可能丢失数据
../gdk/gdkdevice.c(731): warning C4244: “=”: 从“double”转换到“gint”，可能丢失数据
[62/645] Compiling C object gdk/gdk-3-vs15.dll.p/gdkdisplay.c.obj
../gdk/gdkdisplay.c(687): warning C4244: “=”: 从“double”转换到“gint”，可能丢失数据
../gdk/gdkdisplay.c(689): warning C4244: “=”: 从“double”转换到“gint”，可能丢失数据
../gdk/gdkdisplay.c(1010): warning C4244: “=”: 从“double”转换到“int”，可能丢失数据
../gdk/gdkdisplay.c(1011): warning C4244: “=”: 从“double”转换到“int”，可能丢失数据
[65/645] Compiling C object gdk/gdk-3-vs15.dll.p/gdkevents.c.obj
../gdk/gdkevents.c(2219): warning C4244: “=”: 从“gdouble”转换到“gint”，可能丢失数据
../gdk/gdkevents.c(2221): warning C4244: “=”: 从“gdouble”转换到“gint”，可能丢失数据
../gdk/gdkevents.c(2233): warning C4244: “=”: 从“gdouble”转换到“gint”，可能丢失数据
../gdk/gdkevents.c(2235): warning C4244: “=”: 从“gdouble”转换到“gint”，可能丢失数据
[71/645] Compiling C object gdk/gdk-3-vs15.dll.p/gdkoffscreenwindow.c.obj
../gdk/gdkoffscreenwindow.c(272): warning C4244: “=”: 从“double”转换到“int”，可能丢失数据
../gdk/gdkoffscreenwindow.c(273): warning C4244: “=”: 从“double”转换到“int”，可能丢失数据
[92/645] Compiling C object gdk/gdk-3-vs15.dll.p/gdkgl.c.obj
../gdk/gdkgl.c(227): warning C4244: “初始化”: 从“int”转换到“float”，可能丢失数据
../gdk/gdkgl.c(228): warning C4244: “初始化”: 从“int”转换到“float”，可能丢失数据
../gdk/gdkgl.c(400): warning C4244: “=”: 从“double”转换到“int”，可能丢失数据
../gdk/gdkgl.c(401): warning C4244: “=”: 从“double”转换到“int”，可能丢失数据
../gdk/gdkgl.c(607): warning C4244: “初始化”: 从“int”转换到“float”，可能丢失数据
../gdk/gdkgl.c(787): warning C4244: “*=”: 从“double”转换到“int”，可能丢失数据
../gdk/gdkgl.c(788): warning C4244: “*=”: 从“double”转换到“int”，可能丢失数据
../gdk/gdkgl.c(791): warning C4244: “*=”: 从“double”转换到“int”，可能丢失数据
../gdk/gdkgl.c(792): warning C4244: “*=”: 从“double”转换到“int”，可能丢失数据
../gdk/gdkgl.c(811): warning C4244: “初始化”: 从“int”转换到“float”，可能丢失数据
[104/645] Compiling C object gdk/gdk-3-vs15.dll.p/gdkwindow.c.obj
../gdk/gdkwindow.c(5102): warning C4244: “=”: 从“double”转换到“gint”，可能丢失数据
../gdk/gdkwindow.c(5104): warning C4244: “=”: 从“double”转换到“gint”，可能丢失数据
../gdk/gdkwindow.c(7660): warning C4244: “函数”: 从“gdouble”转换到“int”，可能丢失数据
../gdk/gdkwindow.c(7663): warning C4244: “函数”: 从“gdouble”转换到“int”，可能丢失数据
../gdk/gdkwindow.c(9184): warning C4133: “函数”: 从“guint *”到“GdkModifierType *”的类型不兼容
../gdk/gdkwindow.c(9487): warning C4133: “函数”: 从“guint *”到“GdkModifierType *”的类型不兼容
../gdk/gdkwindow.c(9570): warning C4133: “函数”: 从“GdkEventMask *”到“guint *”的类型不兼容
../gdk/gdkwindow.c(9763): warning C4133: “函数”: 从“guint *”到“GdkModifierType *”的类型不兼容
../gdk/gdkwindow.c(9777): warning C4133: “函数”: 从“GdkEventMask *”到“guint *”的类型不兼容
../gdk/gdkwindow.c(10055): warning C4133: “函数”: 从“guint32 *”到“GdkModifierType *”的类型不兼容
../gdk/gdkwindow.c(10182): warning C4244: “函数”: 从“double”转换到“int”，可能丢失数据
../gdk/gdkwindow.c(11344): warning C4244: “=”: 从“double”转换到“guint8”，可能丢失数据
[115/645] Linking target gdk/gdk-3-vs15.dll
  正在创建库 gdk\gdk-3.lib 和对象 gdk\gdk-3.exp
[124/645] Generating gtkresources_h with a custom command
FAILED: gtk/gtkresources.h
"C:\gtk-build\gtk\x64\release\bin\glib-compile-resources.EXE" "gtk/gtk.gresources.xml" "--sourcedir" "C:/gtk-build/build/x64/release/gtk3-24/_gvsbuild-meson/gtk" "--sourcedir" "C:/gtk-build/build/x64/release/gtk3-24/gtk" "--sourcedir" "../gtk" "--c-name" "_gtk" "--internal" "--generate" "--target" "gtk/gtkresources.h" "--manual-register"
[125/645] Generating gtkresources_c with a custom command
FAILED: gtk/gtkresources.c
"C:\gtk-build\gtk\x64\release\bin\glib-compile-resources.EXE" "gtk/gtk.gresources.xml" "--sourcedir" "C:/gtk-build/build/x64/release/gtk3-24/_gvsbuild-meson/gtk" "--sourcedir" "C:/gtk-build/build/x64/release/gtk3-24/gtk" "--sourcedir" "../gtk" "--c-name" "_gtk" "--internal" "--generate" "--target" "gtk/gtkresources.c" "--manual-register" "--dependency-file" "gtk/gtkresources.c.d"
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "H:\library\libgtk\gvsbuild\gvsbuild\utils\builder.py", line 493, in build
    if self.__build_one(p):
  File "H:\library\libgtk\gvsbuild\gvsbuild\utils\builder.py", line 624, in __build_one
    skip_deps = proj.build()
  File "H:\library\libgtk\gvsbuild\gvsbuild\projects.py", line 897, in build
    Meson.build(self, meson_params='-Dtests=false -Ddemos=false -Dexamples=false')
  File "H:\library\libgtk\gvsbuild\gvsbuild\utils\base_builders.py", line 76, in build
    self.builder.exec_ninja(params='install', working_dir=ninja_build)
  File "H:\library\libgtk\gvsbuild\gvsbuild\utils\builder.py", line 908, in exec_ninja
    self.__execute(self.__sub_vars(cmd), working_dir=working_dir, add_path=add_path, env=self.vs_env)
  File "H:\library\libgtk\gvsbuild\gvsbuild\utils\builder.py", line 948, in __execute
    subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
  File "C:\gtk-build\tools\python.3.9.2\tools\lib\subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'ninja install' returned non-zero exit status 1.
Error: gtk3 build failed

**Comment by danyeaw** [comment]
@zhmmmm Could you please provide more information on your computer setup, and what command you are using? There isn't enough details here to try to reproduce this.

**Comment by danyeaw** [comment]
No response, and there isn't enough information here to help triage this. Please open a new issue if you are still having trouble.

**Comment by Wcubed** [comment]
I had this problem when it was building `libpng`.
For anyone who ends up here while looking for a solution to this problem (like I did), this solved it for me:
`gsvbuild build libpng --clean` (replace libpng with whatever package the build failed at)
`gsvbuild build gtk4 --fast-build`
You can also simply do `gsvbuild build gtk4 --clean`, but that is going to take a bunch longer :)
