### ISSUE TITLE
[Documentation] Could the main README clarify which versions of python are supported?

### ISSUE THREAD

**Issue by rubyFeedback** [wingtk/gvsbuild#438]
Yo guys,

I am the docu-improve-guy back again. :P

Right now I am trying the instructions on my win10 laptop.

The "Building" part mentions this:

"Python 3.6 (install in C:\Python36 or use the --python-dir option to tell the script the correct location), or other package like Miniconda 3"

I have the latest python installed, though, which is higher than 3.6; it is 3.8.7

Naturally my question when reading the README is whether these
python versions work.

When I do:

    python .\build.py build -p x64 gtk3

Then I get the error:

    "module 'ctypes' has no attribute 'windll'

So now I am not sure why this error shows. Perhaps I use the wrong python version?

This is why I think it would be helpful if the main README could clarify this. Perhaps
I am using the wrong python version, or perhaps the above error is due to another
reason.

(Actually, the error comes from utils/simple_ui.py line 42,
in script_title, ctypes.windll.kernel32.GetConsoleTitleW(buf, 256) which
is confusing me a bit ... why is 32 there? Should it not be 64 if I use
the above commandline?)

For the record I also did:

    python .\build.py build gtk3

But I get the same ctypes error. I have to debug a little bit, perhaps
my python is incomplete or I may have installed several python 
versions ... my laptop is a mess right now. Anyway the TL;DR part
is that it would be useful if the main README could clarify
which python versions should work (and someone actually
trying it and NOT failing, unlike me :P ).

**Comment by petersasi** [comment]
Hi,
I do not feel to be the right guy to answer but I remember to have seen this is not because the Python _version_ you are using but the _flavour_ i.e. do not use the minGW python, but install a proper windows build of python. 3.8.x should work (worked for me).
Excuse me if I am wrong.

Also, I think Arvind would say "would you mind creating a PR to the improved version of the README" ? 😅

Cheers,
Peter

**Comment by danyeaw** [comment]
The README has been updated to walk through installing all the dependencies with choco. If further enhancements are needed, please open a new issue. Thanks!
