### ISSUE TITLE
CI is failing due to libsoup

### ISSUE THREAD

**Issue by danyeaw** [wingtk/gvsbuild#459]
@nacho in 49f5182 you enabled libsoup on CI, but it looks like the CI has been failing since then. Do you know why it is failing, or should we remove it from the CI until it is resolved?

**Comment by nacho** [comment]
It seems to fail cloning a submodule, let’s remove it for now

Enviado desde mi iPhone

**Comment by danyeaw** [comment]
@nacho Sounds good. Fixed by 5223bd4 👍
