### ISSUE TITLE
libgxps build is broken

### ISSUE THREAD

**Issue by danyeaw** [wingtk/gvsbuild#464]
In https://github.com/wingtk/gvsbuild/commit/830d3dd00f1cb61afb76b7fb86facdd295a5df42, @nacho mentioned that the libgxps build is broken by removing the postfix patch from libtiff.

**Comment by nacho** [comment]
This should be fixed though see https://github.com/wingtk/gvsbuild/commit/62c92c7bce05f282ca0197e05f898192375bbb1b

**Comment by danyeaw** [comment]
Thanks @nacho !
