### ISSUE TITLE
pycairo/pygobject can break exe from pyinstaller on py3.8 and up.

### ISSUE THREAD

**Issue by mhertz** [wingtk/gvsbuild#475]
As title, I had issues with this, and googling it let me to very nice workaround by your own Dan Yeaw, thanks alot, which I just applied other-place. Adding this snippet right over 'added_dirs [];' in __init__.py's of pycairo and pygobject fixes this, as is issue with trailing semicolon in PATH as ticket explains here: https://github.com/pyinstaller/pyinstaller/issues/6100 despite cannot be seen in windows advanced system settings, but can in 'echo %PATH%' from cmd. Could you please be so kind to add that, so we don't need supply own patches and overwrite the ones you use, for pycairo/pygobject, or use sed lines etc after installing from said wheels? Thanks alot in advance!

**Comment by danyeaw** [comment]
@mhertz Thanks for the idea. Shouldn't we fix this upstream though in https://gitlab.gnome.org/GNOME/pygobject?

**Comment by mhertz** [comment]
Thanks alot mate for your fast reply and workaround, much appreciated! :) Apologize for being slow to respond back, sorry.

Yes, splendid idea, though not the best at PRs, but hope decent, and thanks for adding context the last times, appreciate that, maybe I should add a post underneath and explain little, like you did, though don't have time currently, also not best at explaining, but regardless. Thanks again!

https://gitlab.gnome.org/GNOME/pygobject/-/merge_requests/193
https://github.com/pygobject/pycairo/pull/248

**Comment by mhertz** [comment]
@danyeaw I don't suppose it could be considered adding this little change, even before/if get's merged upstream? It's a pretty big issue imho, as would expect many building pycairo/pygobject are gonna freeze them, and as far as I see the trailing semicolon is inserted by windows, despite not showing it under environment variables "GUI", only 'echo %PATH%' from cmd shows it. Just like the bcrypt patch to librsvg I mean, in which was added before merged upstream, though granted PR first submitted after the gvsbuild patch, if remember correct, but regardless. 

I understand if you feel otherwise of-course :)

Thanks regardless.

**Comment by danyeaw** [comment]
@mhertz Do you want to propose how gvsbuild may resolve this with a PR?

**Comment by mhertz** [comment]
Sure, and thanks alot again, much appreciated! :)

**Comment by mhertz** [comment]
Just wanted to add that I think it's windows doing this, making the issue much more pressing. I ssh'd into a family members win10 PC, and same story, so now we have 4 reports with this so far(two in linked thread and two from me).

In short, there's a user PATH env-var with only one entry:
````
%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;
````
This gets added at end of system PATH env-var, seen only through 'echo %path%' from cmd. That entry makes it possible to get the windows store opening and prompting you to install e.g. latest python, when running 'python' into a cmd-prompt, without python added in PATH or cwd in it's install-folder. If adding extra PATH entries to system PATH from the 'Environment Variables' applet or whatever called, then 'echo %path%' still shows trailing semicolon, that's not so surpricing, but if deleting the user PATH entry, then still trailing semicolon under 'echo %path%' and even adding new entry there without trailing semicolon, adds that trailing semicolon regardless - only gets out of this behaviour, by removing semicolon on the user PATH entry, and then after saved the issue is fixed/resolved! So in short, not even a bad installer but windows itself doing this! Googling that user PATH entry also shows a bunch others having this entry, with that trailing semicolon! Just thought to mention here. Thanks.
