### ISSUE TITLE
Pixbuf.new_from_file crashes loading gif, ico or bmp images 

### ISSUE THREAD

**Issue by cas--** [wingtk/gvsbuild#489]
We have encountered a [Deluge issue](https://dev.deluge-torrent.org/ticket/3501#comment:13) on Windows when attempting to load any `gif` or `ico` files which would resulting in a hard crash of Deluge.

This can be replicated by opening a png image followed by an ico image (or vice versa) resulting in a crash:

```
from gi.repository.GdkPixbuf import Pixbuf
Pixbuf.new_from_file("any.gif")
Pixbuf.new_from_file("any.ico")
<stdin>:1: Warning: cannot register existing type 'GdkPixbufGdipAnim'
<stdin>:1: Warning: g_once_init_leave: assertion 'result != 0' failed
<stdin>:1: Warning: g_object_new_with_properties: assertion 'G_TYPE_IS_OBJECT (object_type)' failed
```
I found an old Inkscape bug [​https://bugs.launchpad.net/inkscape/+bug/1467103](https://bugs.launchpad.net/inkscape/+bug/1467103) but they worked around it.

It likely is related to gvsbuild using [native_windows_loaders=true](https://github.com/wingtk/gvsbuild/blob/b6e8b545580e0115c6c9c06ad61f60041d87b619/gvsbuild/projects.py#L510) which disables gdk-pixbuf loaders for [gif,ico & bmp](https://github.com/GNOME/gdk-pixbuf/blob/b9f04547aa00abab67090995d67e4ad80fe84614/gdk-pixbuf/meson.build#L15)

This could be something that upstream needs to fix but hoping there might be a workaround that could be implemented in gvsbuild

**Comment by cas--** [comment]
@nacho I assume this is related or duplicate of #240, would using `-Dbuiltin_loaders=all` as suggested by @fanc999 be the best solution here?

**Comment by mhertz** [comment]
Humble polite bump :)

Anyway, I wanted to make a PR for this, as per the nice research/solution by Cas provided here(unless he wants to himself of-course), but in the mist of testing and reading up on it, then I was in doubt about what specifically you wanted in said PR(likewise as per previous post by Cas).

If wanting keep the (experimental) native loader, then can fix this crashing issue by either using 'builtin_loaders=windows' I found(so just including the native gdi+ loader directly into dll), or include them all with 'builtin_loaders=all' as per Cas above. Then, can also just drop the gdi+ loader entirely and not add any built-in, or even add builtin_loaders=all for good meassure regardless(one gnome team-member recommended that setting on windows, and also made a ticket about making it default in feature, in which maintainer answered fine with him, though ticket still open - also stated easier deployment in docs). 

Thanks in advamce as usual :)

**Comment by cas--** [comment]
@danyeaw @nacho Any guidance for @mhertz here?

**Comment by danyeaw** [comment]
I don't have a strong opinion on this, setting `builtin_loaders=all` sounds reasonable to me. Could someone please submit a PR?

**Comment by nacho** [comment]
Does it work if you run "gdk-pixbuf-query-loaders --update-cache" ?

**Comment by mhertz** [comment]
Thanks Cas.

Thanks @danyeaw, sure will, though need to know as per previous notion if you want it in addition to, or replaced with, 'native_windows_loaders=true' ? (they are not mutually exclusive and both scenarious fixes this - plus as stated, another 2 extra fixes too)

Thanks @nacho, no unfortunetly doesn't(also is run from the project file during build, but i'm sure you know that already).

Strange that the native loader works, though only if embedded and not if dynamic loaded...

Appreciate your replies guys :)

**Comment by danyeaw** [comment]
Are there any issues with us removing `native_windows_loaders=true`?

**Comment by mhertz** [comment]
I don't know if @nacho still experience some missing file formats in his software without, as per last posted thread by Cas.

Anyway, least intrusive change to current setup regarding this issue, maybe until decided more, I believe would be to continue include the native loader, just embedded instead of external, so adding 'builtin_loaders=windows', strangely fixing it too, but your call of-course if wanna go with 'builtin_loaders=all' with or without native loader.

**Comment by mhertz** [comment]
I believe not. 

With or without native though?

Thanks much @nacho

**Comment by mhertz** [comment]
Thanks alot guys! @cas-- @danyeaw @nacho :)

https://github.com/wingtk/gvsbuild/pull/603
