### ISSUE TITLE
jcphuff-sse2.asm with error

### ISSUE THREAD

**Issue by bigvzhang** [wingtk/gvsbuild#502]
Dear,

I got error  on windows7 and vs2015. Could you please look into it?

[build.log](https://github.com/wingtk/gvsbuild/files/8228582/build.log)

**Comment by bigvzhang** [comment]
I found a directory C:\Program Files\nasm, and renamed the directory. Then it passed.

**Comment by danyeaw** [comment]
@bigvzhang Thanks for submitting the issue. Windows 7 was EOL over two years ago, and I don't have a way to try to reproduce this. Did you already have NASM installed to C:\Program Files\nasm before you started trying to use gvsbuild?

**Comment by bigvzhang** [comment]
Yes, I did.

**Comment by danyeaw** [comment]
Closing this issue, if you have tools like nasm installed separately outside gvsbuild, you need to remove them or rename them.
