### ISSUE TITLE
Error on downloading pcre patch https://wrapdb.mesonbuild.com/v2/pcre_8.37-2/get_patch

### ISSUE THREAD

**Issue by martinfischer8** [wingtk/gvsbuild#507]
I'm trying to build gtk3 on Windows 10 x64  by following the steps in the readme.
Building fails when getting a patch from mesonbuild.com. The patch seems to be available but I run into a certificate problem.

The relevant part of the output is here:
```
Downloading pcre source from https://sourceforge.net/projects/pcre/files/pcre/8.37/pcre-8.37.tar.bz2
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)>
Downloading pcre source from https://github.com/wingtk/gvsbuild/releases/download/PCRE-8.37/pcre-8.37.tar.bz2
Download size: 1557603
Downloading: ..........
Downloading pcre patch from https://wrapdb.mesonbuild.com/v2/pcre_8.37-2/get_patch
A fallback URL could be specified using patch_fallback_url key in the wrap file

meson.build:2001:2: ERROR: WrapDB connection failed to https://wrapdb.mesonbuild.com/v2/pcre_8.37-2/get_patch with error <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)>
```

**Comment by bigvzhang** [comment]
I also had this problem.  I try to resolve the problem by download and patch it as:

> wget https://wrapdb.mesonbuild.com/v2/pcre_8.37-2/get_patch  -O pcre_patch.zip
> then copy the content to pcre_8.37.**

But, I got another problem:

>   Creating library gobject\gobject-2.0.lib and object gobject\gobject-2.0.exp
> [457/789] Compiling C object gio/gio-2.0-0.dll.p/gwin32packageparser.c.obj
> FAILED: gio/gio-2.0-0.dll.p/gwin32packageparser.c.obj
> "cl" "-Igio\gio-2.0-0.dll.p" "-Igio" "-I..\gio" "-I." "-I.." "-Iglib" "-I..\glib" "-Igobject" "-I..\gobject" "-Igmodule" "-I..\gmodule" "-ID:/MyLib/GTKV4.6.1/gtk/x64/release/bin/../include" "/MD" "/nologo" "/showIncludes" "/W2" "/O2" "/Zi" "/FImsvc_recommended_pragmas.h" "/wd4035" "/wd4715" "/wd4116
> " "/wd4046" "/wd4068" "/wo4090" "/utf-8" "-D_GNU_SOURCE" "-DG_ENABLE_DEBUG" "-DG_LOG_DOMAIN=\"GLib-GIO\"" "-DGIO_COMPILATION" "-DGIO_MODULE_DIR=\"D:/MyLib/GTKV4.6.1/gtk/x64/release/lib/gio/modules\"" "-DLOCALSTATEDIR=\"D:/MyLib/GTKV4.6.1/gtk/x64/release/var\"" "/Fdgio\gio-2.0-0.dll.p\gwin32packagepa
> rser.c.pdb" /Fogio/gio-2.0-0.dll.p/gwin32packageparser.c.obj "/c" ../gio/gwin32packageparser.c
> C:\Program Files (x86)\Windows Kits\8.1\include\winrt\roapi.h(56): error C2016: C requires that a struct or union has at least one member
> [459/789] Linking target tests/gobject/override.exe
> ninja: build stopped: subcommand failed.
> Traceback (most recent call last):
>   File "E:\gvsbuild4X\gvsbuild\utils\builder.py", line 589, in build
>     if self.__build_one(p):
>   File "E:\gvsbuild4X\gvsbuild\utils\builder.py", line 743, in __build_one
>     skip_deps = proj.build()
>   File "E:\gvsbuild4X\gvsbuild\projects\glib.py", line 40, in build
>     Meson.build(self)
>   File "E:\gvsbuild4X\gvsbuild\utils\base_builders.py", line 88, in build
>     self.builder.exec_ninja(params="install", working_dir=ninja_build)
>   File "E:\gvsbuild4X\gvsbuild\utils\builder.py", line 1091, in exec_ninja
>     self.__execute(
>   File "E:\gvsbuild4X\gvsbuild\utils\builder.py", line 1152, in __execute
>     subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
>   File "subprocess.py", line 364, in check_call
> subprocess.CalledProcessError: Command 'ninja install' returned non-zero exit status 1.
> Error: glib build failed

**Comment by robertpelloni** [comment]
Install Let's Encrypt R3 certificate on your machine: https://letsencrypt.org/certs/lets-encrypt-r3.der

**Comment by martinfischer8** [comment]
Thanks, that did it.
