### ISSUE TITLE
So many issues when I install GTK on my Windows 11

### ISSUE THREAD

**Issue by Howell1618** [wingtk/gvsbuild#509]
I can not understand why it still use so many command line to install this GTK tool!!!  It isn't a platform to build a UI interface? Why don't you use it to build a UI installation interface for this tool itself?!!!   However, I followed the steps but still met a lot of errors and finally I gave up to install this fxcking tool!

**Comment by Howell1618** [comment]
Also, I worry about these installation steps may hurt my system.... I already have Python 3.10 and VS2019, but it still install them to another folder. WTF!!!

**Comment by danyeaw** [comment]
We understand you are frustrated, but this is an open source project and isn't the place for these types of comments. I think it would be great as well if we could install GTK in Windows without compiling it from source, but we are all collaborating on gvsbuild in our free time.

The installation steps are meant to help someone who doesn't have any of the dependencies installed. If you already have your system setup, then you don't need to reinstall things. If you think this could be more clear in the README, we would appreciate a pull request. The installation steps shouldn't hurt your system, you can undo any `choco install` with a `choco uninstall`.

If you have an actual issue to post, please post details on what you tried and what errors you are getting.
