### ISSUE TITLE
Error: Missing 'stack.prop'

### ISSUE THREAD

**Issue by zesinger** [wingtk/gvsbuild#589]
Hello
I strictly followed the steps (with copy/paste), it all worked until the build, just after sending "gvsbuild build gtk3" or "gvsbuild build gtk4", I have the message:
`Error: Missing 'stack.prop' file on directory 'C:\gtk-build\github\gvsbuild\.venv\Scripts\gvsbuild.exe\patches'.
Wrong or missing --patches-root-dir option?`
Whatd did I do wrong, please?
Thanks
David

**Comment by FeldTheorie** [comment]
Same problem here. I successfully built a couple weeks back with the old build method.

Reverting to commit 482b49b3d909ddf772a12d25164f513c4f1fa13b i was able to build with the old method without error (GTK 4.6.3).

**Comment by zesinger** [comment]
I am going to try that, thanks for your answer

**Comment by zesinger** [comment]
It doesn't work either:

`
Cleaning up the build environment
Checking msys tool
Using C:\tools\msys64 for msys installation
Checking Msvc tool

Visual Studio installation(s) found:
    Visual Studio Build Toolsÿ2019 @ C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    Visual Studio Professionalÿ2019 @ C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional

Using Visual Studio at None
Traceback (most recent call last):
  File "C:\gtk-build\github\gvsbuild\build.py", line 43, in <module>
    args.func(args)
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\parser.py", line 161, in do_build
    builder = Builder(opts)
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 126, in __init__
    self.__check_vs(opts)
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 416, in __check_vs
    output = self.__check_good_vs_install(opts, opts.vs_install_path, True)
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 362, in __check_good_vs_install
    vcvars_bat = os.path.join(vs_path, "VC", "bin", "amd64", "vcvars64.bat")
  File "C:\Python310\lib\ntpath.py", line 78, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
`

**Comment by maammer** [comment]
I was using VS2022 to build as suggested in the build instructions.

**Comment by danyeaw** [comment]
Try running `gvsbuild build gtk3 --patches-root-dir patches`

**Comment by stillouyng** [comment]
I managed to use
`gvsbuild build gtk3 --patches-root-dir _path to patches_`
it located on smth like "gvsbuild/pathces"

**Comment by danyeaw** [comment]
Thanks @zesinger, @maammer, and @stillouyng for reporting the issue. This should now be fixed 👍
