### ISSUE TITLE
Unable to Import GTK in python file in window 10 x64

### ISSUE THREAD

**Issue by lifetedy** [wingtk/gvsbuild#628]
I am unable to import GTK in python file both in anaconda and IDLE(python 3.10 x64 bit) interpreter show ModuleNotFoundError: No module named 'gtk'. after gvsbuild is done.  can anyone help?

**Comment by danyeaw** [comment]
@lifetedy Have you used `pip install` to install the wheels you built with gvsbuild?

What Python code are you trying to run?

**Comment by lifetedy** [comment]
thank you danyeaw  for your replay.  how i  install  the wheels for gvsbuild?  the code i want to run is  EspeakGUI
[eSpeakGUI.zip](https://github.com/wingtk/gvsbuild/files/9242140/eSpeakGUI.zip)

**Comment by danyeaw** [comment]
Hi @lifetedy,

Create a virtualenv that you want to run eSpeakGUI from.

Using PowerShell you can install both the wheels with:

```
Get-ChildItem C:\gtk-build\build\x64\release\*\dist\*.whl | ForEach-Object -process { python -m pip install $_ }
```

or you can manually go to the C:\gtk-build\build\x64\release directory and install the wheel for PyGObject and pycairo, they should be in the dist folder for each. You install them using `pip install *.whl`.

Then install any other dependencies you need and launch your program.

**Comment by danyeaw** [comment]
I'm assuming this wasn't an issue in gvsbuild and just some help was needed, so I'm closing this issue.
