### ISSUE TITLE
Couldn't find include 'GdkPixbuf-2.0.gir'

### ISSUE THREAD

**Issue by kaholau** [wingtk/gvsbuild#634]
Hi, I run `gvsbuild build --vs-ver=16 --enable-gi --py-wheel gobject-introspection gtk4 pycairo pygobject adwaita-icon-theme hicolor-icon-theme` and somehow fail to build librsvg. Any idea? Thank you.

`Creating library vs16\release\x64\libpixbufloader-svg.lib and object vs16\release\x64\libpixbufloader-svg.exp
Generating code
Finished generating code
Generating vs16\release\x64\Rsvg-2.0.gir...
        C:\gtk-build\tools\python.3.10.5\tools\python.exe C:\gtk-build\gtk\x64\release\bin\g-ir-scanner  --verbose -no-libtool   --namespace=Rsvg        --nsversion=2.0         --pkg=pango --extra-library=libxml2     --library=rsvg-2.0      --add-include-path=C:\gtk-build\gtk\x64\release\bin\..\share\gir-1.0    --include=GLib-2.0 --include=GObject-2.0        --include=Gio-2.0 --include=cairo-1.0   --include=GdkPixbuf-2.0         --pkg-export=librsvg-2.0        --cflags-begin  -I..\include                    -I.\vs16\release\x64\librsvg            -IC:\gtk-build\gtk\x64\release\include\gdk-pixbuf-2.0   -IC:\gtk-build\gtk\x64\release\include\pango-1.0        -IC:\gtk-build\gtk\x64\release\include\gio-win32-2.0    -IC:\gtk-build\gtk\x64\release\include\glib-2.0         -IC:\gtk-build\gtk\x64\release\lib\glib-2.0\include     -IC:\gtk-build\gtk\x64\release\include\harfbuzz         -IC:\gtk-build\gtk\x64\release\include          -IC:\gtk-build\gtk\x64\release\include\libxml2 -DRSVG_COMPILATION       -utf-8  --cflags-end    --c-include=librsvg/rsvg.h      --filelist=vs16\release\x64\librsvg\Rsvg_2_0_gir_list   -L.\vs16\release\x64 -LC:\gtk-build\gtk\x64\release\lib -LC:\gtk-build\gtk\x64\release\bin      -o vs16\release\x64\Rsvg-2.0.gir
Couldn't find include 'GdkPixbuf-2.0.gir' (search path: '['C:\\gtk-build\\gtk\\x64\\release\\bin\\..\\share\\gir-1.0', 'C:\\gtk-build\\gtk\\x64\\release\\share', 'gir-1.0', 'C:\\gtk-build\\gtk\\x64\\release\\share\\gir-1.0']')
NMAKE : fatal error U1077: 'C:\gtk-build\tools\python.3.10.5\tools\python.exe' : return code '0x1'
Stop.
Traceback (most recent call last):
  File "C:\Users\khlau\.local\pipx\venvs\gvsbuild\lib\site-packages\gvsbuild\utils\builder.py", line 537, in build
    if self.__build_one(p):
  File "C:\Users\khlau\.local\pipx\venvs\gvsbuild\lib\site-packages\gvsbuild\utils\builder.py", line 673, in __build_one
    skip_deps = proj.build()
  File "C:\Users\khlau\.local\pipx\venvs\gvsbuild\lib\site-packages\gvsbuild\projects\librsvg.py", line 52, in build
    self.exec_vs(cmd)
  File "C:\Users\khlau\.local\pipx\venvs\gvsbuild\lib\site-packages\gvsbuild\utils\base_project.py", line 113, in exec_vs
    self.builder.exec_vs(
  File "C:\Users\khlau\.local\pipx\venvs\gvsbuild\lib\site-packages\gvsbuild\utils\builder.py", line 949, in exec_vs
    self.__execute(
  File "C:\Users\khlau\.local\pipx\venvs\gvsbuild\lib\site-packages\gvsbuild\utils\builder.py", line 1051, in __execute
    subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
  File "C:\Python310\lib\subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'nmake -f makefile.vc CFG=release PREFIX=C:\gtk-build\gtk\x64\release PYTHON=C:\gtk-build\tools\python.3.10.5\tools\python.exe install INTROSPECTION=1' returned non-zero exit status 2.
Error: librsvg build failed`

**Comment by danyeaw** [comment]
Hi @kaholau, do you have a `GdkPixbuf-2.0.gir` file in `C:\gtk-build\gtk\x64\release\share\gir-1.0`?

**Comment by kaholau** [comment]
@danyeaw Thank you for your reply. 
I do not have GdkPixbuf-2.0.gir in C:\gtk-build\gtk\x64\release\share\gir-1.0
However, I can sure gdk-pixbuf is built successfully.  I think it is gdk-pixbuf 2.42.8.

**Comment by danyeaw** [comment]
@kaholau Could you please try running:

```
gvsbuild build --vs-ver=16 --from-scratch --enable-gi --py-wheel gobject-introspection gtk4 pycairo pygobject adwaita-icon-theme hicolor-icon-theme
```

It doesn't seem right that gdk-pixbuf doesn't have a .gir available.

**Comment by kaholau** [comment]
Thank you. It works.

**Comment by danyeaw** [comment]
Excellent, closing this since a --from-scratch rebuild fixed it.
