### ISSUE TITLE
both method for installing gvsbuild failed, with vs studio 2019

### ISSUE THREAD

**Issue by alphahui** [wingtk/gvsbuild#650]
I have tried installing gvsbuild with both method
for the first method, when i do "pipx install gvsbuild", it shows pipx is an external command, so I have added it to the PATH environemt variable manually. Then when I continue doing "pipx install gvsbuild", I received the error of:

Fatal error from pip prevented installation. Full pip output in file:
    C:\Users\User\.local\pipx\logs\cmd_2022-08-30_10.28.48_pip_errors.log
Some possibly relevant errors from pip install:
    ERROR: Could not find a version that satisfies the requirement gvsbuild (from versions: none)
    ERROR: No matching distribution found for gvsbuild
Error installing gvsbuild.

in the log:

PIP STDOUT
PIP STDERR
ERROR: Could not find a version that satisfies the requirement gvsbuild (from versions: none)
ERROR: No matching distribution found for gvsbuild

------------------
Then I tried the second method, when I do "pip install .", I received the error of:

Directory '.' is not installable. File 'setup.py' not found.
You are using pip version 9.0.1, however version 22.2.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

Is it because of the version of pip I am using? Any help would be great! Thank you!

**Comment by danyeaw** [comment]
Yes, I think this is related to the version of Python and pip you are running. What does `python --version` return?

**Comment by alphahui** [comment]
Thank you! I have updated pip and python. Then it did the installation, but i receieved another error when doing gvsbuild build gtk3. Thus, I think I will make a new issue instead.
