### ISSUE TITLE
python error with gvsbuild build for vs 2019 Buildtools not Community

### ISSUE THREAD

**Issue by alphahui** [wingtk/gvsbuild#651]
I have ran the command "gvsbuild build  --tools-root-dir "C:\'Program Files (x86)\Microsoft Visual Studio'\2019\BuildTools\tools" --vs-ver 16 gtk3" to build gtk3 for my vs 2019 version. And i received the following error, the ' in the directory is there as the dir name contains spaces.
....
C:\gtk-build\src\pango-1.50.9.tar.xz - Download finished
C:\gtk-build\src\1.5.10.tar.gz - Download finished
C:\gtk-build\src\gtk%2B-3.24.34.tar.xz - Download finished
Building project nuget (6.2.1)
'C:\'Program' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "C:\gtk-build\github\gvsbuild\.venv\lib\site-packages\gvsbuild\utils\builder.py", line 531, in build
    if self.__build_one(p):
  File "C:\gtk-build\github\gvsbuild\.venv\lib\site-packages\gvsbuild\utils\builder.py", line 624, in __build_one
    proj.prepare_build_dir()
  File "C:\gtk-build\github\gvsbuild\.venv\lib\site-packages\gvsbuild\utils\base_project.py", line 390, in prepare_build_dir
    self.unpack()
  File "C:\gtk-build\github\gvsbuild\.venv\lib\site-packages\gvsbuild\tools.py", line 325, in unpack
    self.mark_deps = self.setup(True)
  File "C:\gtk-build\github\gvsbuild\.venv\lib\site-packages\gvsbuild\tools.py", line 298, in setup
    subprocess.check_call(cmd, shell=True)
  File "C:\Program Files\Python310\lib\subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'C:\'Program Files (x86)\Microsoft Visual Studio'\2019\BuildTools\tools\nuget-6.2.1\nuget.exe install python -Version 3.10.6 -OutputDirectory C:\'Program Files (x86)\Microsoft Visual Studio'\2019\BuildTools\tools' returned non-zero exit status 1.
Error: python build failed

Not sure if it is related to me adding the ' in the directory for the spaces. Any help would be great! Thanks.

**Comment by danyeaw** [comment]
`--tools-root-dir` is for providing a place where Python, nuget, and other gvsbuild get installed. Are you trying to put those tools in your Visual Studio directory?

**Comment by alphahui** [comment]
Thank you for the reply. I am only trying to ask it to install for vs 2019. But It would choose the "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community" to install and send out an error which says the folder is missing some files for the installation. Thus, I try to use `--tools-root-dir` to have it choose the BuildTools folder instead of the community one, such that it can find the required files. However, this lead to the error as mentioned above.

**Comment by danyeaw** [comment]
@alphahui I think the option you are looking for is `--vs-install-path`, not `--tools-root-dir`.

**Comment by alphahui** [comment]
Thank you! It worked, I did "gvsbuild build --vs-install-path 'C:Program Files (x86)\Microsoft Visual Studio\2019\Community'  gtk3". I thought --vs-install-path would navigate the files to C:Program Files (x86)\Microsoft Visual Studio\2019 and give me the same previous error of opening the wrong folder, but it actually need to give the dir to the Community folder.
