### ISSUE TITLE
Using GCC instead of msvc?

### ISSUE THREAD

**Issue by alex-tee** [wingtk/gvsbuild#689]
This is more of a question than an issue, but there are some libraries that use custom makefiles instead of a proper build system, and they use gcc-compatible flags and use `ar` and other GNU tools directly. Is it possible to use the mingw gcc compiler suite somehow? And if so, what is the proper way to do it?

Also, if anyone knows, are there any issues when mixing gcc-produced libs with msvc-produced libs?

I kinda managed to make the build succeed by passing `CC="$path_to_mingw_gcc_installed_from_choco"` but I'm not sure if this is the right way to do it. There's also a compiler in msys2

**Comment by danyeaw** [comment]
@alex-tee No, that's not the aim of this project. The whole point is to compile GTK with MSVC. If you want to use mingw gcc, then I recommend just using msys2. :+1:
