### ISSUE TITLE
Update libffi

### ISSUE THREAD

**Issue by pbor** [wingtk/gvsbuild#700]
Our project is pointing to https://github.com/centricular/libffi which is deprecated and replaced by https://gitlab.freedesktop.org/gstreamer/meson-ports/libffi.git

However the new repo does not seem to have a good recent tag we can point to...

@nirbheek can a tag be added? I also see a new libffi version was released so maybe the repo needs a rebase

**Comment by nirbheek** [comment]
@pbor I just pushed a `meson-3.2.9999.4` tag that points to current HEAD. Yes, the project needs to be rebased, it was forked off many years ago. There's a very old WIP MR here: https://gitlab.freedesktop.org/gstreamer/meson-ports/libffi/-/merge_requests/1 but it's a bunch of work, probably 1-2 weeks.

**Comment by pbor** [comment]
Thanks!
