### ISSUE TITLE
[2023.1.0] Building libffi fails due to no-longer-valid commit reference

### ISSUE THREAD

**Issue by mitchhentges** [wingtk/gvsbuild#811]
```
> gvsbuild build libffi
...
libffi:Exception Command 'git checkout -f e610a433b1323a4d0658dda5e0fd627f8364669a' returned non-zero exit status 128.
```

Looking at [that commit on GitHub](https://github.com/xclaesse/libffi/commit/e610a433b1323a4d0658dda5e0fd627f8364669a), it says:

> This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.

I'm guessing [this change](https://github.com/wingtk/gvsbuild/pull/790/files#diff-c0f9fe2b17a418fa5c6a5a362ac7d825f522e0fc6fa9f0fc40bf2e0c3244a2e9R31) is the cause, and there's been some exciting action in the `libffi` fork since `2023.1.0` was released :)

-----

Using [release `2022.6.0`](https://github.com/wingtk/gvsbuild/releases/tag/2022.6.0) works around this issue for me.

**Comment by SwiftPengu** [comment]
Fixed this by switching to the `freedesktop.org` meson repo:

[patches/libffi.py]
```py
@project_add
class Libffi(GitRepo, Meson):
    def __init__(self):
        Project.__init__(
            self,
            "libffi",
            # repo_url="https://github.com/xclaesse/libffi.git",
            repo_url="https://gitlab.freedesktop.org/gstreamer/meson-ports/libffi.git",
            fetch_submodules=False,
            tag="f0215d17",
            dependencies=["ninja", "meson"],
        )

    def build(self):
        Meson.build(self)
        self.install(r"LICENSE share\doc\libffi")
```

**Comment by danyeaw** [comment]
@xclaesse it looks like the commit we were using was rebased. If I switch to the latest commit, do you think that would be OK? Do you think you would be able to avoid rebasing again or do you recommend we swap back to the other meson repo until this is merged?

**Comment by xclaesse** [comment]
You can rebase the PR on latest release, or you can use the version from wrapdb.

**Comment by xclaesse** [comment]
I don't think you should rely on my branch commit id, it's a pr, I can do force push and rebases.

**Comment by danyeaw** [comment]
Thanks @mitchhentges for submitting the issue 👍
