### ISSUE TITLE
Building gtk4 failed: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xce in position 5278: invalid continuation byte

### ISSUE THREAD

**Issue by asthetik** [wingtk/gvsbuild#835]
enter the command line `gvsbuild build gtk4` and return the below issue:

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xce in position 5278: invalid continuation byte.
Please see the PowerShell output log for details.

Python version: 3.11.1
Visual Studio version: Visual Studio Community 2022

[admin Windows PowerShell.txt](https://github.com/wingtk/gvsbuild/files/10529542/admin.Windows.PowerShell.txt)

**Comment by danyeaw** [comment]
Hi @asthetik, which version of PowerShell and Windows are you running? It looks like the colors are being converted into symbols. Have you tried with Windows Terminal or cmd.exe?

**Comment by asthetik** [comment]
Windows version: Windows 11 22H2(Enterprise Edition) 
PowerShell version: 5.1.22621.963

i try to do in cmd and the error returned is different from the last time
[CWindowssystem32cmd.exe.txt](https://github.com/wingtk/gvsbuild/files/10530034/CWindowssystem32cmd.exe.txt)

**Comment by asthetik** [comment]
Hi @danyeaw, I previously installed git and python in the cmd(`scoop install -g git && scoop install -g python`). i reinstall git and python through windows exe now. and then run `gvsbuild build gtk4`, it has been built successfully.

I don't know what the reason is, the only way to solve it.

**Comment by danyeaw** [comment]
Hi @asthetik, glad you figured it out! In the README we use choco, but based on my testing the most reliable way to install Python in Windows is with the official Windows installer. Maybe we should update the README to recommend this as well.
