### ISSUE TITLE
glib fails to build; any ideas?

### ISSUE THREAD

**Issue by steveseguin** [wingtk/gvsbuild#846]
Apologies if this is an issue with my system, but the install script `gvsbuild build gtk3` fails for me with glib.

```
(tar) Exporting glib
Building project glib (2.74.5)
ninja: error: 'C:/release/lib/pcre2-8.lib', needed by 'glib/glib-2.0-0.dll', missing and no known rule to make it
```
![image](https://user-images.githubusercontent.com/2575698/216874843-37366d5b-d247-4fda-babb-55d6c13a1555.png)

Tempted to just format my PC and try again, but wondering if anyone knew a solution first?

btw, Thank you for such a great installer; it was much needed for Windows.

**Comment by danyeaw** [comment]
Hey @steveseguin, have you tried to run `gvsbuild build --from-scratch gtk3`? This will wipe everything and try again.

**Comment by steveseguin** [comment]
Didn't work, but thank you for the suggestion.  I'll close this issue and just format / try again later.
