### ISSUE TITLE
Build does not happen and is not reported properly when Visual Studio is not on disk C

### ISSUE THREAD

**Issue by Alternmill** [wingtk/gvsbuild#856]
I had a problem with building gtk4 and the problem was not reported properly:
TypeError: expected str, bytes or os.PathLike object, not NoneType 
(unfortunately do not have a screenshot)

But it went something like this:

It found my Visual Studio at D:\visual and then just broke in the builder.py file
![image](https://user-images.githubusercontent.com/103444031/219206855-e61be2fe-c87f-422a-902f-6e56923058c7.png)

opts.vs_install_path was None and it broke everything down the line

I assume that this code does not work in the case where Visual Studio is not on disc C but I might be wrong

**Comment by Alternmill** [comment]
Just making that function return a path to my Visual Studio made everything work, so I assume it just was not able to find it on its own

**Comment by danyeaw** [comment]
@Alternmill Did you try using `--vs-install-path`?

**Comment by Alternmill** [comment]
@danyeaw , nope, I directly changed the python code, as I had no idea there was this option. But thanks for answering
