### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte

### ISSUE THREAD

**Issue by yalikes** [wingtk/gvsbuild#859]
When I trying to build gtk4. I got this error.
after I did some inspection, I found that, in gvsbuild/utils/builder.py line 377, we use **utf-8** to decode vcvars_bat's output.

```
        return subprocess.check_output(
            f'cmd.exe /c ""{vcvars_bat}"{add_opts}>NUL && set"',
            encoding="utf-8",
            shell=True,
            text=True,
        )
```
but assuming user use **utf-8**  is not always true.
for example I am a Windows 11 Chinese edition user, when I use `chcp` command to check my active code page, I got 936, this means my computer use gbk encoding rather than utf-8 encoding.
my environment variable contains some Chinese character couse this UnicodeDecodeError.
so, do we need check shell's active code page on Windows?

**Comment by danyeaw** [comment]
@yalikes Thanks for the bug report!

We do want to use utf-8 since that will be the default with Python in the future. I think the issue was the `text=True`, since that uses the default encoding. I created a PR, would you mind giving it a spin?
