### ISSUE TITLE
Fails to build due to `https://gitlab.freedesktop.org` expired SSL certificate error

### ISSUE THREAD

**Issue by tigregalis** [wingtk/gvsbuild#886]
# Context

I am running `gvsbuild build gtk3`, using Windows 10.

When it is unable to locate a dependency, it attempts to clone the git repository from `https://gitlab.freedesktop.org` and build from there, but can't.

For example, it failed on cloning `gperf` into `C:\gtk-build\src\git-exp`.

```
  File "C:\Python310\lib\subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'git clone https://gitlab.freedesktop.org/tpm/gperf.git C:\gtk-build\src\git-exp\gperf' returned non-zero exit status 128.
Error: gperf build failed
```

After a couple attempts and reading the log more carefully, I saw the SSL certificate expiry issue.
```
(git) Cloning https://gitlab.freedesktop.org/tpm/gperf.git to C:\gtk-build\src\git-exp\gperf
Cloning into 'C:\gtk-build\src\git-exp\gperf'...
fatal: unable to access 'https://gitlab.freedesktop.org/tpm/gperf.git/': SSL certificate problem: certificate has expired
gperf:Exception Command 'git clone https://gitlab.freedesktop.org/tpm/gperf.git C:\gtk-build\src\git-exp\gperf' returned
non-zero exit status 128.
Removing the destination dir ...
```

Visiting `https://gitlab.freedesktop.org` it doesn't seem like there's an expired SSL certificate so maybe there's an issue with my system setup.

To work around this, I created an account at `https://gitlab.freedesktop.org`, added an SSH key, and manually cloned into `C:\gtk-build\src\git-exp\gperf`. This did the trick.

Unfortunately, I couldn't apply this trick deeper into the build:

1. When building `cairo` it encountered the same problem, when `cairo`'s build script was attempting to build `pixman`.

```
meson.build:653:0: ERROR: Git command failed: ['c:\\program files\\git\\cmd\\git.EXE', 'clone', 'https://gitlab.freedesktop.org/pixman/pixman.git', 'pixman']
```

2. Unfortunately, as the path wasn't fully qualified in the command it wasn't clear to me where to apply the same trick.

I'm completely unfamiliar with `meson` etc. and C build systems, so I didn't have a clue where to look. I'm simply trying to use `gtk3-rs` from Rust.

# Workaround

With the help of a friend, I realised I could ignore SSL verification in git, via setting the environment variable `GIT_SSL_NO_VERIFY=true`.

This did the trick, and the build succeeded, but clearly doesn't fix the underlying issue of the expired SSL certificate (or perhaps an issue with my SSL setup).

**Comment by danyeaw** [comment]
Hi @tigregalis, this sounds like an upstream issue with gitlab.freedesktop.org. They have an issue tracker here: https://gitlab.freedesktop.org/freedesktop/freedesktop

**Comment by tigregalis** [comment]
Ok, I've submitted an issue there.

**Comment by danyeaw** [comment]
Since I don't think this is a bug with gvsbuild, I am going to close this one.
