### ISSUE TITLE
GTK4 app using latest gvsbuild output crashes upon rendering an embedded matplotlib FigureCanvasGTK4Agg

### ISSUE THREAD

**Issue by wooly17** [wingtk/gvsbuild#888]
I know this is likely not the correct place to submit this issue -- I suspect it is a `cairo` issue, but I could not figure out where to submit it.  **_Hoping for some guidance on how to proceed -- would I submit to Gnome's GitLab?_**

Last year, I used gvsbuild to compile GTK 4.6.4 for Python 3.10.4, and it worked great.  My team recently upgraded to Python 3.11.2, and after re-compiling GTK (4.8.3 a month ago, and latest 4.10.0 the other day), we have the issue detailed below.

## ISSUE
The app has an embedded `matplotlib` Figure Canvas (specifically, `FigureCanvasGTK4Agg`).  With the newly compiled GTK (4.8.3, 4.10.0), it crashes immediately (GUI never appears on screen), without any logging.  Stepping through in a debugger would sometimes give the output below.  Commenting out the line that packs the figure canvas into the window allows the app to run fine.

Output from debugger (not sure where `_pixman_log_error` is...  the log statement comes from within cairo's .pyd file)

```
*** BUG ***
In ???: The expression bits == NULL || (rowstride_bytes % sizeof (uint32_t)) == 0 was false
Set a breakpoint on '_pixman_log_error' to debug

(python.exe:12860): Gsk-WARNING **: 17:25:51.577: drawing failure for render node GskCairoNode: out of memory

Process finished with exit code -1073741819 (0xC0000005)
```

Through a lot of trial & error, we got past the problem by downgrading `cairo` from `1.17.8` to `1.17.6` (this also required downgrading `harfbuzz` from latest to `6.0.0`), but we do experience some other instability that has me wondering if I introduced some other incompatibility by doing so.

## Minimal code to reproduce
```
import gi
gi.require_version('Gtk', '4.0')
from gi.repository import Gtk, GLib, Gio

from matplotlib.backends.backend_gtk4agg import FigureCanvasGTK4Agg as FigureCanvas
import matplotlib.pyplot as plt


class MPLTestApp(Gtk.Application):
   def __init__(self):
      Gtk.Application.__init__(self, application_id=None, flags=Gio.ApplicationFlags.FLAGS_NONE)
      self.window = None
      self.connect('activate', self.on_activate)

   def on_activate(self, application):
      self.window = MainWindow(application=application)
      self.window.connect('close-request', self.on_close_request)
      self.window.present()

   def on_close_request(self, _window):
      self.quit()


class MainWindow(Gtk.ApplicationWindow):
   def __init__(self, *args, **kwargs):
      super(MainWindow, self).__init__(*args, **kwargs)

      box = Gtk.Box()
      self.set_child(box)

      figure, axis = plt.subplots()

      canvas = FigureCanvas(figure)
      canvas.set_size_request(500, 300)

      box.append(canvas)


app = MPLTestApp()
app.run(None)

```

**Comment by danyeaw** [comment]
Hi @wooly17, this does sound like an upstream bug. Cairo's repo is at https://gitlab.freedesktop.org/cairo/cairo 👍
