### ISSUE TITLE
typelib

### ISSUE THREAD

**Issue by pdalet** [wingtk/gvsbuild#913]
Hello,
I've built with success gtk3, gtk4 and openssl with gvsbuild and visual studio 2022 community. 
With gobject-instrospection gvsbuild.exe doesn't generate all the .typelib files.
How generate all the .typelib specially  "gtk-3.0.typelib"
Thank a lot.
Philippe

**Comment by danyeaw** [comment]
Hi @pdalet, what command are you running? Do you use the `--enable-gi` option?
