### ISSUE TITLE
[discussion] urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)>

### ISSUE THREAD

**Issue by voltagex** [wingtk/gvsbuild#921]
Yes, I know this is fixed in #174, but I'm trying to work out why it's happening in the first place
e.g. https://distfiles.dereferenced.org/pkgconf/pkgconf-1.9.4.tar.gz and https://github.com/mesonbuild/meson/releases/download/1.0.1/meson-1.0.1.tar.gz are trusted in Windows 10, but Python fails to validate distfiles.dereferenced.org (but not GitHub? Why?)

Some digging through https://stackoverflow.com/a/52074591 and https://bugs.python.org/msg203711 suggests SSLContext.load_default_certs() might be enough? If this doesn't work, the certifi package can be used as noted in the StackOverflow answer.

I would have opened this as a discussion rather than an issue if discussions were enabled.

**Comment by danyeaw** [comment]
@voltagex I enabled discussions, so I am going to close this issue 👍
