### ISSUE TITLE
IME support in gvsbuild?

### ISSUE THREAD

**Issue by Adriatic1** [wingtk/gvsbuild#922]
Hi, this is more an inquiry than an issue report.
I am investigating how the users of my GTK program can use Japanese input for example.
Looking at the GTK stack recently built in gvsbuild, I see that release/etc folder only contains "im-multipress.conf" file, there are no .dll files for other supported gtk3 input modules.

Is multi-language input supported (for example Japanese) natively by GTK3 gvsbuild or do I need to build some additional component?
Is there any GTK demo app to check if this works correctly?
Any pages explaining how this should work (especially on non-Linux build) ?

The reason for this is a report of an user of my program (on macOS though) that the older releases worked fine on Japanese input, and the new ones don't. I did not make any changes in this regards, so I suspect something in GTK stack could be a culprit so I wanted to test this with gvsbuild.

**Comment by danyeaw** [comment]
@Adriatic1 Our goal is to support IME. Whether it works or not, I am not sure.

**Comment by Adriatic1** [comment]
OK, thanks.

**Comment by danyeaw** [comment]
@Adriatic1 is it working for you?

**Comment by Adriatic1** [comment]
It did not seem to work at the time, so that's why I asked.
I've since reverted back to Mingw (uses up to 50% less memory in some use cases; fixes crash in clipboard wait code, deep in GTK part of the stack, when pasting some RTF).
