### ISSUE TITLE
python3 not found building pycairo

### ISSUE THREAD

**Issue by tjwilli58** [wingtk/gvsbuild#967]
I'm having the same problem as issue https://github.com/wingtk/gvsbuild/issues/899.
I have python 3.9 and 3.11 installed, but I edited my PATH so that only python 3.9 is found. At the beginning of my PATH, I have
```
C:\Users\Tim\AppData\Local\Programs\Python\Python39
C:\Users\Tim\AppData\Local\Programs\Python\Python39\Scripts
C:\Users\Tim\AppData\Local\Programs\Python\Launcher
```
From a `x64 Native Tools Command Prompt for VS 2022` shell, I then create a virtual environment in the gvsbuild directory and activate it with
```
py -3.9 -m venv .venv39
.\.venv39\Scripts\activate.bat
pip install .
```

Now build `cairo` in a clean (empty) build-dir. This is just to show that it builds.`pycairo` will be built later.
`gvsbuild buid --build-dir D:\gstreamer\gvsbuild_testpy39 cairo`

I'll update with the result of building `pycairo` in a bit.

**Comment by tjwilli58** [comment]
result of building cairo:
```
Project(s) built:
    ninja                     (1.539 s)
    meson                     (8.761 s)
    pkgconf                   (27.383 s)
    cmake                     (15.392 s)
    zlib                      (16.798 s)
    libpng                    (21.318 s)
    freetype                  (30.431 s)
    gperf                     (19.545 s)
    expat                     (33.716 s)
    fontconfig                (38.365 s)
    win-iconv                 (8.595 s)
    gettext                   (162.655 s)
    libffi                    (56.652 s)
    pcre2                     (50.821 s)
    glib                      (280.006 s)
    pixman                    (28.875 s)
    cairo                     (192.980 s)

(.venv39) d:\GitClones\gvsbuild>
```

**Comment by tjwilli58** [comment]
pycairo result:
```
(tar) Exporting pycairo
Building project pycairo (1.23.0)
The Meson build system
Version: 1.1.1
Source dir: D:\gstreamer\gvsbuild_testpy39\build\x64\release\pycairo
Build dir: D:\gstreamer\gvsbuild_testpy39\build\x64\release\pycairo\_gvsbuild-meson
Build type: native build
Project name: pycairo
Project version: 1.23.0
C compiler for the host machine: cl (msvc 19.36.32532 "Microsoft (R) C/C++ Optimizing Compiler Version 19.36.32532 for x64")
C linker for the host machine: link link 14.36.32532.0
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program nonexistingprogram found: NO

meson.build:15:15: ERROR: python3 not found

A full log can be found at D:\gstreamer\gvsbuild_testpy39\build\x64\release\pycairo\_gvsbuild-meson\meson-logs\meson-log.txt
Traceback (most recent call last):
  File "d:\GitClones\gvsbuild\.venv39\lib\site-packages\gvsbuild\utils\builder.py", line 525, in build
    if self.__build_one(p):
  File "d:\GitClones\gvsbuild\.venv39\lib\site-packages\gvsbuild\utils\builder.py", line 661, in __build_one
    skip_deps = proj.build()
  File "d:\GitClones\gvsbuild\.venv39\lib\site-packages\gvsbuild\projects\pycairo.py", line 38, in build
    Meson.build(self)
  File "d:\GitClones\gvsbuild\.venv39\lib\site-packages\gvsbuild\utils\base_builders.py", line 49, in build
    self._setup_meson_and_ninja(ninja_build, meson_params, add_path)
  File "d:\GitClones\gvsbuild\.venv39\lib\site-packages\gvsbuild\utils\base_builders.py", line 81, in _setup_meson_and_ninja
    self.exec_vs(cmd, add_path=add_path)
  File "d:\GitClones\gvsbuild\.venv39\lib\site-packages\gvsbuild\utils\base_project.py", line 195, in exec_vs
    self.builder.exec_vs(
  File "d:\GitClones\gvsbuild\.venv39\lib\site-packages\gvsbuild\utils\builder.py", line 935, in exec_vs
    self.__execute(
  File "d:\GitClones\gvsbuild\.venv39\lib\site-packages\gvsbuild\utils\builder.py", line 1039, in __execute
    subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
  File "C:\Users\Tim\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'd:\GitClones\gvsbuild\.venv39\Scripts\python.exe d:\gstreamer\gvsbuild_testpy39\tools\meson-1.1.1\meson.py setup d:\gstreamer\gvsbuild_testpy39\build\x64\release\pycairo d:\gstreamer\gvsbuild_testpy39\build\x64\release\pycairo\_gvsbuild-meson --prefix d:\gstreamer\gvsbuild_testpy39\gtk\x64\release --buildtype debugoptimized' returned non-zero exit status 1.
Error: pycairo build failed

(.venv39) d:\GitClones\gvsbuild>
```
[meson-log.txt](https://github.com/wingtk/gvsbuild/files/11714806/meson-log.txt)
[gvsbuild-log.txt](https://github.com/wingtk/gvsbuild/files/11714816/gvsbuild-log.txt)

@danyeaw , I need to learn how to create a minimal meson project using python still

**Comment by tjwilli58** [comment]
Found this in `meson-log.txt` for cairo build:
```
Running test binary command:  D:\gstreamer\gvsbuild_testpy39\build\x64\release\cairo\_gvsbuild-meson\meson-private\sanitycheckcpp.exe
C++ compiler for the build machine: cl (msvc 19.36.32532 "Microsoft (R) C/C++ Optimizing Compiler Version 19.36.32532 for x64")
C++ linker for the build machine: link link 14.36.32532.0
Build machine cpu family: x86_64
Build machine cpu: x86_64
Host machine cpu family: x86_64
Host machine cpu: x86_64
Target machine cpu family: x86_64
Target machine cpu: x86_64
'utf-8' codec can't decode byte 0x90 in position 2: invalid start byte
Unusable script 'd:\\GitClones\\gvsbuild\\.venv39\\Scripts\\python.exe'
Program python3 found: YES (d:\GitClones\gvsbuild\.venv39\Scripts\python.exe)
Library m found: NO
Dependency gtk+-2.0 skipped: feature gtk2-utils disabled
Running compile:
Working directory:  C:\Users\Tim\AppData\Local\Temp\tmpl7dwsg0x
Command line:  cl C:\Users\Tim\AppData\Local\Temp\tmpl7dwsg0x\testfile.c /nologo /showIncludes /utf-8 /EP /nologo /showIncludes /utf-8 /EP /Od /Oi- 
```
`Program python3 found: YES (d:\GitClones\gvsbuild\.venv39\Scripts\python.exe)`

**Comment by tjwilli58** [comment]
Successfully build `pycairo` using `--use-env` switch
```
Successfully built pycairo-1.23.0.tar.gz and pycairo-1.23.0-cp39-cp39-win_amd64.whl
Processing .\dist\pycairo-1.23.0-cp39-cp39-win_amd64.whl
Installing collected packages: pycairo
Successfully installed pycairo-1.23.0

Project(s) built:
    ninja                     (0.000 s)
    meson                     (0.016 s)
    pkgconf                   (0.797 s)
    cmake                     (0.016 s)
    zlib                      (0.172 s)
    libpng                    (1.574 s)
    freetype                  (1.100 s)
    gperf                     (2.710 s)
    expat                     (0.930 s)
    fontconfig                (6.150 s)
    win-iconv                 (0.944 s)
    gettext                   (31.334 s)
    libffi                    (2.554 s)
    pcre2                     (0.955 s)
    glib                      (2.657 s)
    pixman                    (0.781 s)
    cairo                     (2.018 s)
    pycairo                   (277.140 s)
```
```
(.venv39) d:\GitClones\gvsbuild>pip show pycairo
Name: pycairo
Version: 1.23.0
Summary: Python interface for cairo
Home-page: https://pycairo.readthedocs.io
Author:
Author-email:
License: LGPL-2.1-only OR MPL-1.1
Location: d:\gitclones\gvsbuild\.venv39\lib\site-packages
Requires:
Required-by:
```

**Comment by danyeaw** [comment]
Hi @tjwilli58, which version of gvsbuild are you using? I think `--use-env` is an old command line option right?

**Comment by tjwilli58** [comment]
I'm using the latest commit from the repos

Author:		Dan Yeaw <dan@yeaw.me>
Author date:	2 days ago (6/8/2023 8:19:11 PM)
Committer:	Ignacio Casal Quinteiro <nacho.resa@gmail.com>
Commit date:	2 days ago (6/9/2023 3:08:21 AM)
Commit hash:	0f8553f2c39dc8437540cdb5370e5cebe8a5eb7c
Child:		Commit index
Parent:		979a32e0

Update librsvg to version 2.56.1
Contained in branches:
main

Contained in no tag

Derives from tag: 2023.6.0 + 5 commits

**Comment by tjwilli58** [comment]
Looks like using `--py-wheel` is the trick. 
I just built pycario with
`gvsbuild build --build-dir d:\gstreamer\gvsbuild_testpy39  pycairo --py-wheel`

I'm going to try this with `--from-scratch`.

**Comment by tjwilli58** [comment]
Built everything I need but the "problem" packages successfully;
```
(.venv311) d:\GitClones\gvsbuild>gvsbuild build --build-dir d:\gstreamer\gvsbuild gstreamer gst-plugins-base gst-plugins-good gst-plugins-bad gst-plugins-ugly --from-scratch
```
```
Project(s) built:
    meson                     (9.146 s)
    ninja                     (1.532 s)
    pkgconf                   (26.600 s)
    cmake                     (11.850 s)
    win-iconv                 (21.294 s)
    gettext                   (187.137 s)
    libffi                    (51.037 s)
    zlib                      (8.792 s)
    pcre2                     (40.025 s)
    glib                      (274.365 s)
    orc                       (37.504 s)
    gstreamer                 (73.073 s)
    opus                      (28.400 s)
    ogg                       (26.592 s)
    gst-plugins-base          (186.898 s)
    nasm                      (1.544 s)
    msys2                     (0.000 s)
    libjpeg-turbo             (81.172 s)
    libyuv                    (46.716 s)
    perl                      (10.133 s)
    libvpx                    (431.861 s)
    gst-plugins-good          (233.522 s)
    gst-plugins-bad           (422.243 s)
    gst-plugins-ugly          (32.401 s)
```
`(.venv311) d:\GitClones\gvsbuild>gvsbuild build --build-dir d:\gstreamer\gvsbuild --enable-gi --py-wheel gst-python`

I'm thinking this should also build pygobject, pycairo.

**Comment by tjwilli58** [comment]
Build stopped with `python3 not found` error with it got to pycairo. I needed to use `--use-env` switch to build pycairo.

**Comment by tjwilli58** [comment]
I also needed `--use-env` for `pygobject` and `gst-python`.

I then thought about 

https://github.com/wingtk/gvsbuild#add-gtk-to-your-environmental-variables

I never thought I'd need to do that, since I'm not actually using Gtk in my application. I went and updated `PATH, LIB, INCLUDE` with  my `--build-dir` target directory, i.e.

```cmd
set path=d:\gvsbuild\gtk\x64\release\bin;%path% 
set lib=d:\gstreamer\gvsbuild\gtk\x64\release\lib;%lib%
set include=d:\gstreamer\gvsbuild\gtk\x64\release\include;d:\gstreamer\gvsbuild\gtk\x64\release\include\cairo;d:\gstreamer\gvsbuild\gtk\x64\release\include\glib-2.0;d:\gstreamer\gvsbuild\gtk\x64\release\include\gobject-introspection-1.0;d:\gstreamer\gvsbuild\gtk\x64\release\lib\glib-2.0\include;%include%
```

No such luck.

**Comment by tjwilli58** [comment]
Still haven't set up a minimal meson project to look into this further. I may look into it this weekend. Using `--with-env` seems to get around the issue though. 

I'm wondering if an older version of `meson`  could provide some insight? I saw this https://github.com/mesonbuild/meson/issues/11687 and this https://github.com/mesonbuild/meson/pull/11705 on `import('python')`  and I wonder if this broke something.

@danyeaw , is there a way to specify an older version of `meson` to use with `gvsbuild` ?

**Comment by danyeaw** [comment]
I'm trying to understand how your environment is different than the one in the README. You are trying to use x64 Native Tools Command Prompt for VS 2022 instead of PowerShell, what else is different is everything else installed the same way?

**Comment by tjwilli58** [comment]
I remember reading somewhere a while back that you needed to build from a x64 Native Tools Command Prompt for VS 2022. There is also a Developer PowerShell for VS 2022, which as I understand it basically sets up the same environment variables. I can't find that reference anymore. I thought it was from gtreamer [README](https://gitlab.freedesktop.org/gstreamer/gstreamer#windows-prerequisites-setup), but I don't see it there anymore. There is this in that README:

> Since version 0.59.0, Meson automatically activates the Visual Studio
> environment on Windows if no other compilers (gcc, clang, etc) are found. 

Except for that, my environment is basically what is in your README. That, and not modifying PATH, LIB, INCLUDE as you describe in https://github.com/wingtk/gvsbuild#add-gtk-to-your-environmental-variables.

I wasn't considering that as part of the build process, but something that is done after the build.

**Comment by tjwilli58** [comment]
Just build pygobject with a "regular" PowerShell. So I guess I **don't** need to run this from a VS 2022 cmd or PS.
I still needed to use `--use-env` though.

**Comment by danyeaw** [comment]
You said basically the same, which setup instructions did you follow exactly and which ones are different?

**Comment by tjwilli58** [comment]
Mainly, I didn't use Chocolately.
I already had installed Python, MSYS2, Git, and VS.

**Comment by danyeaw** [comment]
It isn't necessarily bad that you have to use `--use-env`. However, I think if you want to fix it, you could uninstall everything and remove setting all the env variables, then reinstall things using the README instruction. We know those work and match the setup on our CI system.

**Comment by tjwilli58** [comment]
I’ve been thinking about doing that. I’ll uninstall everything and go the chocolately route.

**Comment by tjwilli58** [comment]
So uninstalled VS2022, all versions of Python, even the Launcher (except for my anaconda, which is not in my PATH), and MSYS2.
I did NOT uninstall my Git, but I did do a `choco install git`.
`choco install visualstudio2022-workload-vctools` is still running. Waiting for that to finish before I `choco install python`. 

- Can I install an older python (3.9) with choco?
- Why it MSYS2 in `C:\tools\msys64` instead of `C:\msys64` ? And what about the Start menu shortcuts? Not crazy about that aspect.

**Comment by tjwilli58** [comment]
Looks like I found an answer on the python version:

https://community.chocolatey.org/packages/python3/3.7.3

`choco install python3 --version=3.9`

**Comment by tjwilli58** [comment]
Not liking python in system path.

**Comment by tjwilli58** [comment]
Installed python in user (LOCALAPPDATA) area. Created a virtual environment, pipx installed gvsbuild, and built with

`gvsbuild build  --build-dir D:\gstreamer\gtk-build --enable-gi pycairo`

successfully. No `python3 not found` error. Also built

`gvsbuild build  --build-dir D:\gstreamer\gtk-build --enable-gi --py-wheel pycairo pygobject gst-python`  

I suspect I was missing something in my VS2022 install before. Maybe installing that as Administrator helped. I don't think Python needs to be installed as admin, 
Not sure about MSYS2.
