### ISSUE TITLE
Debug build of fontconfig refers to expat.dll instead of libexpatd.dll

### ISSUE THREAD

**Issue by code-affinity** [wingtk/gvsbuild#971]
I am using commit 9d7f76c of gvsbuild (the first commit that had a fix for issue #961).

I deleted C:\gtk-build

I ran the command
`gvsbuild build --platform x64 --vs-ver 17 --msys-dir C:\tools\msys64 --configuration debug fontconfig`

When it was finished, I reviewed the contents of C:\gtk-build\gtk\x64\debug\bin.  I saw fontconfig-1.dll and libexpatd.dll as expected.

I used [Dependency Walker](https://dependencywalker.com/) to view the dependencies of fontconfig-1.dll.  I observed that it depends on expat.dll, not libexpatd.dll.

I repeated the same experiment with a release configuration.  Then I used Dependency Walker to review the dependencies of C:\gtk-build\gtk\x64\release\bin.  It correctly depends on libexpat.dll.

The effect of this problem at the application level is that debug configurations of applications that link to fontconfig, or any library that transitively links to fontconfig (such as cairo) fail to launch.  Windows displays an error dialog indicating that expat.dll is missing.

**Comment by code-affinity** [comment]
Research notes:

Reviewing the source code in gvsbuild/projects/fontconfig.py and expat.py, it seems like this issue could only have been caused upstream.  gvsbuild simply downloads the tarballs for both projects and builds them, with no patches to either library.

The DLL name for the expat library changed from expat.dll to libexpat[d].dll in version 2.2.9 way back in 2019, or perhaps even earlier.  (I'm only looking at the [libexpat release notes](https://github.com/libexpat/libexpat/blob/R_2_2_9/expat/Changes), not actual source code changes.)  gvsbuild is currently using version 2.5.0 of expat and version 2.14.2 of fontconfig, which is only a four-month-old version.

It is hard to believe that this problem has been around for four years and never been noticed, so I suspect that I'm doing something wrong.  But my reproduction steps are pretty simple.

gvsbuild/projects/expat.py has only ever referred to version 2.5.0 of that library, ever since it was added as a fontconfig dependency on 11/11/2022. 

The previous version of gvsbuild that we were using successfully (i.e. without an expat.dll name mismatch) was snapshotted on 4/23/2022 (commit 0da585a).  I went back and reviewed our build output from that version.  To my surprise, I found expat.dll, even though that was before expat was added as a dependency on fontconfig.  Was expat included in gvsbuild at that time, just not as a dependency from fontconfig?  When gvsbuild/project.py was refactored into individual modules on 1/23/2022, there was no expat project.  The expat project was added to gvsbuild for the first time when it was added as a dependency for fontconfig on 11/11/2022.  So I don't understand how my 4/23/2022 snapshot came to include a copy of expat.dll.

When gvsbuild switched the fontconfig dependency from libxml2 to expat on 11/11/2022, no changes were made to the way fontconfig was configured or built.  (For example, no build-time configuration option was changed to tell it to use a different XML parsing back end.)  

So there are apparently some pieces of the puzzle that I am missing.

Reviewing the fontconfig code that links to the expat library, I think the result of its package search process for expat is that it simply links with "-lexpat", where expat is the static import library (.lib) name, not the DLL name.  I think fontconfig does not know or care what the DLL is named.

**Comment by code-affinity** [comment]
Revisiting the switch from libxml2 to expat on 11/11/2022, since this change was effected without changing gvsbuild/projects/fontconfig.py, I conclude that fontconfig is automatically searching for an XML parser and selecting whichever one it finds at build time.  So on 11/11/2022, when gvsbuild stopped building libxml2 and started building expat, fontconfig started finding expat instead of libxml2.

I theorized that my problem could be caused by a copy of expat lying around somewhere (but not produced by gvsbuild), and fontconfig found it instead of the desired gvsbuild-produced expat.  I don't understand yet why this problem would only occur for the debug build type, though.

On that theory, I searched my system for other copies of expat.dll.  To my surprise, I found a copy of it in the gvsbuild tree.  In C:/gtk-build/build/x64/debug/fontconfig/_gvsbuild-meson/subprojects/expat-2.2.6.  Somehow fontconfig is being configured to build its own expat library, and it's building an older version than the one configured by gvsbuild/projects/expat.py.

I compared this to C:/gtk-build/build/x64/fontconfig/_gvsbuild-meson.  That folder does not have a subprojects directory at all.

Summary:  Only for a debug build of gvsbuild, fontconfig is somehow pulling in a subproject for an outdated version of the expat library, which uses a different DLL name than the desired version of the expat library.

**Comment by code-affinity** [comment]
Research:  What can cause fontconfig to decide to build an outdated version of expat as a subproject?  

Browsing its source code, I see fontconfig/subprojects/expat.wrap, which selects version 2.2.6 of the expat tarball and selects a patch for that version from wrapdb.mesonbuild.com.

I am not very familiar with autoconf or meson, but my reading of the config files is that fontconfig falls back to an expat subproject if it fails to find an expat library.

So could the problem be that gvsbuild is not building its own expat library for the debug build type?  No, it is being built; I see C:/gtk-build/build/x64/debug/expat with all of the typical content, and C:/gtk-build/gtk/x64/debug/lib/libexpatd.lib.

Hmm.  But the lib name is different.  In C:/gtk-build/build/x64/debug/expat, the library is named libexpatd.dll.  In C:/gtk-build/build/x64/release/expat, the library is named libexpat.lib.

So I bet the problem is that fontconfig doesn't look for the expat library with the "d" suffix.  When it fails to find it, it falls back to building its own expat as a subproject.

**Comment by code-affinity** [comment]
I created https://gitlab.freedesktop.org/fontconfig/fontconfig/-/issues/367

**Comment by danyeaw** [comment]
Thanks @code-affinity for submitting this and researching the issue!

Libvpx does something similar where it creates vpxmd.lib for release builds and vpxmdd.lib for debug. After we build this library, we run a post install action to rename the built file to vpx.lib. We could do something similar for libexpat as well. What do you think?

**Comment by code-affinity** [comment]
I think it might not work.  The problem isn't just that it's the wrong library file name, but it's the wrong library version.  The debug version of fontconfig 2.14.2 is linking to expat.lib library version 2.2.6, not the libexpatd.lib version 2.5.0 as the gvsbuild system intended.

So even if you rename gvsbuild's libexpatd.dll to expat.dll (or maybe you are suggesting the other way around) as a post install action, there will be a version mismatch between the expat library that fontconfig linked against and the expat DLL that is actually present.  Would this cause problems?

To work around the problem for our application, I copied both expat.dll and libexpatd.dll to my application's runtime directory.

**Comment by danyeaw** [comment]
I think if we rename it as a post install step of libexpat, then when fontconfig builds, meson will find the dependency and not rebuild it using the wrap file.

**Comment by code-affinity** [comment]
Oh, now I see what you mean.  Yes, that makes sense.
