### ISSUE TITLE
How does gvsbuild.exe get built?

### ISSUE THREAD

**Issue by g40** [wingtk/gvsbuild#978]
The .exe file I have here is ~106K. Too small for `pyinstaller` or similar?

Which leads on to a related question: How to get a build log? I am trying to work out why libpng fails to build correctly with the git bundled awk.

**Comment by danyeaw** [comment]
Hi @g40! This is a pure Python library built into a Wheel. We depend on the user having Python installed. PyInstaller ships all dependencies including Python itself.

The output is sent to the stdout of the terminal. You could save it to a file if you want.

**Comment by g40** [comment]
Hello @danyeaw 

Quite. What I don't get is how it is built. 

If I run `pyinstaller main.py` I end up with the following where `main.exe` does not do anything. 

What am I missing?

``
>du -h dist/main
21M     dist/main

>ls -a dist/main
.                                              api-ms-win-core-rtlsupport-l1-1-0.dll
..                                             api-ms-win-core-string-l1-1-0.dll
VCRUNTIME140.dll                               api-ms-win-core-synch-l1-1-0.dll
_bz2.pyd                                       api-ms-win-core-synch-l1-2-0.dll
_ctypes.pyd                                    api-ms-win-core-sysinfo-l1-1-0.dll
_decimal.pyd                                   api-ms-win-core-timezone-l1-1-0.dll
_hashlib.pyd                                   api-ms-win-core-util-l1-1-0.dll
_lzma.pyd                                      api-ms-win-crt-conio-l1-1-0.dll
_queue.pyd                                     api-ms-win-crt-convert-l1-1-0.dll
_socket.pyd                                    api-ms-win-crt-environment-l1-1-0.dll
_ssl.pyd                                       api-ms-win-crt-filesystem-l1-1-0.dll
_uuid.pyd                                      api-ms-win-crt-heap-l1-1-0.dll
api-ms-win-core-console-l1-1-0.dll             api-ms-win-crt-locale-l1-1-0.dll
api-ms-win-core-datetime-l1-1-0.dll            api-ms-win-crt-math-l1-1-0.dll
api-ms-win-core-debug-l1-1-0.dll               api-ms-win-crt-process-l1-1-0.dll
api-ms-win-core-errorhandling-l1-1-0.dll       api-ms-win-crt-runtime-l1-1-0.dll
api-ms-win-core-file-l1-1-0.dll                api-ms-win-crt-stdio-l1-1-0.dll
api-ms-win-core-file-l1-2-0.dll                api-ms-win-crt-string-l1-1-0.dll
api-ms-win-core-file-l2-1-0.dll                api-ms-win-crt-time-l1-1-0.dll
api-ms-win-core-handle-l1-1-0.dll              api-ms-win-crt-utility-l1-1-0.dll
api-ms-win-core-heap-l1-1-0.dll                base_library.zip
api-ms-win-core-interlocked-l1-1-0.dll         libcrypto-1_1.dll
api-ms-win-core-libraryloader-l1-1-0.dll       libffi-8.dll
api-ms-win-core-localization-l1-2-0.dll        libssl-1_1.dll
api-ms-win-core-memory-l1-1-0.dll              main.exe
api-ms-win-core-namedpipe-l1-1-0.dll           pyexpat.pyd
api-ms-win-core-processenvironment-l1-1-0.dll  python311.dll
api-ms-win-core-processthreads-l1-1-0.dll      select.pyd
api-ms-win-core-processthreads-l1-1-1.dll      ucrtbase.dll
api-ms-win-core-profile-l1-1-0.dll             unicodedata.pyd

```

**Comment by danyeaw** [comment]
Could you please explain what you are trying to accomplish? Are you trying to package gvsbuild into a standalone exe? What is your use case?

**Comment by g40** [comment]
@danyeaw I am trying to work out how gvsbuild runs. The .exe file installed using pip is tiny. There is no makefile or build script in this repo. So how does gvsbuild.exe come into this world?

why? I’d like to debug some of the python code to understand why libpng fails to build, in the first instance. And then to work out how to add, say, gtkmm and friends to the process.

make sense?

**Comment by danyeaw** [comment]
We build the Wheel that goes to PyPI using a development environment setup and then running `poetry build`. A Wheel is a zip of Python source with some metadata, it should be small.

**Comment by g40** [comment]
@danyeaw: `poetry`, that's the part I was missing. Excellent, thank you.

**Comment by g40** [comment]
Closing.
