### ISSUE TITLE
gtkmm build fails?

### ISSUE THREAD

**Issue by g40** [wingtk/gvsbuild#980]
in glibmm with a fresh clone from this repo. GTK3 and GTK4 both build cleanly, libpng irritation notwithstanding.

Does the glibmm.py file need to resolve a dependency on https://github.com/GNOME/mm-common or similar?

Command line:
```
gvsbuild build --ninja-opts -j=2 --build-dir r:\src\test\gvsbuild\build --msys-dir  r:\apps\msys64 --configuration debug gtkmm
```

Relevant portion of the build log:

```
Executing subproject glibmm-2.68

glibmm-2.68| Project name: glibmm
glibmm-2.68| Project version: 2.76.0
glibmm-2.68| C++ compiler for the host machine: cl (msvc 19.36.32532 "Microsoft (R) C/C++ Optimizing Compiler Version 19.36.32532 for x64")
glibmm-2.68| C++ linker for the host machine: link link 14.36.32532.0
glibmm-2.68| Program python3 found: YES 3.11.4
glibmm-2.68| Run-time dependency sigc++-3.0 found: YES 3.4.0
glibmm-2.68| Run-time dependency glib-2.0 found: YES 2.76.3
glibmm-2.68| Run-time dependency gobject-2.0 found: YES 2.76.3
glibmm-2.68| Run-time dependency gmodule-2.0 found: YES 2.76.3
glibmm-2.68| Run-time dependency gio-2.0 found: YES 2.76.3
glibmm-2.68| Program mm-common-get found: NO
glibmm-2.68| Message: Maintainer mode requires the 'mm-common-get' command. If it is not found,
glibmm-2.68| install the 'mm-common' package, version 1.0.0 or higher.
glibmm-2.68| Program mm-common-get found: NO
```

**Comment by danyeaw** [comment]
Hi @g40, thanks for submitting the issue, I can reproduce it. It looks like pangomm should have a dependency on glibmm, so that it doesn't try to build it as a meson wrap subproject. Would you be interested in submitting a PR with the added dependency?

**Comment by g40** [comment]
@danyeaw: thanks for the reply. yes I'd be happy to do so. But first I have to understand how gvsbuild works :) 

I  had hoped that the fix would be as simple as adding a new dependency to pangomm.py, but this seems to have zero effect.

```
R:\src\test\gvsbuild>git diff gvsbuild\projects\pangomm.py
diff --git a/gvsbuild/projects/pangomm.py b/gvsbuild/projects/pangomm.py
index f514081f..85a72c16 100644
--- a/gvsbuild/projects/pangomm.py
+++ b/gvsbuild/projects/pangomm.py
@@ -35,6 +35,7 @@ class Pangomm(Tarball, Meson):
             dependencies=[
                 "meson",
                 "ninja",
+                "glibmm",
                 "libsigc++",
                 "cairomm",
                 "pango",
```

**Comment by danyeaw** [comment]
Hi @g40, that worked for me. Did you try to rebuild it with `gvsbuild build --clean gtkmm`?

**Comment by g40** [comment]
No, it did not. I am struggling to make sense of typer. I am debugging the codebase using VS Code and the usual Python 3.11 tooling. Yet none of the changes I make in the projects directory appear to get applied. My bad I expect.

**Comment by danyeaw** [comment]
If you are using the development environment instructions in the README, you can run `py -m pip install -e .` to make the install editable, otherwise you can run `pip install .` after each change. You could also use pipx to install poetry and run `poetry install` instead.
