### ISSUE TITLE
.gitignore needs modification?

### ISSUE THREAD

**Issue by g40** [wingtk/gvsbuild#983]
A build seems to leave a lot of artefacts behind, all of which should be ignored I think? An example below, the modified files and those relating to VS Code are work-in-progress.

```
# additions to root of repository folder
build/
export/
dist/
logs/
src/
test/
tools/
```

```
R:\src\test\gvsbuild>git status
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   .gitignore
        modified:   gvsbuild/main.py

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        .vscode/
        build-dbg.cmd
        build/
        dist/
        export/
        checksym.awk
        gvsbuild.code-workspace
        gvsbuild/.vscode/
        logs/
        src/
        test/
        tools/
```

**Comment by danyeaw** [comment]
Hi @g40, the default settings don't have you build the projects in the root of the source directory

**Comment by g40** [comment]
@danyeaw yes, but would it not be an idea of they did? by default that is the most likely scenario no?

**Comment by danyeaw** [comment]
No I don't think so. Most users should install gvsbuild with pipx and build to C:\gtk-build. For developers, I also don't build to my gvsbuild source root.
