### ISSUE TITLE
https://distfiles.dereferenced.org/ is down

### ISSUE THREAD

**Issue by SomnathS09** [wingtk/gvsbuild#994]
The mentioned website is down, getting the error when building :
`gvsbuild build --enable-gi --py-wheel gtk4 pygobject`

```
Exception downloading file 'https://distfiles.dereferenced.org/pkgconf/pkgconf-1.9.5.tar.gz'
<urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
```

**Comment by SomnathS09** [comment]
Attaching pkgconf's issue related to this:
https://github.com/pkgconf/pkgconf/issues/302

**Comment by danyeaw** [comment]
Hi @SomnathS09. Thanks for submitting the issue, I opened a PR yesterday to resolve this, just waiting on a review from one of the other team members:
https://github.com/wingtk/gvsbuild/pull/992

**Comment by FelixBellaby** [comment]
You need to patch the gvs/projects/pkgconf.py file to point to distfiles.ariadne.space instead of disfiles.dereferenced.org, as noted at https://github.com/pkgconf/pkgconf
