### ISSUE TITLE
fontconfig debug build fails.

### ISSUE THREAD

**Issue by g40** [wingtk/gvsbuild#999]
Think this must be a fontconfig build issue, and not a gvsbuild, but posting if anyone has seen this before. The build succeeds in release mode

Searching for the libexpat DLL files shows they exist but the (probably) wrongly named file has been copied to the staging area: `libexpat.dll` instead of the correct `libexpatd.dll`. 

```
>finder -fs -ft libexpat*.dll
Finder  searching r:\src\gtk\gvs-dbg
r:\src\gtk\gvs-dbg\build\x64\debug\expat\_gvsbuild-cmake\libexpatd.dll 370,688 bytes 2023/7/3-11:13:6
r:\src\gtk\gvs-dbg\gtk\x64\debug\bin\libexpat.dll 370,688 bytes 2023/7/3-11:13:6
```

```
gvsbuild build --keep-tools --ninja-opts -j=2 --build-dir r:/src/gtk/gvs-dbg --msys-dir r:/apps/msys64 --log-single --capture-out --configuration debug --verbose fontconfig
```

![image](https://github.com/wingtk/gvsbuild/assets/812250/9067b809-d8fb-4c49-8710-9a15fe0b576d)

**Comment by g40** [comment]
Actually `expat.py` has some special case code to copy `.DLL/.LIB` output files for fontconfig. The renaming `mv` step is incorrect as fontconfig definitely wants  `libexpatd.dll`

```
        if self.builder.opts.configuration == "debug":
            # Fontconfig is looking for libexpat, not libexpatd
            bin_dir = Path(self.builder.gtk_dir) / "bin"
            self.builder.exec_msys(
                ["mv", "libexpatd.dll", "libexpat.dll"],
                working_dir=bin_dir,
            )
            lib_dir = Path(self.builder.gtk_dir) / "lib"
            self.builder.exec_msys(
                ["mv", "libexpatd.lib", "libexpat.lib"],
                working_dir=lib_dir,
            )
```

**Comment by g40** [comment]
I've got a fix for this. Any interest in a PR?

**Comment by danyeaw** [comment]
@g40 Yes, PRs are always welcome!

**Comment by g40** [comment]
@danyeaw Hello there. Just pushed a couple of PR's. But the 2nd may also contain the first. My apologies for any confusion. Do let me know.
